// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"
)

const clearAccountPrimaryFlag = `-- name: ClearAccountPrimaryFlag :exec
UPDATE accounts
SET is_primary = 0
WHERE id = ? AND user_id = ?
`

type ClearAccountPrimaryFlagParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) ClearAccountPrimaryFlag(ctx context.Context, arg ClearAccountPrimaryFlagParams) error {
	_, err := q.db.ExecContext(ctx, clearAccountPrimaryFlag, arg.ID, arg.UserID)
	return err
}

const clearPrimaryAccounts = `-- name: ClearPrimaryAccounts :exec
UPDATE accounts
SET is_primary = 0
WHERE user_id = ? AND status = 'active'
`

func (q *Queries) ClearPrimaryAccounts(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, clearPrimaryAccounts, userID)
	return err
}

const countActiveAccountsByName = `-- name: CountActiveAccountsByName :one
SELECT COUNT(*) AS count
FROM accounts
WHERE user_id = ? AND name = ? AND status = 'active'
`

type CountActiveAccountsByNameParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CountActiveAccountsByName(ctx context.Context, arg CountActiveAccountsByNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAccountsByName, arg.UserID, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveAccountsByNameExcluding = `-- name: CountActiveAccountsByNameExcluding :one
SELECT COUNT(*) AS count
FROM accounts
WHERE user_id = ? AND name = ? AND status = 'active' AND id != ?
`

type CountActiveAccountsByNameExcludingParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
	ID     string `json:"id"`
}

func (q *Queries) CountActiveAccountsByNameExcluding(ctx context.Context, arg CountActiveAccountsByNameExcludingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAccountsByNameExcluding, arg.UserID, arg.Name, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveAccountsByUser = `-- name: CountActiveAccountsByUser :one
SELECT COUNT(*) AS count
FROM accounts
WHERE user_id = ? AND status = 'active'
`

func (q *Queries) CountActiveAccountsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAccountsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts
WHERE id = ? AND user_id = ?
`

type DeleteAccountParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAccount, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const firstActiveAccountID = `-- name: FirstActiveAccountID :one
SELECT id
FROM accounts
WHERE user_id = ? AND status = 'active'
ORDER BY created_at, name
LIMIT 1
`

func (q *Queries) FirstActiveAccountID(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRowContext(ctx, firstActiveAccountID, userID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT
    a.id,
    a.name,
    a.type,
    a.bank_id,
    a.initial_balance,
    a.status,
    a.is_primary,
    a.created_at,
    a.updated_at,
    b.name AS bank_name,
    b.icon_path AS bank_icon
FROM accounts a
LEFT JOIN banks b ON b.id = a.bank_id
WHERE a.id = ? AND a.user_id = ?
`

type GetAccountByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type GetAccountByIDRow struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	Type           string  `json:"type"`
	BankID         *string `json:"bank_id"`
	InitialBalance int64   `json:"initial_balance"`
	Status         string  `json:"status"`
	IsPrimary      int64   `json:"is_primary"`
	CreatedAt      string  `json:"created_at"`
	UpdatedAt      string  `json:"updated_at"`
	BankName       *string `json:"bank_name"`
	BankIcon       *string `json:"bank_icon"`
}

func (q *Queries) GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (GetAccountByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, arg.ID, arg.UserID)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BankID,
		&i.InitialBalance,
		&i.Status,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BankName,
		&i.BankIcon,
	)
	return i, err
}

const getActiveAccountByName = `-- name: GetActiveAccountByName :one
SELECT
    a.id,
    a.name,
    a.type,
    a.bank_id,
    a.initial_balance,
    a.status,
    a.is_primary,
    a.created_at,
    a.updated_at,
    b.name AS bank_name,
    b.icon_path AS bank_icon
FROM accounts a
LEFT JOIN banks b ON b.id = a.bank_id
WHERE a.user_id = ? AND a.status = 'active' AND a.name = ?
LIMIT 1
`

type GetActiveAccountByNameParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

type GetActiveAccountByNameRow struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	Type           string  `json:"type"`
	BankID         *string `json:"bank_id"`
	InitialBalance int64   `json:"initial_balance"`
	Status         string  `json:"status"`
	IsPrimary      int64   `json:"is_primary"`
	CreatedAt      string  `json:"created_at"`
	UpdatedAt      string  `json:"updated_at"`
	BankName       *string `json:"bank_name"`
	BankIcon       *string `json:"bank_icon"`
}

func (q *Queries) GetActiveAccountByName(ctx context.Context, arg GetActiveAccountByNameParams) (GetActiveAccountByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveAccountByName, arg.UserID, arg.Name)
	var i GetActiveAccountByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BankID,
		&i.InitialBalance,
		&i.Status,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BankName,
		&i.BankIcon,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (
    id, user_id, name, type, bank_id, initial_balance, status, is_primary, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, 'active', ?, ?, ?)
`

type InsertAccountParams struct {
	ID             string  `json:"id"`
	UserID         string  `json:"user_id"`
	Name           string  `json:"name"`
	Type           string  `json:"type"`
	BankID         *string `json:"bank_id"`
	InitialBalance int64   `json:"initial_balance"`
	IsPrimary      int64   `json:"is_primary"`
	CreatedAt      string  `json:"created_at"`
	UpdatedAt      string  `json:"updated_at"`
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertAccount,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.BankID,
		arg.InitialBalance,
		arg.IsPrimary,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listAccountsByUserActive = `-- name: ListAccountsByUserActive :many
SELECT
    a.id,
    a.name,
    a.type,
    a.bank_id,
    a.initial_balance,
    a.status,
    a.is_primary,
    a.created_at,
    a.updated_at,
    b.name AS bank_name,
    b.icon_path AS bank_icon
FROM accounts a
LEFT JOIN banks b ON b.id = a.bank_id
WHERE a.user_id = ? AND a.status = 'active'
ORDER BY a.name
`

type ListAccountsByUserActiveRow struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	Type           string  `json:"type"`
	BankID         *string `json:"bank_id"`
	InitialBalance int64   `json:"initial_balance"`
	Status         string  `json:"status"`
	IsPrimary      int64   `json:"is_primary"`
	CreatedAt      string  `json:"created_at"`
	UpdatedAt      string  `json:"updated_at"`
	BankName       *string `json:"bank_name"`
	BankIcon       *string `json:"bank_icon"`
}

func (q *Queries) ListAccountsByUserActive(ctx context.Context, userID string) ([]ListAccountsByUserActiveRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByUserActive, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsByUserActiveRow{}
	for rows.Next() {
		var i ListAccountsByUserActiveRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.BankID,
			&i.InitialBalance,
			&i.Status,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BankName,
			&i.BankIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByUserAndStatus = `-- name: ListAccountsByUserAndStatus :many
SELECT
    a.id,
    a.name,
    a.type,
    a.bank_id,
    a.initial_balance,
    a.status,
    a.is_primary,
    a.created_at,
    a.updated_at,
    b.name AS bank_name,
    b.icon_path AS bank_icon
FROM accounts a
LEFT JOIN banks b ON b.id = a.bank_id
WHERE a.user_id = ? AND a.status = ?
ORDER BY a.name
`

type ListAccountsByUserAndStatusParams struct {
	UserID string `json:"user_id"`
	Status string `json:"status"`
}

type ListAccountsByUserAndStatusRow struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	Type           string  `json:"type"`
	BankID         *string `json:"bank_id"`
	InitialBalance int64   `json:"initial_balance"`
	Status         string  `json:"status"`
	IsPrimary      int64   `json:"is_primary"`
	CreatedAt      string  `json:"created_at"`
	UpdatedAt      string  `json:"updated_at"`
	BankName       *string `json:"bank_name"`
	BankIcon       *string `json:"bank_icon"`
}

func (q *Queries) ListAccountsByUserAndStatus(ctx context.Context, arg ListAccountsByUserAndStatusParams) ([]ListAccountsByUserAndStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByUserAndStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsByUserAndStatusRow{}
	for rows.Next() {
		var i ListAccountsByUserAndStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.BankID,
			&i.InitialBalance,
			&i.Status,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BankName,
			&i.BankIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAccountNames = `-- name: ListActiveAccountNames :many
SELECT name
FROM accounts
WHERE user_id = ? AND status = 'active'
`

func (q *Queries) ListActiveAccountNames(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAccountNames, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountPrimary = `-- name: SetAccountPrimary :exec
UPDATE accounts
SET is_primary = 1
WHERE id = ? AND user_id = ? AND status = 'active'
`

type SetAccountPrimaryParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SetAccountPrimary(ctx context.Context, arg SetAccountPrimaryParams) error {
	_, err := q.db.ExecContext(ctx, setAccountPrimary, arg.ID, arg.UserID)
	return err
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts
SET name = ?, bank_id = ?, initial_balance = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateAccountParams struct {
	Name           string  `json:"name"`
	BankID         *string `json:"bank_id"`
	InitialBalance int64   `json:"initial_balance"`
	UpdatedAt      string  `json:"updated_at"`
	ID             string  `json:"id"`
	UserID         string  `json:"user_id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateAccount,
		arg.Name,
		arg.BankID,
		arg.InitialBalance,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :execrows
UPDATE accounts
SET status = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateAccountStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAccountStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
