// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package sqlc

import (
	"context"
)

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE id = ? AND user_id = ?
`

type DeleteAPITokenParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, deleteAPIToken, arg.ID, arg.UserID)
	return err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, expires_at FROM api_tokens WHERE token_hash = ?
`

type GetAPITokenByHashRow struct {
	ID        string  `json:"id"`
	UserID    string  `json:"user_id"`
	ExpiresAt *string `json:"expires_at"`
}

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (GetAPITokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i GetAPITokenByHashRow
	err := row.Scan(&i.ID, &i.UserID, &i.ExpiresAt)
	return i, err
}

const getAPITokenCreatedAt = `-- name: GetAPITokenCreatedAt :one
SELECT created_at FROM api_tokens WHERE id = ?
`

func (q *Queries) GetAPITokenCreatedAt(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenCreatedAt, id)
	var created_at string
	err := row.Scan(&created_at)
	return created_at, err
}

const getAPITokenExpiresAt = `-- name: GetAPITokenExpiresAt :one
SELECT expires_at FROM api_tokens WHERE token_hash = ?
`

func (q *Queries) GetAPITokenExpiresAt(ctx context.Context, tokenHash string) (*string, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenExpiresAt, tokenHash)
	var expires_at *string
	err := row.Scan(&expires_at)
	return expires_at, err
}

const getAPITokenMeta = `-- name: GetAPITokenMeta :one
SELECT name, token_prefix FROM api_tokens WHERE id = ? AND user_id = ?
`

type GetAPITokenMetaParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type GetAPITokenMetaRow struct {
	Name        string `json:"name"`
	TokenPrefix string `json:"token_prefix"`
}

func (q *Queries) GetAPITokenMeta(ctx context.Context, arg GetAPITokenMetaParams) (GetAPITokenMetaRow, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenMeta, arg.ID, arg.UserID)
	var i GetAPITokenMetaRow
	err := row.Scan(&i.Name, &i.TokenPrefix)
	return i, err
}

const insertAPIToken = `-- name: InsertAPIToken :exec
INSERT INTO api_tokens (id, user_id, name, token_hash, token_prefix, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAPITokenParams struct {
	ID          string  `json:"id"`
	UserID      string  `json:"user_id"`
	Name        string  `json:"name"`
	TokenHash   string  `json:"token_hash"`
	TokenPrefix string  `json:"token_prefix"`
	ExpiresAt   *string `json:"expires_at"`
}

func (q *Queries) InsertAPIToken(ctx context.Context, arg InsertAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, insertAPIToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.ExpiresAt,
	)
	return err
}

const listAPITokensByUser = `-- name: ListAPITokensByUser :many
SELECT id, name, token_prefix, expires_at, last_used_at, created_at
FROM api_tokens WHERE user_id = ? ORDER BY created_at DESC
`

type ListAPITokensByUserRow struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	TokenPrefix string  `json:"token_prefix"`
	ExpiresAt   *string `json:"expires_at"`
	LastUsedAt  *string `json:"last_used_at"`
	CreatedAt   string  `json:"created_at"`
}

func (q *Queries) ListAPITokensByUser(ctx context.Context, userID string) ([]ListAPITokensByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPITokensByUserRow{}
	for rows.Next() {
		var i ListAPITokensByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenPrefix,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPITokenByHash = `-- name: TouchAPITokenByHash :exec
UPDATE api_tokens SET last_used_at = datetime('now') WHERE token_hash = ?
`

func (q *Queries) TouchAPITokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, touchAPITokenByHash, tokenHash)
	return err
}

const touchAPITokenByID = `-- name: TouchAPITokenByID :exec
UPDATE api_tokens SET last_used_at = datetime('now') WHERE id = ?
`

func (q *Queries) TouchAPITokenByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchAPITokenByID, id)
	return err
}
