// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: banks.sql

package sqlc

import (
	"context"
)

const bankExists = `-- name: BankExists :one
SELECT EXISTS(SELECT 1 FROM banks WHERE id = ?) AS ok
`

func (q *Queries) BankExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, bankExists, id)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const listBanks = `-- name: ListBanks :many
SELECT id, name, bic, icon_path, sort_order
FROM banks
ORDER BY sort_order, name
`

func (q *Queries) ListBanks(ctx context.Context) ([]Bank, error) {
	rows, err := q.db.QueryContext(ctx, listBanks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bank{}
	for rows.Next() {
		var i Bank
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bic,
			&i.IconPath,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBank = `-- name: UpsertBank :exec
INSERT INTO banks (id, name, bic, icon_path, sort_order)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    bic = excluded.bic,
    icon_path = excluded.icon_path,
    sort_order = excluded.sort_order
`

type UpsertBankParams struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Bic       *string `json:"bic"`
	IconPath  string  `json:"icon_path"`
	SortOrder int64   `json:"sort_order"`
}

func (q *Queries) UpsertBank(ctx context.Context, arg UpsertBankParams) error {
	_, err := q.db.ExecContext(ctx, upsertBank,
		arg.ID,
		arg.Name,
		arg.Bic,
		arg.IconPath,
		arg.SortOrder,
	)
	return err
}
