// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budget.sql

package sqlc

import (
	"context"
)

const budgetSpent = `-- name: BudgetSpent :one
SELECT CAST(COALESCE(SUM(t.amount), 0) AS INTEGER) AS spent
FROM transactions t
WHERE t.user_id = ?
  AND t.type = 'expense'
  AND (? = '' OR t.account_id = ?)
  AND (? = '' OR t.category_id = ?)
  AND (? = '' OR t.subcategory_id = ?)
  AND t.kind = 'manual'
  AND t.transaction_date >= ?
  AND t.transaction_date < ?
  AND t.transfer_group_id IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM credit_payments cp
    WHERE cp.transaction_id = t.id
      AND cp.exclude_from_stats = 1
  )
`

type BudgetSpentParams struct {
	UserID            string      `json:"user_id"`
	Column2           interface{} `json:"column_2"`
	AccountID         string      `json:"account_id"`
	Column4           interface{} `json:"column_4"`
	CategoryID        *string     `json:"category_id"`
	Column6           interface{} `json:"column_6"`
	SubcategoryID     *string     `json:"subcategory_id"`
	TransactionDate   string      `json:"transaction_date"`
	TransactionDate_2 string      `json:"transaction_date_2"`
}

func (q *Queries) BudgetSpent(ctx context.Context, arg BudgetSpentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, budgetSpent,
		arg.UserID,
		arg.Column2,
		arg.AccountID,
		arg.Column4,
		arg.CategoryID,
		arg.Column6,
		arg.SubcategoryID,
		arg.TransactionDate,
		arg.TransactionDate_2,
	)
	var spent int64
	err := row.Scan(&spent)
	return spent, err
}

const countActiveBudgetConflict = `-- name: CountActiveBudgetConflict :one
SELECT COUNT(*) AS cnt
FROM budgets
WHERE user_id = ?
  AND scope = ?
  AND IFNULL(category_id, '') = IFNULL(?, '')
  AND IFNULL(subcategory_id, '') = IFNULL(?, '')
  AND month = ?
  AND is_active = 1
  AND (?6 = '' OR id != ?6)
`

type CountActiveBudgetConflictParams struct {
	UserID    string      `json:"user_id"`
	Scope     string      `json:"scope"`
	IFNULL    interface{} `json:"IFNULL"`
	IFNULL_2  interface{} `json:"IFNULL_2"`
	Month     string      `json:"month"`
	ExcludeID interface{} `json:"exclude_id"`
}

func (q *Queries) CountActiveBudgetConflict(ctx context.Context, arg CountActiveBudgetConflictParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveBudgetConflict,
		arg.UserID,
		arg.Scope,
		arg.IFNULL,
		arg.IFNULL_2,
		arg.Month,
		arg.ExcludeID,
	)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countActiveBudgetsByUserMonth = `-- name: CountActiveBudgetsByUserMonth :one
SELECT COUNT(*) AS cnt
FROM budgets
WHERE user_id = ?
  AND month = ?
  AND is_active = 1
`

type CountActiveBudgetsByUserMonthParams struct {
	UserID string `json:"user_id"`
	Month  string `json:"month"`
}

func (q *Queries) CountActiveBudgetsByUserMonth(ctx context.Context, arg CountActiveBudgetsByUserMonthParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveBudgetsByUserMonth, arg.UserID, arg.Month)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const deleteBudget = `-- name: DeleteBudget :execrows
DELETE FROM budgets
WHERE id = ? AND user_id = ?
`

type DeleteBudgetParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteBudget(ctx context.Context, arg DeleteBudgetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBudget, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT
    b.id,
    b.user_id,
    b.name,
    b.scope,
    b.category_id,
    c.name AS category_name,
    c.icon AS category_icon,
    b.subcategory_id,
    s.name AS subcategory_name,
    b.amount,
    b.period,
    b.account_id,
    a.name AS account_name,
    b.month,
    b.copy_forward,
    b.rollover,
    b.alert_at_percent,
    b.is_active,
    b.created_at,
    b.updated_at
FROM budgets b
LEFT JOIN categories c ON c.id = b.category_id
LEFT JOIN subcategories s ON s.id = b.subcategory_id
LEFT JOIN accounts a ON a.id = b.account_id
WHERE b.id = ? AND b.user_id = ?
`

type GetBudgetByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type GetBudgetByIDRow struct {
	ID              string  `json:"id"`
	UserID          string  `json:"user_id"`
	Name            string  `json:"name"`
	Scope           string  `json:"scope"`
	CategoryID      *string `json:"category_id"`
	CategoryName    *string `json:"category_name"`
	CategoryIcon    *string `json:"category_icon"`
	SubcategoryID   *string `json:"subcategory_id"`
	SubcategoryName *string `json:"subcategory_name"`
	Amount          int64   `json:"amount"`
	Period          string  `json:"period"`
	AccountID       *string `json:"account_id"`
	AccountName     *string `json:"account_name"`
	Month           string  `json:"month"`
	CopyForward     int64   `json:"copy_forward"`
	Rollover        int64   `json:"rollover"`
	AlertAtPercent  int64   `json:"alert_at_percent"`
	IsActive        int64   `json:"is_active"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

func (q *Queries) GetBudgetByID(ctx context.Context, arg GetBudgetByIDParams) (GetBudgetByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBudgetByID, arg.ID, arg.UserID)
	var i GetBudgetByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Scope,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategoryIcon,
		&i.SubcategoryID,
		&i.SubcategoryName,
		&i.Amount,
		&i.Period,
		&i.AccountID,
		&i.AccountName,
		&i.Month,
		&i.CopyForward,
		&i.Rollover,
		&i.AlertAtPercent,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetPeriod = `-- name: GetBudgetPeriod :one
SELECT
    id,
    budget_id,
    period_start,
    planned_amount,
    rollover_amount,
    created_at,
    updated_at
FROM budget_periods
WHERE budget_id = ? AND period_start = ?
`

type GetBudgetPeriodParams struct {
	BudgetID    string `json:"budget_id"`
	PeriodStart string `json:"period_start"`
}

func (q *Queries) GetBudgetPeriod(ctx context.Context, arg GetBudgetPeriodParams) (BudgetPeriod, error) {
	row := q.db.QueryRowContext(ctx, getBudgetPeriod, arg.BudgetID, arg.PeriodStart)
	var i BudgetPeriod
	err := row.Scan(
		&i.ID,
		&i.BudgetID,
		&i.PeriodStart,
		&i.PlannedAmount,
		&i.RolloverAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasBudgetAlertSent = `-- name: HasBudgetAlertSent :one
SELECT COUNT(*) AS cnt
FROM budget_alert_sent
WHERE budget_id = ? AND period_start = ? AND threshold_percent = ?
`

type HasBudgetAlertSentParams struct {
	BudgetID         string `json:"budget_id"`
	PeriodStart      string `json:"period_start"`
	ThresholdPercent int64  `json:"threshold_percent"`
}

func (q *Queries) HasBudgetAlertSent(ctx context.Context, arg HasBudgetAlertSentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasBudgetAlertSent, arg.BudgetID, arg.PeriodStart, arg.ThresholdPercent)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const insertBudget = `-- name: InsertBudget :exec
INSERT INTO budgets (
    id, user_id, name, scope,
    category_id, subcategory_id, amount, period, account_id,
    month, copy_forward,
    rollover, alert_at_percent, is_active,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertBudgetParams struct {
	ID             string  `json:"id"`
	UserID         string  `json:"user_id"`
	Name           string  `json:"name"`
	Scope          string  `json:"scope"`
	CategoryID     *string `json:"category_id"`
	SubcategoryID  *string `json:"subcategory_id"`
	Amount         int64   `json:"amount"`
	Period         string  `json:"period"`
	AccountID      *string `json:"account_id"`
	Month          string  `json:"month"`
	CopyForward    int64   `json:"copy_forward"`
	Rollover       int64   `json:"rollover"`
	AlertAtPercent int64   `json:"alert_at_percent"`
	IsActive       int64   `json:"is_active"`
	CreatedAt      string  `json:"created_at"`
	UpdatedAt      string  `json:"updated_at"`
}

func (q *Queries) InsertBudget(ctx context.Context, arg InsertBudgetParams) error {
	_, err := q.db.ExecContext(ctx, insertBudget,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Scope,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.Amount,
		arg.Period,
		arg.AccountID,
		arg.Month,
		arg.CopyForward,
		arg.Rollover,
		arg.AlertAtPercent,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertBudgetAlertSent = `-- name: InsertBudgetAlertSent :exec
INSERT INTO budget_alert_sent (budget_id, period_start, threshold_percent, sent_at)
VALUES (?, ?, ?, ?)
`

type InsertBudgetAlertSentParams struct {
	BudgetID         string `json:"budget_id"`
	PeriodStart      string `json:"period_start"`
	ThresholdPercent int64  `json:"threshold_percent"`
	SentAt           string `json:"sent_at"`
}

func (q *Queries) InsertBudgetAlertSent(ctx context.Context, arg InsertBudgetAlertSentParams) error {
	_, err := q.db.ExecContext(ctx, insertBudgetAlertSent,
		arg.BudgetID,
		arg.PeriodStart,
		arg.ThresholdPercent,
		arg.SentAt,
	)
	return err
}

const insertBudgetPeriod = `-- name: InsertBudgetPeriod :exec
INSERT INTO budget_periods (
    id, budget_id, period_start, planned_amount, rollover_amount,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertBudgetPeriodParams struct {
	ID             string `json:"id"`
	BudgetID       string `json:"budget_id"`
	PeriodStart    string `json:"period_start"`
	PlannedAmount  int64  `json:"planned_amount"`
	RolloverAmount int64  `json:"rollover_amount"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}

func (q *Queries) InsertBudgetPeriod(ctx context.Context, arg InsertBudgetPeriodParams) error {
	_, err := q.db.ExecContext(ctx, insertBudgetPeriod,
		arg.ID,
		arg.BudgetID,
		arg.PeriodStart,
		arg.PlannedAmount,
		arg.RolloverAmount,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listActiveBudgetsByUser = `-- name: ListActiveBudgetsByUser :many
SELECT
    b.id,
    b.user_id,
    b.name,
    b.scope,
    b.category_id,
    b.subcategory_id,
    b.amount,
    b.account_id,
    b.month,
    b.alert_at_percent
FROM budgets b
WHERE b.user_id = ? AND b.is_active = 1
  AND (? = '' OR b.month = ?)
`

type ListActiveBudgetsByUserParams struct {
	UserID  string      `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Month   string      `json:"month"`
}

type ListActiveBudgetsByUserRow struct {
	ID             string  `json:"id"`
	UserID         string  `json:"user_id"`
	Name           string  `json:"name"`
	Scope          string  `json:"scope"`
	CategoryID     *string `json:"category_id"`
	SubcategoryID  *string `json:"subcategory_id"`
	Amount         int64   `json:"amount"`
	AccountID      *string `json:"account_id"`
	Month          string  `json:"month"`
	AlertAtPercent int64   `json:"alert_at_percent"`
}

func (q *Queries) ListActiveBudgetsByUser(ctx context.Context, arg ListActiveBudgetsByUserParams) ([]ListActiveBudgetsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveBudgetsByUser, arg.UserID, arg.Column2, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveBudgetsByUserRow{}
	for rows.Next() {
		var i ListActiveBudgetsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Scope,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.Amount,
			&i.AccountID,
			&i.Month,
			&i.AlertAtPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetsByUser = `-- name: ListBudgetsByUser :many
SELECT
    b.id,
    b.user_id,
    b.name,
    b.scope,
    b.category_id,
    c.name AS category_name,
    c.icon AS category_icon,
    b.subcategory_id,
    s.name AS subcategory_name,
    b.amount,
    b.period,
    b.account_id,
    a.name AS account_name,
    b.month,
    b.copy_forward,
    b.rollover,
    b.alert_at_percent,
    b.is_active,
    b.created_at,
    b.updated_at
FROM budgets b
LEFT JOIN categories c ON c.id = b.category_id
LEFT JOIN subcategories s ON s.id = b.subcategory_id
LEFT JOIN accounts a ON a.id = b.account_id
WHERE b.user_id = ?
  AND (? = '' OR b.month = ?)
ORDER BY b.created_at DESC
`

type ListBudgetsByUserParams struct {
	UserID  string      `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Month   string      `json:"month"`
}

type ListBudgetsByUserRow struct {
	ID              string  `json:"id"`
	UserID          string  `json:"user_id"`
	Name            string  `json:"name"`
	Scope           string  `json:"scope"`
	CategoryID      *string `json:"category_id"`
	CategoryName    *string `json:"category_name"`
	CategoryIcon    *string `json:"category_icon"`
	SubcategoryID   *string `json:"subcategory_id"`
	SubcategoryName *string `json:"subcategory_name"`
	Amount          int64   `json:"amount"`
	Period          string  `json:"period"`
	AccountID       *string `json:"account_id"`
	AccountName     *string `json:"account_name"`
	Month           string  `json:"month"`
	CopyForward     int64   `json:"copy_forward"`
	Rollover        int64   `json:"rollover"`
	AlertAtPercent  int64   `json:"alert_at_percent"`
	IsActive        int64   `json:"is_active"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

func (q *Queries) ListBudgetsByUser(ctx context.Context, arg ListBudgetsByUserParams) ([]ListBudgetsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listBudgetsByUser, arg.UserID, arg.Column2, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetsByUserRow{}
	for rows.Next() {
		var i ListBudgetsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Scope,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.SubcategoryID,
			&i.SubcategoryName,
			&i.Amount,
			&i.Period,
			&i.AccountID,
			&i.AccountName,
			&i.Month,
			&i.CopyForward,
			&i.Rollover,
			&i.AlertAtPercent,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudget = `-- name: UpdateBudget :execrows
UPDATE budgets
SET name = ?, scope = ?,
    category_id = ?, subcategory_id = ?, amount = ?,
    account_id = ?, copy_forward = ?, alert_at_percent = ?, is_active = ?,
    updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateBudgetParams struct {
	Name           string  `json:"name"`
	Scope          string  `json:"scope"`
	CategoryID     *string `json:"category_id"`
	SubcategoryID  *string `json:"subcategory_id"`
	Amount         int64   `json:"amount"`
	AccountID      *string `json:"account_id"`
	CopyForward    int64   `json:"copy_forward"`
	AlertAtPercent int64   `json:"alert_at_percent"`
	IsActive       int64   `json:"is_active"`
	UpdatedAt      string  `json:"updated_at"`
	ID             string  `json:"id"`
	UserID         string  `json:"user_id"`
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateBudget,
		arg.Name,
		arg.Scope,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.Amount,
		arg.AccountID,
		arg.CopyForward,
		arg.AlertAtPercent,
		arg.IsActive,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateBudgetPeriodPlannedAmount = `-- name: UpdateBudgetPeriodPlannedAmount :execrows
UPDATE budget_periods
SET planned_amount = ?, updated_at = ?
WHERE budget_id = ? AND period_start = ?
`

type UpdateBudgetPeriodPlannedAmountParams struct {
	PlannedAmount int64  `json:"planned_amount"`
	UpdatedAt     string `json:"updated_at"`
	BudgetID      string `json:"budget_id"`
	PeriodStart   string `json:"period_start"`
}

func (q *Queries) UpdateBudgetPeriodPlannedAmount(ctx context.Context, arg UpdateBudgetPeriodPlannedAmountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateBudgetPeriodPlannedAmount,
		arg.PlannedAmount,
		arg.UpdatedAt,
		arg.BudgetID,
		arg.PeriodStart,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
