// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlc

import (
	"context"
)

const clearPrimaryCategories = `-- name: ClearPrimaryCategories :exec
UPDATE categories
SET is_primary = 0
WHERE user_id = ? AND type = ?
`

type ClearPrimaryCategoriesParams struct {
	UserID string `json:"user_id"`
	Type   string `json:"type"`
}

func (q *Queries) ClearPrimaryCategories(ctx context.Context, arg ClearPrimaryCategoriesParams) error {
	_, err := q.db.ExecContext(ctx, clearPrimaryCategories, arg.UserID, arg.Type)
	return err
}

const countCategoriesByName = `-- name: CountCategoriesByName :one
SELECT COUNT(*) AS count
FROM categories
WHERE user_id = ? AND name = ? AND type = ?
`

type CountCategoriesByNameParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
	Type   string `json:"type"`
}

func (q *Queries) CountCategoriesByName(ctx context.Context, arg CountCategoriesByNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategoriesByName, arg.UserID, arg.Name, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCategoriesByNameExcluding = `-- name: CountCategoriesByNameExcluding :one
SELECT COUNT(*) AS count
FROM categories
WHERE user_id = ? AND name = ? AND type = ? AND id != ?
`

type CountCategoriesByNameExcludingParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
	Type   string `json:"type"`
	ID     string `json:"id"`
}

func (q *Queries) CountCategoriesByNameExcluding(ctx context.Context, arg CountCategoriesByNameExcludingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategoriesByNameExcluding,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.ID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCategoriesByType = `-- name: CountCategoriesByType :one
SELECT COUNT(*) AS count
FROM categories
WHERE user_id = ? AND type = ?
`

type CountCategoriesByTypeParams struct {
	UserID string `json:"user_id"`
	Type   string `json:"type"`
}

func (q *Queries) CountCategoriesByType(ctx context.Context, arg CountCategoriesByTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategoriesByType, arg.UserID, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories
WHERE id = ? AND user_id = ?
`

type DeleteCategoryParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCategory, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSubcategory = `-- name: DeleteSubcategory :execrows
DELETE FROM subcategories
WHERE id = ?
`

func (q *Queries) DeleteSubcategory(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSubcategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT
    c.id,
    c.name,
    c.type,
    c.icon,
    c.sort_order,
    c.is_primary,
    c.is_system,
    c.created_at,
    (SELECT COUNT(*) FROM subcategories s WHERE s.category_id = c.id) AS sub_count
FROM categories c
WHERE c.id = ? AND c.user_id = ?
`

type GetCategoryByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type GetCategoryByIDRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	Icon      string `json:"icon"`
	SortOrder int64  `json:"sort_order"`
	IsPrimary int64  `json:"is_primary"`
	IsSystem  int64  `json:"is_system"`
	CreatedAt string `json:"created_at"`
	SubCount  int64  `json:"sub_count"`
}

func (q *Queries) GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (GetCategoryByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, arg.ID, arg.UserID)
	var i GetCategoryByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.SortOrder,
		&i.IsPrimary,
		&i.IsSystem,
		&i.CreatedAt,
		&i.SubCount,
	)
	return i, err
}

const getSubcategoryByID = `-- name: GetSubcategoryByID :one
SELECT s.id, s.category_id, s.name, s.icon, s.sort_order, s.created_at
FROM subcategories s
JOIN categories c ON c.id = s.category_id
WHERE s.id = ? AND c.user_id = ?
`

type GetSubcategoryByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetSubcategoryByID(ctx context.Context, arg GetSubcategoryByIDParams) (Subcategory, error) {
	row := q.db.QueryRowContext(ctx, getSubcategoryByID, arg.ID, arg.UserID)
	var i Subcategory
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Icon,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const insertCategory = `-- name: InsertCategory :exec
INSERT INTO categories (id, user_id, name, type, icon, sort_order, is_primary, is_system, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCategoryParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	Icon      string `json:"icon"`
	SortOrder int64  `json:"sort_order"`
	IsPrimary int64  `json:"is_primary"`
	IsSystem  int64  `json:"is_system"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) error {
	_, err := q.db.ExecContext(ctx, insertCategory,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Icon,
		arg.SortOrder,
		arg.IsPrimary,
		arg.IsSystem,
		arg.CreatedAt,
	)
	return err
}

const insertSubcategory = `-- name: InsertSubcategory :exec
INSERT INTO subcategories (id, category_id, name, icon, sort_order, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertSubcategoryParams struct {
	ID         string `json:"id"`
	CategoryID string `json:"category_id"`
	Name       string `json:"name"`
	Icon       string `json:"icon"`
	SortOrder  int64  `json:"sort_order"`
	CreatedAt  string `json:"created_at"`
}

func (q *Queries) InsertSubcategory(ctx context.Context, arg InsertSubcategoryParams) error {
	_, err := q.db.ExecContext(ctx, insertSubcategory,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Icon,
		arg.SortOrder,
		arg.CreatedAt,
	)
	return err
}

const listCategoriesByUser = `-- name: ListCategoriesByUser :many
SELECT
    c.id,
    c.name,
    c.type,
    c.icon,
    c.sort_order,
    c.is_primary,
    c.is_system,
    c.created_at,
    (SELECT COUNT(*) FROM subcategories s WHERE s.category_id = c.id) AS sub_count
FROM categories c
WHERE c.user_id = ?
ORDER BY c.sort_order, c.name
`

type ListCategoriesByUserRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	Icon      string `json:"icon"`
	SortOrder int64  `json:"sort_order"`
	IsPrimary int64  `json:"is_primary"`
	IsSystem  int64  `json:"is_system"`
	CreatedAt string `json:"created_at"`
	SubCount  int64  `json:"sub_count"`
}

func (q *Queries) ListCategoriesByUser(ctx context.Context, userID string) ([]ListCategoriesByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesByUserRow{}
	for rows.Next() {
		var i ListCategoriesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Icon,
			&i.SortOrder,
			&i.IsPrimary,
			&i.IsSystem,
			&i.CreatedAt,
			&i.SubCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByUserAndType = `-- name: ListCategoriesByUserAndType :many
SELECT
    c.id,
    c.name,
    c.type,
    c.icon,
    c.sort_order,
    c.is_primary,
    c.is_system,
    c.created_at,
    (SELECT COUNT(*) FROM subcategories s WHERE s.category_id = c.id) AS sub_count
FROM categories c
WHERE c.user_id = ? AND c.type = ?
ORDER BY c.sort_order, c.name
`

type ListCategoriesByUserAndTypeParams struct {
	UserID string `json:"user_id"`
	Type   string `json:"type"`
}

type ListCategoriesByUserAndTypeRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	Icon      string `json:"icon"`
	SortOrder int64  `json:"sort_order"`
	IsPrimary int64  `json:"is_primary"`
	IsSystem  int64  `json:"is_system"`
	CreatedAt string `json:"created_at"`
	SubCount  int64  `json:"sub_count"`
}

func (q *Queries) ListCategoriesByUserAndType(ctx context.Context, arg ListCategoriesByUserAndTypeParams) ([]ListCategoriesByUserAndTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByUserAndType, arg.UserID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesByUserAndTypeRow{}
	for rows.Next() {
		var i ListCategoriesByUserAndTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Icon,
			&i.SortOrder,
			&i.IsPrimary,
			&i.IsSystem,
			&i.CreatedAt,
			&i.SubCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubcategoriesByCategory = `-- name: ListSubcategoriesByCategory :many
SELECT id, category_id, name, icon, sort_order, created_at
FROM subcategories
WHERE category_id = ?
ORDER BY sort_order, name
`

func (q *Queries) ListSubcategoriesByCategory(ctx context.Context, categoryID string) ([]Subcategory, error) {
	rows, err := q.db.QueryContext(ctx, listSubcategoriesByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subcategory{}
	for rows.Next() {
		var i Subcategory
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Icon,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxCategorySortOrder = `-- name: MaxCategorySortOrder :one
SELECT COALESCE(MAX(sort_order), 0)
FROM categories
WHERE user_id = ? AND type = ?
`

type MaxCategorySortOrderParams struct {
	UserID string `json:"user_id"`
	Type   string `json:"type"`
}

func (q *Queries) MaxCategorySortOrder(ctx context.Context, arg MaxCategorySortOrderParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxCategorySortOrder, arg.UserID, arg.Type)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const maxSubcategorySortOrder = `-- name: MaxSubcategorySortOrder :one
SELECT COALESCE(MAX(sort_order), 0)
FROM subcategories
WHERE category_id = ?
`

func (q *Queries) MaxSubcategorySortOrder(ctx context.Context, categoryID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxSubcategorySortOrder, categoryID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const setCategoryPrimary = `-- name: SetCategoryPrimary :exec
UPDATE categories
SET is_primary = 1
WHERE id = ? AND user_id = ?
`

type SetCategoryPrimaryParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SetCategoryPrimary(ctx context.Context, arg SetCategoryPrimaryParams) error {
	_, err := q.db.ExecContext(ctx, setCategoryPrimary, arg.ID, arg.UserID)
	return err
}

const setCategorySystem = `-- name: SetCategorySystem :exec
UPDATE categories SET is_system = ? WHERE id = ? AND user_id = ?
`

type SetCategorySystemParams struct {
	IsSystem int64  `json:"is_system"`
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) SetCategorySystem(ctx context.Context, arg SetCategorySystemParams) error {
	_, err := q.db.ExecContext(ctx, setCategorySystem, arg.IsSystem, arg.ID, arg.UserID)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories
SET name = ?, icon = ?, sort_order = ?
WHERE id = ? AND user_id = ?
`

type UpdateCategoryParams struct {
	Name      string `json:"name"`
	Icon      string `json:"icon"`
	SortOrder int64  `json:"sort_order"`
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.Name,
		arg.Icon,
		arg.SortOrder,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateCategorySortOrder = `-- name: UpdateCategorySortOrder :exec
UPDATE categories
SET sort_order = ?
WHERE id = ? AND user_id = ?
`

type UpdateCategorySortOrderParams struct {
	SortOrder int64  `json:"sort_order"`
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) UpdateCategorySortOrder(ctx context.Context, arg UpdateCategorySortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateCategorySortOrder, arg.SortOrder, arg.ID, arg.UserID)
	return err
}

const updateSubcategory = `-- name: UpdateSubcategory :exec
UPDATE subcategories
SET name = ?, icon = ?
WHERE id = ?
`

type UpdateSubcategoryParams struct {
	Name string `json:"name"`
	Icon string `json:"icon"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateSubcategory(ctx context.Context, arg UpdateSubcategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateSubcategory, arg.Name, arg.Icon, arg.ID)
	return err
}

const updateSubcategorySortOrder = `-- name: UpdateSubcategorySortOrder :exec
UPDATE subcategories
SET sort_order = ?
WHERE id = ?
`

type UpdateSubcategorySortOrderParams struct {
	SortOrder int64  `json:"sort_order"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateSubcategorySortOrder(ctx context.Context, arg UpdateSubcategorySortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateSubcategorySortOrder, arg.SortOrder, arg.ID)
	return err
}
