// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credits.sql

package sqlc

import (
	"context"
)

const applyCreditPayment = `-- name: ApplyCreditPayment :execrows
UPDATE credit_payments
SET is_applied = 1, kind = ?, transaction_id = ?
WHERE id = ? AND credit_id = ? AND is_applied = 0
`

type ApplyCreditPaymentParams struct {
	Kind          string  `json:"kind"`
	TransactionID *string `json:"transaction_id"`
	ID            string  `json:"id"`
	CreditID      string  `json:"credit_id"`
}

func (q *Queries) ApplyCreditPayment(ctx context.Context, arg ApplyCreditPaymentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, applyCreditPayment,
		arg.Kind,
		arg.TransactionID,
		arg.ID,
		arg.CreditID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const applyScheduledPayment = `-- name: ApplyScheduledPayment :execrows
UPDATE credit_payments
SET transaction_id = ?, is_applied = 1, payment_date = ?, amount = ?
WHERE id = ? AND credit_id = ? AND kind = 'scheduled' AND is_applied = 0
`

type ApplyScheduledPaymentParams struct {
	TransactionID *string `json:"transaction_id"`
	PaymentDate   string  `json:"payment_date"`
	Amount        int64   `json:"amount"`
	ID            string  `json:"id"`
	CreditID      string  `json:"credit_id"`
}

func (q *Queries) ApplyScheduledPayment(ctx context.Context, arg ApplyScheduledPaymentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, applyScheduledPayment,
		arg.TransactionID,
		arg.PaymentDate,
		arg.Amount,
		arg.ID,
		arg.CreditID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const backdateFirstUnappliedScheduledPayment = `-- name: BackdateFirstUnappliedScheduledPayment :execrows
UPDATE credit_payments SET payment_date = datetime('now', '-1 day')
WHERE id = (
    SELECT cp2.id FROM credit_payments cp2
    WHERE cp2.credit_id = ? AND cp2.is_applied = 0 AND cp2.kind = 'scheduled' LIMIT 1
)
`

func (q *Queries) BackdateFirstUnappliedScheduledPayment(ctx context.Context, creditID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, backdateFirstUnappliedScheduledPayment, creditID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const closeCredit = `-- name: CloseCredit :execrows
UPDATE credits
SET status = 'closed', closed_at = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND status = 'active'
`

type CloseCreditParams struct {
	ClosedAt  *string `json:"closed_at"`
	UpdatedAt string  `json:"updated_at"`
	ID        string  `json:"id"`
	UserID    string  `json:"user_id"`
}

func (q *Queries) CloseCredit(ctx context.Context, arg CloseCreditParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeCredit,
		arg.ClosedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countAppliedCreditPayments = `-- name: CountAppliedCreditPayments :one
SELECT COUNT(*) FROM credit_payments
WHERE credit_id = ? AND is_applied = 1
`

func (q *Queries) CountAppliedCreditPayments(ctx context.Context, creditID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppliedCreditPayments, creditID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCreditPayments = `-- name: CountCreditPayments :one
SELECT COUNT(*) FROM credit_payments WHERE credit_id = ?
`

func (q *Queries) CountCreditPayments(ctx context.Context, creditID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCreditPayments, creditID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const creditPaymentsUnappliedByUser = `-- name: CreditPaymentsUnappliedByUser :many
SELECT cp.id, c.name AS credit_name, cp.amount, cp.payment_date
FROM credit_payments cp
JOIN credits c ON c.id = cp.credit_id
WHERE cp.is_applied = 0 AND cp.kind = 'scheduled'
  AND c.status = 'active' AND c.user_id = ?
`

type CreditPaymentsUnappliedByUserRow struct {
	ID          string  `json:"id"`
	CreditName  *string `json:"credit_name"`
	Amount      int64   `json:"amount"`
	PaymentDate string  `json:"payment_date"`
}

func (q *Queries) CreditPaymentsUnappliedByUser(ctx context.Context, userID string) ([]CreditPaymentsUnappliedByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, creditPaymentsUnappliedByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CreditPaymentsUnappliedByUserRow{}
	for rows.Next() {
		var i CreditPaymentsUnappliedByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreditName,
			&i.Amount,
			&i.PaymentDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCredit = `-- name: DeleteCredit :execrows
DELETE FROM credits WHERE id = ? AND user_id = ?
`

type DeleteCreditParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteCredit(ctx context.Context, arg DeleteCreditParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCredit, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCreditPaymentByID = `-- name: DeleteCreditPaymentByID :execrows
DELETE FROM credit_payments
WHERE id = ? AND credit_id = ?
`

type DeleteCreditPaymentByIDParams struct {
	ID       string `json:"id"`
	CreditID string `json:"credit_id"`
}

func (q *Queries) DeleteCreditPaymentByID(ctx context.Context, arg DeleteCreditPaymentByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCreditPaymentByID, arg.ID, arg.CreditID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCreditPaymentsByCredit = `-- name: DeleteCreditPaymentsByCredit :exec
DELETE FROM credit_payments WHERE credit_id = ?
`

func (q *Queries) DeleteCreditPaymentsByCredit(ctx context.Context, creditID string) error {
	_, err := q.db.ExecContext(ctx, deleteCreditPaymentsByCredit, creditID)
	return err
}

const deleteUnappliedCreditPayments = `-- name: DeleteUnappliedCreditPayments :execrows
DELETE FROM credit_payments
WHERE credit_id = ? AND is_applied = 0
`

func (q *Queries) DeleteUnappliedCreditPayments(ctx context.Context, creditID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnappliedCreditPayments, creditID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUnappliedScheduledOnDate = `-- name: DeleteUnappliedScheduledOnDate :execrows
DELETE FROM credit_payments
WHERE credit_id = ?
  AND kind = 'scheduled'
  AND is_applied = 0
  AND payment_date = ?
`

type DeleteUnappliedScheduledOnDateParams struct {
	CreditID    string `json:"credit_id"`
	PaymentDate string `json:"payment_date"`
}

func (q *Queries) DeleteUnappliedScheduledOnDate(ctx context.Context, arg DeleteUnappliedScheduledOnDateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnappliedScheduledOnDate, arg.CreditID, arg.PaymentDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCreditByID = `-- name: GetCreditByID :one
SELECT
    c.id,
    c.user_id,
    c.name,
    c.credit_kind,
    c.principal_amount,
    c.property_price,
    c.down_payment,
    c.down_payment_affects_balance,
    c.down_payment_transaction_id,
    c.issue_date,
    c.term_months,
    c.interest_rate,
    c.payment_interval,
    c.paid_amount,
    c.monthly_payment,
    c.debit_account_id,
    a.name AS debit_account_name,
    c.debit_time_local,
    c.bank_id,
    c.bank_id_locked,
    b.name AS bank_name,
    c.added_retroactively,
    c.recorded_at,
    c.status,
    c.closed_at,
    c.created_at,
    c.updated_at
FROM credits c
JOIN accounts a ON a.id = c.debit_account_id
LEFT JOIN banks b ON b.id = c.bank_id
WHERE c.id = ? AND c.user_id = ?
`

type GetCreditByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type GetCreditByIDRow struct {
	ID                        string  `json:"id"`
	UserID                    string  `json:"user_id"`
	Name                      *string `json:"name"`
	CreditKind                string  `json:"credit_kind"`
	PrincipalAmount           int64   `json:"principal_amount"`
	PropertyPrice             *int64  `json:"property_price"`
	DownPayment               int64   `json:"down_payment"`
	DownPaymentAffectsBalance int64   `json:"down_payment_affects_balance"`
	DownPaymentTransactionID  *string `json:"down_payment_transaction_id"`
	IssueDate                 string  `json:"issue_date"`
	TermMonths                int64   `json:"term_months"`
	InterestRate              float64 `json:"interest_rate"`
	PaymentInterval           string  `json:"payment_interval"`
	PaidAmount                int64   `json:"paid_amount"`
	MonthlyPayment            int64   `json:"monthly_payment"`
	DebitAccountID            string  `json:"debit_account_id"`
	DebitAccountName          string  `json:"debit_account_name"`
	DebitTimeLocal            *string `json:"debit_time_local"`
	BankID                    *string `json:"bank_id"`
	BankIDLocked              int64   `json:"bank_id_locked"`
	BankName                  *string `json:"bank_name"`
	AddedRetroactively        int64   `json:"added_retroactively"`
	RecordedAt                string  `json:"recorded_at"`
	Status                    string  `json:"status"`
	ClosedAt                  *string `json:"closed_at"`
	CreatedAt                 string  `json:"created_at"`
	UpdatedAt                 string  `json:"updated_at"`
}

func (q *Queries) GetCreditByID(ctx context.Context, arg GetCreditByIDParams) (GetCreditByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCreditByID, arg.ID, arg.UserID)
	var i GetCreditByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreditKind,
		&i.PrincipalAmount,
		&i.PropertyPrice,
		&i.DownPayment,
		&i.DownPaymentAffectsBalance,
		&i.DownPaymentTransactionID,
		&i.IssueDate,
		&i.TermMonths,
		&i.InterestRate,
		&i.PaymentInterval,
		&i.PaidAmount,
		&i.MonthlyPayment,
		&i.DebitAccountID,
		&i.DebitAccountName,
		&i.DebitTimeLocal,
		&i.BankID,
		&i.BankIDLocked,
		&i.BankName,
		&i.AddedRetroactively,
		&i.RecordedAt,
		&i.Status,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreditPaymentByID = `-- name: GetCreditPaymentByID :one
SELECT
    id, credit_id, transaction_id, amount, payment_date, kind,
    is_applied, exclude_from_stats, created_at
FROM credit_payments
WHERE id = ? AND credit_id = ?
`

type GetCreditPaymentByIDParams struct {
	ID       string `json:"id"`
	CreditID string `json:"credit_id"`
}

func (q *Queries) GetCreditPaymentByID(ctx context.Context, arg GetCreditPaymentByIDParams) (CreditPayment, error) {
	row := q.db.QueryRowContext(ctx, getCreditPaymentByID, arg.ID, arg.CreditID)
	var i CreditPayment
	err := row.Scan(
		&i.ID,
		&i.CreditID,
		&i.TransactionID,
		&i.Amount,
		&i.PaymentDate,
		&i.Kind,
		&i.IsApplied,
		&i.ExcludeFromStats,
		&i.CreatedAt,
	)
	return i, err
}

const getCreditPaymentForUser = `-- name: GetCreditPaymentForUser :one
SELECT
    cp.id,
    cp.credit_id,
    cp.transaction_id,
    cp.amount,
    cp.payment_date,
    cp.kind,
    cp.is_applied,
    c.paid_amount,
    c.status AS credit_status
FROM credit_payments cp
JOIN credits c ON c.id = cp.credit_id
WHERE cp.id = ? AND cp.credit_id = ? AND c.user_id = ?
`

type GetCreditPaymentForUserParams struct {
	ID       string `json:"id"`
	CreditID string `json:"credit_id"`
	UserID   string `json:"user_id"`
}

type GetCreditPaymentForUserRow struct {
	ID            string  `json:"id"`
	CreditID      string  `json:"credit_id"`
	TransactionID *string `json:"transaction_id"`
	Amount        int64   `json:"amount"`
	PaymentDate   string  `json:"payment_date"`
	Kind          string  `json:"kind"`
	IsApplied     int64   `json:"is_applied"`
	PaidAmount    int64   `json:"paid_amount"`
	CreditStatus  string  `json:"credit_status"`
}

func (q *Queries) GetCreditPaymentForUser(ctx context.Context, arg GetCreditPaymentForUserParams) (GetCreditPaymentForUserRow, error) {
	row := q.db.QueryRowContext(ctx, getCreditPaymentForUser, arg.ID, arg.CreditID, arg.UserID)
	var i GetCreditPaymentForUserRow
	err := row.Scan(
		&i.ID,
		&i.CreditID,
		&i.TransactionID,
		&i.Amount,
		&i.PaymentDate,
		&i.Kind,
		&i.IsApplied,
		&i.PaidAmount,
		&i.CreditStatus,
	)
	return i, err
}

const getCreditPaymentLinkByTransactionID = `-- name: GetCreditPaymentLinkByTransactionID :one
SELECT
    cp.id AS payment_id,
    cp.credit_id,
    cp.amount AS payment_amount,
    cp.kind AS payment_kind,
    cp.is_applied AS payment_is_applied,
    c.paid_amount,
    c.status AS credit_status
FROM credit_payments cp
JOIN credits c ON c.id = cp.credit_id
WHERE cp.transaction_id = ? AND c.user_id = ?
`

type GetCreditPaymentLinkByTransactionIDParams struct {
	TransactionID *string `json:"transaction_id"`
	UserID        string  `json:"user_id"`
}

type GetCreditPaymentLinkByTransactionIDRow struct {
	PaymentID        string `json:"payment_id"`
	CreditID         string `json:"credit_id"`
	PaymentAmount    int64  `json:"payment_amount"`
	PaymentKind      string `json:"payment_kind"`
	PaymentIsApplied int64  `json:"payment_is_applied"`
	PaidAmount       int64  `json:"paid_amount"`
	CreditStatus     string `json:"credit_status"`
}

func (q *Queries) GetCreditPaymentLinkByTransactionID(ctx context.Context, arg GetCreditPaymentLinkByTransactionIDParams) (GetCreditPaymentLinkByTransactionIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCreditPaymentLinkByTransactionID, arg.TransactionID, arg.UserID)
	var i GetCreditPaymentLinkByTransactionIDRow
	err := row.Scan(
		&i.PaymentID,
		&i.CreditID,
		&i.PaymentAmount,
		&i.PaymentKind,
		&i.PaymentIsApplied,
		&i.PaidAmount,
		&i.CreditStatus,
	)
	return i, err
}

const hasPaymentOnDate = `-- name: HasPaymentOnDate :one
SELECT COUNT(*) FROM credit_payments
WHERE credit_id = ?
  AND payment_date = ?
  AND is_applied = 1
  AND kind IN ('early', 'auto', 'retroactive')
`

type HasPaymentOnDateParams struct {
	CreditID    string `json:"credit_id"`
	PaymentDate string `json:"payment_date"`
}

func (q *Queries) HasPaymentOnDate(ctx context.Context, arg HasPaymentOnDateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasPaymentOnDate, arg.CreditID, arg.PaymentDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertCredit = `-- name: InsertCredit :exec
INSERT INTO credits (
    id, user_id, name, credit_kind, principal_amount, property_price, down_payment,
    down_payment_affects_balance, down_payment_transaction_id, issue_date, term_months, interest_rate,
    payment_interval, paid_amount, monthly_payment, debit_account_id,
    debit_time_local, bank_id, bank_id_locked,
    added_retroactively, recorded_at, status, closed_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCreditParams struct {
	ID                        string  `json:"id"`
	UserID                    string  `json:"user_id"`
	Name                      *string `json:"name"`
	CreditKind                string  `json:"credit_kind"`
	PrincipalAmount           int64   `json:"principal_amount"`
	PropertyPrice             *int64  `json:"property_price"`
	DownPayment               int64   `json:"down_payment"`
	DownPaymentAffectsBalance int64   `json:"down_payment_affects_balance"`
	DownPaymentTransactionID  *string `json:"down_payment_transaction_id"`
	IssueDate                 string  `json:"issue_date"`
	TermMonths                int64   `json:"term_months"`
	InterestRate              float64 `json:"interest_rate"`
	PaymentInterval           string  `json:"payment_interval"`
	PaidAmount                int64   `json:"paid_amount"`
	MonthlyPayment            int64   `json:"monthly_payment"`
	DebitAccountID            string  `json:"debit_account_id"`
	DebitTimeLocal            *string `json:"debit_time_local"`
	BankID                    *string `json:"bank_id"`
	BankIDLocked              int64   `json:"bank_id_locked"`
	AddedRetroactively        int64   `json:"added_retroactively"`
	RecordedAt                string  `json:"recorded_at"`
	Status                    string  `json:"status"`
	ClosedAt                  *string `json:"closed_at"`
	CreatedAt                 string  `json:"created_at"`
	UpdatedAt                 string  `json:"updated_at"`
}

func (q *Queries) InsertCredit(ctx context.Context, arg InsertCreditParams) error {
	_, err := q.db.ExecContext(ctx, insertCredit,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.CreditKind,
		arg.PrincipalAmount,
		arg.PropertyPrice,
		arg.DownPayment,
		arg.DownPaymentAffectsBalance,
		arg.DownPaymentTransactionID,
		arg.IssueDate,
		arg.TermMonths,
		arg.InterestRate,
		arg.PaymentInterval,
		arg.PaidAmount,
		arg.MonthlyPayment,
		arg.DebitAccountID,
		arg.DebitTimeLocal,
		arg.BankID,
		arg.BankIDLocked,
		arg.AddedRetroactively,
		arg.RecordedAt,
		arg.Status,
		arg.ClosedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertCreditPayment = `-- name: InsertCreditPayment :exec
INSERT INTO credit_payments (
    id, credit_id, transaction_id, amount, payment_date, kind,
    is_applied, exclude_from_stats, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCreditPaymentParams struct {
	ID               string  `json:"id"`
	CreditID         string  `json:"credit_id"`
	TransactionID    *string `json:"transaction_id"`
	Amount           int64   `json:"amount"`
	PaymentDate      string  `json:"payment_date"`
	Kind             string  `json:"kind"`
	IsApplied        int64   `json:"is_applied"`
	ExcludeFromStats int64   `json:"exclude_from_stats"`
	CreatedAt        string  `json:"created_at"`
}

func (q *Queries) InsertCreditPayment(ctx context.Context, arg InsertCreditPaymentParams) error {
	_, err := q.db.ExecContext(ctx, insertCreditPayment,
		arg.ID,
		arg.CreditID,
		arg.TransactionID,
		arg.Amount,
		arg.PaymentDate,
		arg.Kind,
		arg.IsApplied,
		arg.ExcludeFromStats,
		arg.CreatedAt,
	)
	return err
}

const listActiveCreditsForScheduleRepair = `-- name: ListActiveCreditsForScheduleRepair :many
SELECT id, user_id, principal_amount, issue_date, term_months, interest_rate,
       payment_interval, monthly_payment, added_retroactively
FROM credits
WHERE status = 'active' AND payment_interval != 'manual'
`

type ListActiveCreditsForScheduleRepairRow struct {
	ID                 string  `json:"id"`
	UserID             string  `json:"user_id"`
	PrincipalAmount    int64   `json:"principal_amount"`
	IssueDate          string  `json:"issue_date"`
	TermMonths         int64   `json:"term_months"`
	InterestRate       float64 `json:"interest_rate"`
	PaymentInterval    string  `json:"payment_interval"`
	MonthlyPayment     int64   `json:"monthly_payment"`
	AddedRetroactively int64   `json:"added_retroactively"`
}

func (q *Queries) ListActiveCreditsForScheduleRepair(ctx context.Context) ([]ListActiveCreditsForScheduleRepairRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCreditsForScheduleRepair)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCreditsForScheduleRepairRow{}
	for rows.Next() {
		var i ListActiveCreditsForScheduleRepairRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PrincipalAmount,
			&i.IssueDate,
			&i.TermMonths,
			&i.InterestRate,
			&i.PaymentInterval,
			&i.MonthlyPayment,
			&i.AddedRetroactively,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreditPaymentTransactionIDs = `-- name: ListCreditPaymentTransactionIDs :many
SELECT transaction_id FROM credit_payments
WHERE credit_id = ? AND transaction_id IS NOT NULL
`

func (q *Queries) ListCreditPaymentTransactionIDs(ctx context.Context, creditID string) ([]*string, error) {
	rows, err := q.db.QueryContext(ctx, listCreditPaymentTransactionIDs, creditID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var transaction_id *string
		if err := rows.Scan(&transaction_id); err != nil {
			return nil, err
		}
		items = append(items, transaction_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreditPayments = `-- name: ListCreditPayments :many
SELECT
    cp.id,
    cp.credit_id,
    cp.transaction_id,
    cp.amount,
    cp.payment_date,
    cp.kind,
    cp.is_applied,
    cp.exclude_from_stats,
    cp.created_at,
    t.kind AS transaction_kind
FROM credit_payments cp
LEFT JOIN transactions t ON t.id = cp.transaction_id
WHERE cp.credit_id = ?
ORDER BY cp.payment_date ASC, cp.created_at ASC
`

type ListCreditPaymentsRow struct {
	ID               string  `json:"id"`
	CreditID         string  `json:"credit_id"`
	TransactionID    *string `json:"transaction_id"`
	Amount           int64   `json:"amount"`
	PaymentDate      string  `json:"payment_date"`
	Kind             string  `json:"kind"`
	IsApplied        int64   `json:"is_applied"`
	ExcludeFromStats int64   `json:"exclude_from_stats"`
	CreatedAt        string  `json:"created_at"`
	TransactionKind  *string `json:"transaction_kind"`
}

func (q *Queries) ListCreditPayments(ctx context.Context, creditID string) ([]ListCreditPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCreditPayments, creditID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCreditPaymentsRow{}
	for rows.Next() {
		var i ListCreditPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreditID,
			&i.TransactionID,
			&i.Amount,
			&i.PaymentDate,
			&i.Kind,
			&i.IsApplied,
			&i.ExcludeFromStats,
			&i.CreatedAt,
			&i.TransactionKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreditsByUser = `-- name: ListCreditsByUser :many
SELECT
    c.id,
    c.user_id,
    c.name,
    c.credit_kind,
    c.principal_amount,
    c.property_price,
    c.down_payment,
    c.down_payment_affects_balance,
    c.down_payment_transaction_id,
    c.issue_date,
    c.term_months,
    c.interest_rate,
    c.payment_interval,
    c.paid_amount,
    c.monthly_payment,
    c.debit_account_id,
    a.name AS debit_account_name,
    c.debit_time_local,
    c.bank_id,
    c.bank_id_locked,
    b.name AS bank_name,
    c.added_retroactively,
    c.recorded_at,
    c.status,
    c.closed_at,
    c.created_at,
    c.updated_at
FROM credits c
JOIN accounts a ON a.id = c.debit_account_id
LEFT JOIN banks b ON b.id = c.bank_id
WHERE c.user_id = ?
  AND (? = '' OR c.status = ?)
ORDER BY c.status ASC, c.issue_date DESC, c.created_at DESC
`

type ListCreditsByUserParams struct {
	UserID  string      `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Status  string      `json:"status"`
}

type ListCreditsByUserRow struct {
	ID                        string  `json:"id"`
	UserID                    string  `json:"user_id"`
	Name                      *string `json:"name"`
	CreditKind                string  `json:"credit_kind"`
	PrincipalAmount           int64   `json:"principal_amount"`
	PropertyPrice             *int64  `json:"property_price"`
	DownPayment               int64   `json:"down_payment"`
	DownPaymentAffectsBalance int64   `json:"down_payment_affects_balance"`
	DownPaymentTransactionID  *string `json:"down_payment_transaction_id"`
	IssueDate                 string  `json:"issue_date"`
	TermMonths                int64   `json:"term_months"`
	InterestRate              float64 `json:"interest_rate"`
	PaymentInterval           string  `json:"payment_interval"`
	PaidAmount                int64   `json:"paid_amount"`
	MonthlyPayment            int64   `json:"monthly_payment"`
	DebitAccountID            string  `json:"debit_account_id"`
	DebitAccountName          string  `json:"debit_account_name"`
	DebitTimeLocal            *string `json:"debit_time_local"`
	BankID                    *string `json:"bank_id"`
	BankIDLocked              int64   `json:"bank_id_locked"`
	BankName                  *string `json:"bank_name"`
	AddedRetroactively        int64   `json:"added_retroactively"`
	RecordedAt                string  `json:"recorded_at"`
	Status                    string  `json:"status"`
	ClosedAt                  *string `json:"closed_at"`
	CreatedAt                 string  `json:"created_at"`
	UpdatedAt                 string  `json:"updated_at"`
}

func (q *Queries) ListCreditsByUser(ctx context.Context, arg ListCreditsByUserParams) ([]ListCreditsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listCreditsByUser, arg.UserID, arg.Column2, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCreditsByUserRow{}
	for rows.Next() {
		var i ListCreditsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreditKind,
			&i.PrincipalAmount,
			&i.PropertyPrice,
			&i.DownPayment,
			&i.DownPaymentAffectsBalance,
			&i.DownPaymentTransactionID,
			&i.IssueDate,
			&i.TermMonths,
			&i.InterestRate,
			&i.PaymentInterval,
			&i.PaidAmount,
			&i.MonthlyPayment,
			&i.DebitAccountID,
			&i.DebitAccountName,
			&i.DebitTimeLocal,
			&i.BankID,
			&i.BankIDLocked,
			&i.BankName,
			&i.AddedRetroactively,
			&i.RecordedAt,
			&i.Status,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueCreditPayments = `-- name: ListDueCreditPayments :many
SELECT
    cp.id,
    cp.credit_id,
    cp.transaction_id,
    cp.amount,
    cp.payment_date,
    cp.kind,
    cp.is_applied,
    cp.exclude_from_stats,
    cp.created_at,
    c.user_id,
    c.name AS credit_name,
    c.debit_account_id,
    c.debit_time_local,
    c.status AS credit_status
FROM credit_payments cp
JOIN credits c ON c.id = cp.credit_id
WHERE cp.is_applied = 0
  AND cp.kind = 'scheduled'
  AND c.status = 'active'
  AND cp.payment_date <= ?
ORDER BY cp.payment_date ASC
`

type ListDueCreditPaymentsRow struct {
	ID               string  `json:"id"`
	CreditID         string  `json:"credit_id"`
	TransactionID    *string `json:"transaction_id"`
	Amount           int64   `json:"amount"`
	PaymentDate      string  `json:"payment_date"`
	Kind             string  `json:"kind"`
	IsApplied        int64   `json:"is_applied"`
	ExcludeFromStats int64   `json:"exclude_from_stats"`
	CreatedAt        string  `json:"created_at"`
	UserID           string  `json:"user_id"`
	CreditName       *string `json:"credit_name"`
	DebitAccountID   string  `json:"debit_account_id"`
	DebitTimeLocal   *string `json:"debit_time_local"`
	CreditStatus     string  `json:"credit_status"`
}

func (q *Queries) ListDueCreditPayments(ctx context.Context, paymentDate string) ([]ListDueCreditPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDueCreditPayments, paymentDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueCreditPaymentsRow{}
	for rows.Next() {
		var i ListDueCreditPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreditID,
			&i.TransactionID,
			&i.Amount,
			&i.PaymentDate,
			&i.Kind,
			&i.IsApplied,
			&i.ExcludeFromStats,
			&i.CreatedAt,
			&i.UserID,
			&i.CreditName,
			&i.DebitAccountID,
			&i.DebitTimeLocal,
			&i.CreditStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCreditPaymentApplied = `-- name: MarkCreditPaymentApplied :execrows
UPDATE credit_payments
SET is_applied = 1
WHERE id = ? AND credit_id = ? AND is_applied = 0 AND transaction_id IS NOT NULL
`

type MarkCreditPaymentAppliedParams struct {
	ID       string `json:"id"`
	CreditID string `json:"credit_id"`
}

func (q *Queries) MarkCreditPaymentApplied(ctx context.Context, arg MarkCreditPaymentAppliedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markCreditPaymentApplied, arg.ID, arg.CreditID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reopenCredit = `-- name: ReopenCredit :execrows
UPDATE credits
SET status = 'active', closed_at = NULL, updated_at = ?
WHERE id = ? AND user_id = ? AND status = 'closed'
`

type ReopenCreditParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) ReopenCredit(ctx context.Context, arg ReopenCreditParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reopenCredit, arg.UpdatedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revertCreditPaymentLink = `-- name: RevertCreditPaymentLink :execrows
UPDATE credit_payments
SET transaction_id = NULL, is_applied = 0, kind = 'scheduled'
WHERE id = ? AND credit_id = ? AND transaction_id = ? AND is_applied = 1
`

type RevertCreditPaymentLinkParams struct {
	ID            string  `json:"id"`
	CreditID      string  `json:"credit_id"`
	TransactionID *string `json:"transaction_id"`
}

func (q *Queries) RevertCreditPaymentLink(ctx context.Context, arg RevertCreditPaymentLinkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revertCreditPaymentLink, arg.ID, arg.CreditID, arg.TransactionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setCreditDownPaymentTransaction = `-- name: SetCreditDownPaymentTransaction :exec
UPDATE credits
SET down_payment_transaction_id = ?
WHERE id = ? AND user_id = ?
`

type SetCreditDownPaymentTransactionParams struct {
	DownPaymentTransactionID *string `json:"down_payment_transaction_id"`
	ID                       string  `json:"id"`
	UserID                   string  `json:"user_id"`
}

func (q *Queries) SetCreditDownPaymentTransaction(ctx context.Context, arg SetCreditDownPaymentTransactionParams) error {
	_, err := q.db.ExecContext(ctx, setCreditDownPaymentTransaction, arg.DownPaymentTransactionID, arg.ID, arg.UserID)
	return err
}

const unlinkCreditPaymentTransactions = `-- name: UnlinkCreditPaymentTransactions :exec
UPDATE credit_payments SET transaction_id = NULL WHERE credit_id = ?
`

func (q *Queries) UnlinkCreditPaymentTransactions(ctx context.Context, creditID string) error {
	_, err := q.db.ExecContext(ctx, unlinkCreditPaymentTransactions, creditID)
	return err
}

const updateCredit = `-- name: UpdateCredit :execrows
UPDATE credits
SET
    name = ?,
    monthly_payment = ?,
    debit_account_id = ?,
    debit_time_local = ?,
    bank_id = ?,
    bank_id_locked = ?,
    updated_at = ?
WHERE id = ? AND user_id = ? AND status = 'active'
`

type UpdateCreditParams struct {
	Name           *string `json:"name"`
	MonthlyPayment int64   `json:"monthly_payment"`
	DebitAccountID string  `json:"debit_account_id"`
	DebitTimeLocal *string `json:"debit_time_local"`
	BankID         *string `json:"bank_id"`
	BankIDLocked   int64   `json:"bank_id_locked"`
	UpdatedAt      string  `json:"updated_at"`
	ID             string  `json:"id"`
	UserID         string  `json:"user_id"`
}

func (q *Queries) UpdateCredit(ctx context.Context, arg UpdateCreditParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCredit,
		arg.Name,
		arg.MonthlyPayment,
		arg.DebitAccountID,
		arg.DebitTimeLocal,
		arg.BankID,
		arg.BankIDLocked,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCreditPaidAmount = `-- name: UpdateCreditPaidAmount :exec
UPDATE credits
SET paid_amount = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateCreditPaidAmountParams struct {
	PaidAmount int64  `json:"paid_amount"`
	UpdatedAt  string `json:"updated_at"`
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
}

func (q *Queries) UpdateCreditPaidAmount(ctx context.Context, arg UpdateCreditPaidAmountParams) error {
	_, err := q.db.ExecContext(ctx, updateCreditPaidAmount,
		arg.PaidAmount,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateFutureTransactionAccount = `-- name: UpdateFutureTransactionAccount :execrows
UPDATE transactions
SET account_id = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND kind = 'future'
`

type UpdateFutureTransactionAccountParams struct {
	AccountID string `json:"account_id"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) UpdateFutureTransactionAccount(ctx context.Context, arg UpdateFutureTransactionAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFutureTransactionAccount,
		arg.AccountID,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateFutureTransactionAmount = `-- name: UpdateFutureTransactionAmount :execrows
UPDATE transactions
SET amount = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND kind = 'future'
`

type UpdateFutureTransactionAmountParams struct {
	Amount    int64  `json:"amount"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) UpdateFutureTransactionAmount(ctx context.Context, arg UpdateFutureTransactionAmountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFutureTransactionAmount,
		arg.Amount,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateScheduledCreditPaymentAmount = `-- name: UpdateScheduledCreditPaymentAmount :execrows
UPDATE credit_payments
SET amount = ?
WHERE id = ? AND credit_id = ? AND is_applied = 0 AND kind = 'scheduled'
`

type UpdateScheduledCreditPaymentAmountParams struct {
	Amount   int64  `json:"amount"`
	ID       string `json:"id"`
	CreditID string `json:"credit_id"`
}

func (q *Queries) UpdateScheduledCreditPaymentAmount(ctx context.Context, arg UpdateScheduledCreditPaymentAmountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateScheduledCreditPaymentAmount, arg.Amount, arg.ID, arg.CreditID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
