// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: debts.sql

package sqlc

import (
	"context"
)

const clearDebtTransactionLink = `-- name: ClearDebtTransactionLink :exec
UPDATE debts
SET transaction_id = NULL, affects_balance = 0
WHERE transaction_id = ? AND user_id = ?
`

type ClearDebtTransactionLinkParams struct {
	TransactionID *string `json:"transaction_id"`
	UserID        string  `json:"user_id"`
}

func (q *Queries) ClearDebtTransactionLink(ctx context.Context, arg ClearDebtTransactionLinkParams) error {
	_, err := q.db.ExecContext(ctx, clearDebtTransactionLink, arg.TransactionID, arg.UserID)
	return err
}

const clearDebtTransactionLinkByDebtID = `-- name: ClearDebtTransactionLinkByDebtID :exec
UPDATE debts
SET transaction_id = NULL, affects_balance = 0
WHERE id = ? AND user_id = ?
`

type ClearDebtTransactionLinkByDebtIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) ClearDebtTransactionLinkByDebtID(ctx context.Context, arg ClearDebtTransactionLinkByDebtIDParams) error {
	_, err := q.db.ExecContext(ctx, clearDebtTransactionLinkByDebtID, arg.ID, arg.UserID)
	return err
}

const countActiveDebtsByDebtor = `-- name: CountActiveDebtsByDebtor :one
SELECT COUNT(*) FROM debts
WHERE debtor_id = ? AND user_id = ? AND is_settled = 0
`

type CountActiveDebtsByDebtorParams struct {
	DebtorID string `json:"debtor_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) CountActiveDebtsByDebtor(ctx context.Context, arg CountActiveDebtsByDebtorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveDebtsByDebtor, arg.DebtorID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveDebtsByDebtorAndDirection = `-- name: CountActiveDebtsByDebtorAndDirection :one
SELECT COUNT(*) FROM debts
WHERE debtor_id = ? AND user_id = ? AND is_settled = 0 AND direction = ?
`

type CountActiveDebtsByDebtorAndDirectionParams struct {
	DebtorID  string `json:"debtor_id"`
	UserID    string `json:"user_id"`
	Direction string `json:"direction"`
}

func (q *Queries) CountActiveDebtsByDebtorAndDirection(ctx context.Context, arg CountActiveDebtsByDebtorAndDirectionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveDebtsByDebtorAndDirection, arg.DebtorID, arg.UserID, arg.Direction)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSettleLinksByDebt = `-- name: CountSettleLinksByDebt :one
SELECT COUNT(*)
FROM debt_transactions
WHERE debt_id = ? AND role = 'settle'
`

func (q *Queries) CountSettleLinksByDebt(ctx context.Context, debtID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSettleLinksByDebt, debtID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDebt = `-- name: DeleteDebt :execrows
DELETE FROM debts WHERE id = ? AND user_id = ?
`

type DeleteDebtParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteDebt(ctx context.Context, arg DeleteDebtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDebt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDebtTransactionLink = `-- name: DeleteDebtTransactionLink :exec
DELETE FROM debt_transactions
WHERE transaction_id = ?
`

func (q *Queries) DeleteDebtTransactionLink(ctx context.Context, transactionID string) error {
	_, err := q.db.ExecContext(ctx, deleteDebtTransactionLink, transactionID)
	return err
}

const deleteDebtor = `-- name: DeleteDebtor :execrows
DELETE FROM debtors
WHERE id = ? AND user_id = ?
`

type DeleteDebtorParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteDebtor(ctx context.Context, arg DeleteDebtorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDebtor, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDebtByID = `-- name: GetDebtByID :one
SELECT
    d.id,
    d.user_id,
    d.debtor_id,
    dt.name AS debtor_name,
    d.direction,
    d.amount,
    d.affects_balance,
    d.debt_date,
    d.due_date,
    d.description,
    d.transaction_id,
    d.is_settled,
    d.settled_at,
    d.created_at,
    tx.account_id AS open_account_id,
    acc.name AS open_account_name
FROM debts d
JOIN debtors dt ON dt.id = d.debtor_id
LEFT JOIN debt_transactions dtx_open ON dtx_open.debt_id = d.id AND dtx_open.role = 'open'
LEFT JOIN transactions tx ON tx.id = COALESCE(dtx_open.transaction_id, d.transaction_id) AND tx.user_id = d.user_id
LEFT JOIN accounts acc ON acc.id = tx.account_id
WHERE d.id = ? AND d.user_id = ?
`

type GetDebtByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type GetDebtByIDRow struct {
	ID              string  `json:"id"`
	UserID          string  `json:"user_id"`
	DebtorID        string  `json:"debtor_id"`
	DebtorName      string  `json:"debtor_name"`
	Direction       string  `json:"direction"`
	Amount          int64   `json:"amount"`
	AffectsBalance  int64   `json:"affects_balance"`
	DebtDate        string  `json:"debt_date"`
	DueDate         string  `json:"due_date"`
	Description     *string `json:"description"`
	TransactionID   *string `json:"transaction_id"`
	IsSettled       int64   `json:"is_settled"`
	SettledAt       *string `json:"settled_at"`
	CreatedAt       string  `json:"created_at"`
	OpenAccountID   *string `json:"open_account_id"`
	OpenAccountName *string `json:"open_account_name"`
}

func (q *Queries) GetDebtByID(ctx context.Context, arg GetDebtByIDParams) (GetDebtByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDebtByID, arg.ID, arg.UserID)
	var i GetDebtByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DebtorID,
		&i.DebtorName,
		&i.Direction,
		&i.Amount,
		&i.AffectsBalance,
		&i.DebtDate,
		&i.DueDate,
		&i.Description,
		&i.TransactionID,
		&i.IsSettled,
		&i.SettledAt,
		&i.CreatedAt,
		&i.OpenAccountID,
		&i.OpenAccountName,
	)
	return i, err
}

const getDebtLinkByTransactionID = `-- name: GetDebtLinkByTransactionID :one
SELECT debt_id, role
FROM debt_transactions
WHERE transaction_id = ?
`

type GetDebtLinkByTransactionIDRow struct {
	DebtID string `json:"debt_id"`
	Role   string `json:"role"`
}

func (q *Queries) GetDebtLinkByTransactionID(ctx context.Context, transactionID string) (GetDebtLinkByTransactionIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDebtLinkByTransactionID, transactionID)
	var i GetDebtLinkByTransactionIDRow
	err := row.Scan(&i.DebtID, &i.Role)
	return i, err
}

const getDebtorByID = `-- name: GetDebtorByID :one
SELECT id, user_id, name, created_at
FROM debtors
WHERE id = ? AND user_id = ?
`

type GetDebtorByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetDebtorByID(ctx context.Context, arg GetDebtorByIDParams) (Debtor, error) {
	row := q.db.QueryRowContext(ctx, getDebtorByID, arg.ID, arg.UserID)
	var i Debtor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getDebtorByName = `-- name: GetDebtorByName :one
SELECT id, user_id, name, created_at
FROM debtors
WHERE user_id = ?1 AND lower(name) = lower(?2)
`

type GetDebtorByNameParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetDebtorByName(ctx context.Context, arg GetDebtorByNameParams) (Debtor, error) {
	row := q.db.QueryRowContext(ctx, getDebtorByName, arg.UserID, arg.Name)
	var i Debtor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const insertDebt = `-- name: InsertDebt :exec
INSERT INTO debts (
    id, user_id, debtor_id, direction, amount, affects_balance,
    debt_date, due_date, description, transaction_id, is_settled, settled_at, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDebtParams struct {
	ID             string  `json:"id"`
	UserID         string  `json:"user_id"`
	DebtorID       string  `json:"debtor_id"`
	Direction      string  `json:"direction"`
	Amount         int64   `json:"amount"`
	AffectsBalance int64   `json:"affects_balance"`
	DebtDate       string  `json:"debt_date"`
	DueDate        string  `json:"due_date"`
	Description    *string `json:"description"`
	TransactionID  *string `json:"transaction_id"`
	IsSettled      int64   `json:"is_settled"`
	SettledAt      *string `json:"settled_at"`
	CreatedAt      string  `json:"created_at"`
}

func (q *Queries) InsertDebt(ctx context.Context, arg InsertDebtParams) error {
	_, err := q.db.ExecContext(ctx, insertDebt,
		arg.ID,
		arg.UserID,
		arg.DebtorID,
		arg.Direction,
		arg.Amount,
		arg.AffectsBalance,
		arg.DebtDate,
		arg.DueDate,
		arg.Description,
		arg.TransactionID,
		arg.IsSettled,
		arg.SettledAt,
		arg.CreatedAt,
	)
	return err
}

const insertDebtTransactionLink = `-- name: InsertDebtTransactionLink :exec
INSERT INTO debt_transactions (debt_id, transaction_id, role)
VALUES (?, ?, ?)
`

type InsertDebtTransactionLinkParams struct {
	DebtID        string `json:"debt_id"`
	TransactionID string `json:"transaction_id"`
	Role          string `json:"role"`
}

func (q *Queries) InsertDebtTransactionLink(ctx context.Context, arg InsertDebtTransactionLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertDebtTransactionLink, arg.DebtID, arg.TransactionID, arg.Role)
	return err
}

const insertDebtor = `-- name: InsertDebtor :exec
INSERT INTO debtors (id, user_id, name, created_at)
VALUES (?, ?, ?, ?)
`

type InsertDebtorParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) InsertDebtor(ctx context.Context, arg InsertDebtorParams) error {
	_, err := q.db.ExecContext(ctx, insertDebtor,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const listActiveDebtsByUser = `-- name: ListActiveDebtsByUser :many
SELECT
    d.id,
    d.user_id,
    d.debtor_id,
    dt.name AS debtor_name,
    d.direction,
    d.amount,
    d.affects_balance,
    d.debt_date,
    d.due_date,
    d.description,
    d.transaction_id,
    d.is_settled,
    d.settled_at,
    d.created_at,
    tx.account_id AS open_account_id,
    acc.name AS open_account_name
FROM debts d
JOIN debtors dt ON dt.id = d.debtor_id
LEFT JOIN debt_transactions dtx_open ON dtx_open.debt_id = d.id AND dtx_open.role = 'open'
LEFT JOIN transactions tx ON tx.id = COALESCE(dtx_open.transaction_id, d.transaction_id) AND tx.user_id = d.user_id
LEFT JOIN accounts acc ON acc.id = tx.account_id
WHERE d.user_id = ? AND d.is_settled = 0
ORDER BY d.debt_date DESC, d.created_at DESC
`

type ListActiveDebtsByUserRow struct {
	ID              string  `json:"id"`
	UserID          string  `json:"user_id"`
	DebtorID        string  `json:"debtor_id"`
	DebtorName      string  `json:"debtor_name"`
	Direction       string  `json:"direction"`
	Amount          int64   `json:"amount"`
	AffectsBalance  int64   `json:"affects_balance"`
	DebtDate        string  `json:"debt_date"`
	DueDate         string  `json:"due_date"`
	Description     *string `json:"description"`
	TransactionID   *string `json:"transaction_id"`
	IsSettled       int64   `json:"is_settled"`
	SettledAt       *string `json:"settled_at"`
	CreatedAt       string  `json:"created_at"`
	OpenAccountID   *string `json:"open_account_id"`
	OpenAccountName *string `json:"open_account_name"`
}

func (q *Queries) ListActiveDebtsByUser(ctx context.Context, userID string) ([]ListActiveDebtsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDebtsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveDebtsByUserRow{}
	for rows.Next() {
		var i ListActiveDebtsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DebtorID,
			&i.DebtorName,
			&i.Direction,
			&i.Amount,
			&i.AffectsBalance,
			&i.DebtDate,
			&i.DueDate,
			&i.Description,
			&i.TransactionID,
			&i.IsSettled,
			&i.SettledAt,
			&i.CreatedAt,
			&i.OpenAccountID,
			&i.OpenAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveDebtsForSummary = `-- name: ListActiveDebtsForSummary :many
SELECT direction, amount, due_date
FROM debts
WHERE user_id = ? AND is_settled = 0
`

type ListActiveDebtsForSummaryRow struct {
	Direction string `json:"direction"`
	Amount    int64  `json:"amount"`
	DueDate   string `json:"due_date"`
}

func (q *Queries) ListActiveDebtsForSummary(ctx context.Context, userID string) ([]ListActiveDebtsForSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDebtsForSummary, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveDebtsForSummaryRow{}
	for rows.Next() {
		var i ListActiveDebtsForSummaryRow
		if err := rows.Scan(&i.Direction, &i.Amount, &i.DueDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDebtsByUser = `-- name: ListAllDebtsByUser :many
SELECT
    d.id,
    d.user_id,
    d.debtor_id,
    dt.name AS debtor_name,
    d.direction,
    d.amount,
    d.affects_balance,
    d.debt_date,
    d.due_date,
    d.description,
    d.transaction_id,
    d.is_settled,
    d.settled_at,
    d.created_at,
    tx.account_id AS open_account_id,
    acc.name AS open_account_name
FROM debts d
JOIN debtors dt ON dt.id = d.debtor_id
LEFT JOIN debt_transactions dtx_open ON dtx_open.debt_id = d.id AND dtx_open.role = 'open'
LEFT JOIN transactions tx ON tx.id = COALESCE(dtx_open.transaction_id, d.transaction_id) AND tx.user_id = d.user_id
LEFT JOIN accounts acc ON acc.id = tx.account_id
WHERE d.user_id = ?
ORDER BY d.is_settled ASC, d.debt_date DESC, d.created_at DESC
`

type ListAllDebtsByUserRow struct {
	ID              string  `json:"id"`
	UserID          string  `json:"user_id"`
	DebtorID        string  `json:"debtor_id"`
	DebtorName      string  `json:"debtor_name"`
	Direction       string  `json:"direction"`
	Amount          int64   `json:"amount"`
	AffectsBalance  int64   `json:"affects_balance"`
	DebtDate        string  `json:"debt_date"`
	DueDate         string  `json:"due_date"`
	Description     *string `json:"description"`
	TransactionID   *string `json:"transaction_id"`
	IsSettled       int64   `json:"is_settled"`
	SettledAt       *string `json:"settled_at"`
	CreatedAt       string  `json:"created_at"`
	OpenAccountID   *string `json:"open_account_id"`
	OpenAccountName *string `json:"open_account_name"`
}

func (q *Queries) ListAllDebtsByUser(ctx context.Context, userID string) ([]ListAllDebtsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllDebtsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllDebtsByUserRow{}
	for rows.Next() {
		var i ListAllDebtsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DebtorID,
			&i.DebtorName,
			&i.Direction,
			&i.Amount,
			&i.AffectsBalance,
			&i.DebtDate,
			&i.DueDate,
			&i.Description,
			&i.TransactionID,
			&i.IsSettled,
			&i.SettledAt,
			&i.CreatedAt,
			&i.OpenAccountID,
			&i.OpenAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebtorsByUser = `-- name: ListDebtorsByUser :many
SELECT id, user_id, name, created_at
FROM debtors
WHERE user_id = ?
ORDER BY name COLLATE NOCASE ASC
`

func (q *Queries) ListDebtorsByUser(ctx context.Context, userID string) ([]Debtor, error) {
	rows, err := q.db.QueryContext(ctx, listDebtorsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Debtor{}
	for rows.Next() {
		var i Debtor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebtsByDebtor = `-- name: ListDebtsByDebtor :many
SELECT
    d.id,
    d.user_id,
    d.debtor_id,
    dt.name AS debtor_name,
    d.direction,
    d.amount,
    d.affects_balance,
    d.debt_date,
    d.due_date,
    d.description,
    d.transaction_id,
    d.is_settled,
    d.settled_at,
    d.created_at,
    tx.account_id AS open_account_id,
    acc.name AS open_account_name
FROM debts d
JOIN debtors dt ON dt.id = d.debtor_id
LEFT JOIN debt_transactions dtx_open ON dtx_open.debt_id = d.id AND dtx_open.role = 'open'
LEFT JOIN transactions tx ON tx.id = COALESCE(dtx_open.transaction_id, d.transaction_id) AND tx.user_id = d.user_id
LEFT JOIN accounts acc ON acc.id = tx.account_id
WHERE d.user_id = ? AND d.debtor_id = ?
ORDER BY d.is_settled ASC, d.debt_date DESC, d.created_at DESC
`

type ListDebtsByDebtorParams struct {
	UserID   string `json:"user_id"`
	DebtorID string `json:"debtor_id"`
}

type ListDebtsByDebtorRow struct {
	ID              string  `json:"id"`
	UserID          string  `json:"user_id"`
	DebtorID        string  `json:"debtor_id"`
	DebtorName      string  `json:"debtor_name"`
	Direction       string  `json:"direction"`
	Amount          int64   `json:"amount"`
	AffectsBalance  int64   `json:"affects_balance"`
	DebtDate        string  `json:"debt_date"`
	DueDate         string  `json:"due_date"`
	Description     *string `json:"description"`
	TransactionID   *string `json:"transaction_id"`
	IsSettled       int64   `json:"is_settled"`
	SettledAt       *string `json:"settled_at"`
	CreatedAt       string  `json:"created_at"`
	OpenAccountID   *string `json:"open_account_id"`
	OpenAccountName *string `json:"open_account_name"`
}

func (q *Queries) ListDebtsByDebtor(ctx context.Context, arg ListDebtsByDebtorParams) ([]ListDebtsByDebtorRow, error) {
	rows, err := q.db.QueryContext(ctx, listDebtsByDebtor, arg.UserID, arg.DebtorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDebtsByDebtorRow{}
	for rows.Next() {
		var i ListDebtsByDebtorRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DebtorID,
			&i.DebtorName,
			&i.Direction,
			&i.Amount,
			&i.AffectsBalance,
			&i.DebtDate,
			&i.DueDate,
			&i.Description,
			&i.TransactionID,
			&i.IsSettled,
			&i.SettledAt,
			&i.CreatedAt,
			&i.OpenAccountID,
			&i.OpenAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettledDebtsByUser = `-- name: ListSettledDebtsByUser :many
SELECT
    d.id,
    d.user_id,
    d.debtor_id,
    dt.name AS debtor_name,
    d.direction,
    d.amount,
    d.affects_balance,
    d.debt_date,
    d.due_date,
    d.description,
    d.transaction_id,
    d.is_settled,
    d.settled_at,
    d.created_at,
    tx.account_id AS open_account_id,
    acc.name AS open_account_name
FROM debts d
JOIN debtors dt ON dt.id = d.debtor_id
LEFT JOIN debt_transactions dtx_open ON dtx_open.debt_id = d.id AND dtx_open.role = 'open'
LEFT JOIN transactions tx ON tx.id = COALESCE(dtx_open.transaction_id, d.transaction_id) AND tx.user_id = d.user_id
LEFT JOIN accounts acc ON acc.id = tx.account_id
WHERE d.user_id = ? AND d.is_settled = 1
ORDER BY d.settled_at DESC, d.created_at DESC
`

type ListSettledDebtsByUserRow struct {
	ID              string  `json:"id"`
	UserID          string  `json:"user_id"`
	DebtorID        string  `json:"debtor_id"`
	DebtorName      string  `json:"debtor_name"`
	Direction       string  `json:"direction"`
	Amount          int64   `json:"amount"`
	AffectsBalance  int64   `json:"affects_balance"`
	DebtDate        string  `json:"debt_date"`
	DueDate         string  `json:"due_date"`
	Description     *string `json:"description"`
	TransactionID   *string `json:"transaction_id"`
	IsSettled       int64   `json:"is_settled"`
	SettledAt       *string `json:"settled_at"`
	CreatedAt       string  `json:"created_at"`
	OpenAccountID   *string `json:"open_account_id"`
	OpenAccountName *string `json:"open_account_name"`
}

func (q *Queries) ListSettledDebtsByUser(ctx context.Context, userID string) ([]ListSettledDebtsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listSettledDebtsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSettledDebtsByUserRow{}
	for rows.Next() {
		var i ListSettledDebtsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DebtorID,
			&i.DebtorName,
			&i.Direction,
			&i.Amount,
			&i.AffectsBalance,
			&i.DebtDate,
			&i.DueDate,
			&i.Description,
			&i.TransactionID,
			&i.IsSettled,
			&i.SettledAt,
			&i.CreatedAt,
			&i.OpenAccountID,
			&i.OpenAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionIDsByDebt = `-- name: ListTransactionIDsByDebt :many
SELECT transaction_id
FROM debt_transactions
WHERE debt_id = ?
`

func (q *Queries) ListTransactionIDsByDebt(ctx context.Context, debtID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionIDsByDebt, debtID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var transaction_id string
		if err := rows.Scan(&transaction_id); err != nil {
			return nil, err
		}
		items = append(items, transaction_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionIDsByDebtor = `-- name: ListTransactionIDsByDebtor :many
SELECT DISTINCT dtx.transaction_id
FROM debt_transactions dtx
INNER JOIN debts d ON d.id = dtx.debt_id
INNER JOIN transactions t ON t.id = dtx.transaction_id
WHERE d.user_id = ? AND d.debtor_id = ?
ORDER BY t.transaction_date DESC, t.created_at DESC
`

type ListTransactionIDsByDebtorParams struct {
	UserID   string `json:"user_id"`
	DebtorID string `json:"debtor_id"`
}

func (q *Queries) ListTransactionIDsByDebtor(ctx context.Context, arg ListTransactionIDsByDebtorParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionIDsByDebtor, arg.UserID, arg.DebtorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var transaction_id string
		if err := rows.Scan(&transaction_id); err != nil {
			return nil, err
		}
		items = append(items, transaction_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reduceDebtAmount = `-- name: ReduceDebtAmount :execrows
UPDATE debts
SET amount = ?
WHERE id = ? AND user_id = ? AND is_settled = 0
`

type ReduceDebtAmountParams struct {
	Amount int64  `json:"amount"`
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) ReduceDebtAmount(ctx context.Context, arg ReduceDebtAmountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reduceDebtAmount, arg.Amount, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const settleDebt = `-- name: SettleDebt :execrows
UPDATE debts
SET is_settled = 1, settled_at = ?
WHERE id = ? AND user_id = ? AND is_settled = 0
`

type SettleDebtParams struct {
	SettledAt *string `json:"settled_at"`
	ID        string  `json:"id"`
	UserID    string  `json:"user_id"`
}

func (q *Queries) SettleDebt(ctx context.Context, arg SettleDebtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, settleDebt, arg.SettledAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDebtTransactionID = `-- name: UpdateDebtTransactionID :exec
UPDATE debts SET transaction_id = ? WHERE id = ? AND user_id = ?
`

type UpdateDebtTransactionIDParams struct {
	TransactionID *string `json:"transaction_id"`
	ID            string  `json:"id"`
	UserID        string  `json:"user_id"`
}

func (q *Queries) UpdateDebtTransactionID(ctx context.Context, arg UpdateDebtTransactionIDParams) error {
	_, err := q.db.ExecContext(ctx, updateDebtTransactionID, arg.TransactionID, arg.ID, arg.UserID)
	return err
}

const updateDebtorName = `-- name: UpdateDebtorName :execrows
UPDATE debtors
SET name = ?
WHERE id = ? AND user_id = ?
`

type UpdateDebtorNameParams struct {
	Name   string `json:"name"`
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpdateDebtorName(ctx context.Context, arg UpdateDebtorNameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDebtorName, arg.Name, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
