// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feature_flags.sql

package sqlc

import (
	"context"
)

const getFeatureFlag = `-- name: GetFeatureFlag :one
SELECT key, enabled, updated_at FROM feature_flags WHERE key = ?
`

func (q *Queries) GetFeatureFlag(ctx context.Context, key string) (FeatureFlag, error) {
	row := q.db.QueryRowContext(ctx, getFeatureFlag, key)
	var i FeatureFlag
	err := row.Scan(&i.Key, &i.Enabled, &i.UpdatedAt)
	return i, err
}

const listFeatureFlags = `-- name: ListFeatureFlags :many
SELECT key, enabled, updated_at FROM feature_flags
`

func (q *Queries) ListFeatureFlags(ctx context.Context) ([]FeatureFlag, error) {
	rows, err := q.db.QueryContext(ctx, listFeatureFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeatureFlag{}
	for rows.Next() {
		var i FeatureFlag
		if err := rows.Scan(&i.Key, &i.Enabled, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeatureFlag = `-- name: UpsertFeatureFlag :exec
INSERT INTO feature_flags (key, enabled, updated_at)
VALUES (?, ?, datetime('now'))
ON CONFLICT(key) DO UPDATE SET
    enabled = excluded.enabled,
    updated_at = excluded.updated_at
`

type UpsertFeatureFlagParams struct {
	Key     string `json:"key"`
	Enabled int64  `json:"enabled"`
}

func (q *Queries) UpsertFeatureFlag(ctx context.Context, arg UpsertFeatureFlagParams) error {
	_, err := q.db.ExecContext(ctx, upsertFeatureFlag, arg.Key, arg.Enabled)
	return err
}
