// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import.sql

package sqlc

import (
	"context"
)

const getImportIdempotency = `-- name: GetImportIdempotency :one
SELECT response_json
FROM import_idempotency
WHERE user_id = ? AND idempotency_key = ?
`

type GetImportIdempotencyParams struct {
	UserID         string `json:"user_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetImportIdempotency(ctx context.Context, arg GetImportIdempotencyParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getImportIdempotency, arg.UserID, arg.IdempotencyKey)
	var response_json string
	err := row.Scan(&response_json)
	return response_json, err
}

const insertImportIdempotency = `-- name: InsertImportIdempotency :exec
INSERT INTO import_idempotency (id, user_id, idempotency_key, response_json, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertImportIdempotencyParams struct {
	ID             string `json:"id"`
	UserID         string `json:"user_id"`
	IdempotencyKey string `json:"idempotency_key"`
	ResponseJson   string `json:"response_json"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) InsertImportIdempotency(ctx context.Context, arg InsertImportIdempotencyParams) error {
	_, err := q.db.ExecContext(ctx, insertImportIdempotency,
		arg.ID,
		arg.UserID,
		arg.IdempotencyKey,
		arg.ResponseJson,
		arg.CreatedAt,
	)
	return err
}

const listTransactionDedupRows = `-- name: ListTransactionDedupRows :many
SELECT
    t.type,
    t.amount,
    substr(t.transaction_date, 1, 10) AS tx_date,
    a.name AS account_name,
    COALESCE(c.name, '') AS category_name
FROM transactions t
JOIN accounts a ON a.id = t.account_id
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.user_id = ?
  AND t.type IN ('income', 'expense', 'transfer')
  AND (t.transfer_group_id IS NULL OR t.id = (
      SELECT x.id FROM transactions x
      WHERE x.transfer_group_id = t.transfer_group_id
      ORDER BY x.created_at ASC, x.id ASC
      LIMIT 1
  ))
`

type ListTransactionDedupRowsRow struct {
	Type         string `json:"type"`
	Amount       int64  `json:"amount"`
	TxDate       string `json:"tx_date"`
	AccountName  string `json:"account_name"`
	CategoryName string `json:"category_name"`
}

func (q *Queries) ListTransactionDedupRows(ctx context.Context, userID string) ([]ListTransactionDedupRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionDedupRows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionDedupRowsRow{}
	for rows.Next() {
		var i ListTransactionDedupRowsRow
		if err := rows.Scan(
			&i.Type,
			&i.Amount,
			&i.TxDate,
			&i.AccountName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
