// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchants.sql

package sqlc

import (
	"context"
)

const deleteMerchant = `-- name: DeleteMerchant :execrows
DELETE FROM merchants
WHERE id = ? AND user_id = ?
`

type DeleteMerchantParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteMerchant(ctx context.Context, arg DeleteMerchantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMerchant, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMerchantByID = `-- name: GetMerchantByID :one
SELECT id, user_id, name, icon, created_at
FROM merchants
WHERE id = ? AND user_id = ?
`

type GetMerchantByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetMerchantByID(ctx context.Context, arg GetMerchantByIDParams) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByID, arg.ID, arg.UserID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const getMerchantByName = `-- name: GetMerchantByName :one
SELECT id, user_id, name, icon, created_at
FROM merchants
WHERE user_id = ?1 AND lower(name) = lower(?2)
`

type GetMerchantByNameParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetMerchantByName(ctx context.Context, arg GetMerchantByNameParams) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByName, arg.UserID, arg.Name)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const insertMerchant = `-- name: InsertMerchant :exec
INSERT INTO merchants (id, user_id, name, icon, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertMerchantParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Name      string `json:"name"`
	Icon      string `json:"icon"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) InsertMerchant(ctx context.Context, arg InsertMerchantParams) error {
	_, err := q.db.ExecContext(ctx, insertMerchant,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Icon,
		arg.CreatedAt,
	)
	return err
}

const listMerchantsByUser = `-- name: ListMerchantsByUser :many
SELECT id, user_id, name, icon, created_at
FROM merchants
WHERE user_id = ?
ORDER BY name COLLATE NOCASE ASC
`

func (q *Queries) ListMerchantsByUser(ctx context.Context, userID string) ([]Merchant, error) {
	rows, err := q.db.QueryContext(ctx, listMerchantsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Merchant{}
	for rows.Next() {
		var i Merchant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Icon,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMerchant = `-- name: UpdateMerchant :execrows
UPDATE merchants
SET name = ?, icon = ?
WHERE id = ? AND user_id = ?
`

type UpdateMerchantParams struct {
	Name   string `json:"name"`
	Icon   string `json:"icon"`
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMerchant,
		arg.Name,
		arg.Icon,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
