// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migrate_recovery.sql

package sqlc

import (
	"context"
)

const countSqliteTable = `-- name: CountSqliteTable :one

SELECT COUNT(*) FROM sqlite_master WHERE type = 'table' AND name = ?
`

// Migration recovery (partial 033 rebuild). See internal/db/db.go recoverInterruptedAccountRebuild.
func (q *Queries) CountSqliteTable(ctx context.Context, name *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSqliteTable, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dropAccountsNewTable = `-- name: DropAccountsNewTable :exec
DROP TABLE accounts_new
`

func (q *Queries) DropAccountsNewTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, dropAccountsNewTable)
	return err
}

const renameAccountsNewToAccounts = `-- name: RenameAccountsNewToAccounts :exec
ALTER TABLE accounts_new RENAME TO accounts
`

func (q *Queries) RenameAccountsNewToAccounts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, renameAccountsNewToAccounts)
	return err
}
