// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Account struct {
	ID               string  `json:"id"`
	UserID           string  `json:"user_id"`
	Name             string  `json:"name"`
	Type             string  `json:"type"`
	BankID           *string `json:"bank_id"`
	InitialBalance   int64   `json:"initial_balance"`
	CurrentBalance   int64   `json:"current_balance"`
	CreditLimit      *int64  `json:"credit_limit"`
	PaymentAccountID *string `json:"payment_account_id"`
	Status           string  `json:"status"`
	IsPrimary        int64   `json:"is_primary"`
	CreatedAt        string  `json:"created_at"`
	UpdatedAt        string  `json:"updated_at"`
}

type AccountsNew struct {
	ID               string  `json:"id"`
	UserID           string  `json:"user_id"`
	Name             string  `json:"name"`
	Type             string  `json:"type"`
	BankID           *string `json:"bank_id"`
	InitialBalance   int64   `json:"initial_balance"`
	CurrentBalance   int64   `json:"current_balance"`
	CreditLimit      *int64  `json:"credit_limit"`
	PaymentAccountID *string `json:"payment_account_id"`
	Status           string  `json:"status"`
	IsPrimary        int64   `json:"is_primary"`
	CreatedAt        string  `json:"created_at"`
	UpdatedAt        string  `json:"updated_at"`
}

type ApiToken struct {
	ID          string  `json:"id"`
	UserID      string  `json:"user_id"`
	Name        string  `json:"name"`
	TokenHash   string  `json:"token_hash"`
	TokenPrefix string  `json:"token_prefix"`
	ExpiresAt   *string `json:"expires_at"`
	LastUsedAt  *string `json:"last_used_at"`
	CreatedAt   string  `json:"created_at"`
}

type Bank struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Bic       *string `json:"bic"`
	IconPath  string  `json:"icon_path"`
	SortOrder int64   `json:"sort_order"`
}

type Category struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	Icon      string `json:"icon"`
	SortOrder int64  `json:"sort_order"`
	IsPrimary int64  `json:"is_primary"`
	IsSystem  int64  `json:"is_system"`
	CreatedAt string `json:"created_at"`
}

type Credit struct {
	ID                        string  `json:"id"`
	UserID                    string  `json:"user_id"`
	Name                      *string `json:"name"`
	CreditKind                string  `json:"credit_kind"`
	PrincipalAmount           int64   `json:"principal_amount"`
	PropertyPrice             *int64  `json:"property_price"`
	DownPayment               int64   `json:"down_payment"`
	DownPaymentAffectsBalance int64   `json:"down_payment_affects_balance"`
	DownPaymentTransactionID  *string `json:"down_payment_transaction_id"`
	PrincipalAffectsBalance   int64   `json:"principal_affects_balance"`
	PrincipalTransactionID    *string `json:"principal_transaction_id"`
	IssueDate                 string  `json:"issue_date"`
	TermMonths                int64   `json:"term_months"`
	InterestRate              float64 `json:"interest_rate"`
	PaymentInterval           string  `json:"payment_interval"`
	PaidAmount                int64   `json:"paid_amount"`
	MonthlyPayment            int64   `json:"monthly_payment"`
	DebitAccountID            string  `json:"debit_account_id"`
	DebitTimeLocal            *string `json:"debit_time_local"`
	BankID                    *string `json:"bank_id"`
	BankIDLocked              int64   `json:"bank_id_locked"`
	AddedRetroactively        int64   `json:"added_retroactively"`
	RecordedAt                string  `json:"recorded_at"`
	Status                    string  `json:"status"`
	ClosedAt                  *string `json:"closed_at"`
	CreatedAt                 string  `json:"created_at"`
	UpdatedAt                 string  `json:"updated_at"`
}

type CreditPayment struct {
	ID               string  `json:"id"`
	CreditID         string  `json:"credit_id"`
	TransactionID    *string `json:"transaction_id"`
	Amount           int64   `json:"amount"`
	PaymentDate      string  `json:"payment_date"`
	Kind             string  `json:"kind"`
	IsApplied        int64   `json:"is_applied"`
	ExcludeFromStats int64   `json:"exclude_from_stats"`
	CreatedAt        string  `json:"created_at"`
}

type Debt struct {
	ID             string  `json:"id"`
	UserID         string  `json:"user_id"`
	DebtorID       string  `json:"debtor_id"`
	Direction      string  `json:"direction"`
	Amount         int64   `json:"amount"`
	AffectsBalance int64   `json:"affects_balance"`
	DebtDate       string  `json:"debt_date"`
	DueDate        string  `json:"due_date"`
	Description    *string `json:"description"`
	TransactionID  *string `json:"transaction_id"`
	IsSettled      int64   `json:"is_settled"`
	SettledAt      *string `json:"settled_at"`
	CreatedAt      string  `json:"created_at"`
}

type DebtTransaction struct {
	DebtID        string `json:"debt_id"`
	TransactionID string `json:"transaction_id"`
	Role          string `json:"role"`
}

type Debtor struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

type ImportIdempotency struct {
	ID             string `json:"id"`
	UserID         string `json:"user_id"`
	IdempotencyKey string `json:"idempotency_key"`
	ResponseJson   string `json:"response_json"`
	CreatedAt      string `json:"created_at"`
}

type ImportJob struct {
	ID           string  `json:"id"`
	UserID       string  `json:"user_id"`
	Filename     string  `json:"filename"`
	Status       string  `json:"status"`
	ErrorMessage *string `json:"error_message"`
	ReportJson   *string `json:"report_json"`
	CreatedAt    string  `json:"created_at"`
	StartedAt    *string `json:"started_at"`
	FinishedAt   *string `json:"finished_at"`
	UpdatedAt    string  `json:"updated_at"`
}

type NotificationLog struct {
	ID          string  `json:"id"`
	UserID      string  `json:"user_id"`
	TriggerType string  `json:"trigger_type"`
	Channel     string  `json:"channel"`
	EntityID    *string `json:"entity_id"`
	DedupDate   *string `json:"dedup_date"`
	Status      string  `json:"status"`
	Message     *string `json:"message"`
	CreatedAt   string  `json:"created_at"`
}

type NotificationSetting struct {
	UserID                        string  `json:"user_id"`
	TelegramEnabled               int64   `json:"telegram_enabled"`
	TelegramBotToken              *string `json:"telegram_bot_token"`
	TelegramChatID                *string `json:"telegram_chat_id"`
	MaxEnabled                    int64   `json:"max_enabled"`
	MaxProvider                   *string `json:"max_provider"`
	MaxToken                      *string `json:"max_token"`
	MaxUserID                     *int64  `json:"max_user_id"`
	MaxRecipientID                *int64  `json:"max_recipient_id"`
	TriggerDebt                   int64   `json:"trigger_debt"`
	TriggerCredit                 int64   `json:"trigger_credit"`
	TriggerPlanned                int64   `json:"trigger_planned"`
	TriggerNegativeBalance        int64   `json:"trigger_negative_balance"`
	TriggerUserRegistration       int64   `json:"trigger_user_registration"`
	TriggerPasswordReset          int64   `json:"trigger_password_reset"`
	DebtDaysBefore                int64   `json:"debt_days_before"`
	MyDebtOverdueDaysLimit        int64   `json:"my_debt_overdue_days_limit"`
	OwedDebtOverdueStartAfterDays int64   `json:"owed_debt_overdue_start_after_days"`
	OwedDebtOverdueDaysLimit      int64   `json:"owed_debt_overdue_days_limit"`
	CreditDaysBefore              int64   `json:"credit_days_before"`
	NotificationTimeLocal         string  `json:"notification_time_local"`
	UpdatedAt                     string  `json:"updated_at"`
}

type NotificationTemplate struct {
	UserID      string `json:"user_id"`
	TriggerType string `json:"trigger_type"`
	Template    string `json:"template"`
	UpdatedAt   string `json:"updated_at"`
}

type PasswordResetRequest struct {
	ID          string  `json:"id"`
	UserID      string  `json:"user_id"`
	CreatedAt   string  `json:"created_at"`
	DismissedAt *string `json:"dismissed_at"`
}

type RecurringOperation struct {
	ID            string  `json:"id"`
	UserID        string  `json:"user_id"`
	Type          string  `json:"type"`
	Amount        int64   `json:"amount"`
	Description   *string `json:"description"`
	AccountID     string  `json:"account_id"`
	CategoryID    string  `json:"category_id"`
	SubcategoryID *string `json:"subcategory_id"`
	Period        string  `json:"period"`
	Weekday       *int64  `json:"weekday"`
	DayOfMonth    *int64  `json:"day_of_month"`
	StartDate     string  `json:"start_date"`
	TimeLocal     string  `json:"time_local"`
	NextRunAt     string  `json:"next_run_at"`
	LastRunAt     *string `json:"last_run_at"`
	Active        int64   `json:"active"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
}

type Session struct {
	ID           string  `json:"id"`
	UserID       string  `json:"user_id"`
	TokenHash    string  `json:"token_hash"`
	LastActivity string  `json:"last_activity"`
	ExpiresAt    string  `json:"expires_at"`
	IpAddress    *string `json:"ip_address"`
	UserAgent    *string `json:"user_agent"`
	CreatedAt    string  `json:"created_at"`
}

type SqliteMaster struct {
	Type     *string `json:"type"`
	Name     *string `json:"name"`
	TblName  *string `json:"tbl_name"`
	Rootpage *int64  `json:"rootpage"`
	Sql      *string `json:"sql"`
}

type Subcategory struct {
	ID         string `json:"id"`
	CategoryID string `json:"category_id"`
	Name       string `json:"name"`
	Icon       string `json:"icon"`
	SortOrder  int64  `json:"sort_order"`
	CreatedAt  string `json:"created_at"`
}

type SystemSetting struct {
	ID                    int64   `json:"id"`
	IsConfigured          int64   `json:"is_configured"`
	DbPath                string  `json:"db_path"`
	ExternalUrl           *string `json:"external_url"`
	NotificationSecretKey string  `json:"notification_secret_key"`
	AppVersion            string  `json:"app_version"`
	PreviousAppVersion    *string `json:"previous_app_version"`
	RegistrationEnabled   int64   `json:"registration_enabled"`
	BackupEnabled         int64   `json:"backup_enabled"`
	BackupTime            *string `json:"backup_time"`
	BackupRetention       int64   `json:"backup_retention"`
	CreatedAt             string  `json:"created_at"`
	UpdatedAt             string  `json:"updated_at"`
}

type Transaction struct {
	ID                string  `json:"id"`
	UserID            string  `json:"user_id"`
	AccountID         string  `json:"account_id"`
	Type              string  `json:"type"`
	Kind              string  `json:"kind"`
	Amount            int64   `json:"amount"`
	Description       *string `json:"description"`
	CategoryID        *string `json:"category_id"`
	SubcategoryID     *string `json:"subcategory_id"`
	TransferGroupID   *string `json:"transfer_group_id"`
	TransferAccountID *string `json:"transfer_account_id"`
	TransactionDate   string  `json:"transaction_date"`
	AffectsBalance    int64   `json:"affects_balance"`
	CreatedAt         string  `json:"created_at"`
	UpdatedAt         string  `json:"updated_at"`
}

type User struct {
	ID           string  `json:"id"`
	Login        string  `json:"login"`
	PasswordHash string  `json:"password_hash"`
	DisplayName  *string `json:"display_name"`
	IsAdmin      int64   `json:"is_admin"`
	Language     string  `json:"language"`
	Currency     string  `json:"currency"`
	Timezone     string  `json:"timezone"`
	Theme        string  `json:"theme"`
	Status       string  `json:"status"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
}
