// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"
)

const deleteNotificationTemplate = `-- name: DeleteNotificationTemplate :execrows
DELETE FROM notification_templates
WHERE user_id = ? AND trigger_type = ?
`

type DeleteNotificationTemplateParams struct {
	UserID      string `json:"user_id"`
	TriggerType string `json:"trigger_type"`
}

func (q *Queries) DeleteNotificationTemplate(ctx context.Context, arg DeleteNotificationTemplateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNotificationTemplate, arg.UserID, arg.TriggerType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteNotificationTemplatesByUser = `-- name: DeleteNotificationTemplatesByUser :execrows
DELETE FROM notification_templates
WHERE user_id = ?
`

func (q *Queries) DeleteNotificationTemplatesByUser(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNotificationTemplatesByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensureNotificationSettings = `-- name: EnsureNotificationSettings :exec
INSERT INTO notification_settings (user_id)
VALUES (?)
ON CONFLICT(user_id) DO NOTHING
`

func (q *Queries) EnsureNotificationSettings(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, ensureNotificationSettings, userID)
	return err
}

const existsNotificationDedup = `-- name: ExistsNotificationDedup :one
SELECT COUNT(*)
FROM notification_log
WHERE user_id = ?
  AND trigger_type = ?
  AND channel = ?
  AND entity_id = ?
  AND dedup_date = ?
`

type ExistsNotificationDedupParams struct {
	UserID      string  `json:"user_id"`
	TriggerType string  `json:"trigger_type"`
	Channel     string  `json:"channel"`
	EntityID    *string `json:"entity_id"`
	DedupDate   *string `json:"dedup_date"`
}

func (q *Queries) ExistsNotificationDedup(ctx context.Context, arg ExistsNotificationDedupParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsNotificationDedup,
		arg.UserID,
		arg.TriggerType,
		arg.Channel,
		arg.EntityID,
		arg.DedupDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNotificationSettings = `-- name: GetNotificationSettings :one
SELECT
    user_id,
    telegram_enabled,
    telegram_bot_token,
    telegram_chat_id,
    max_enabled,
    max_provider,
    max_token,
    max_user_id,
    max_recipient_id,
    trigger_debt,
    trigger_credit,
    trigger_planned,
    trigger_negative_balance,
    trigger_budget,
    trigger_auto_topup_disabled,
    trigger_user_registration,
    trigger_password_reset,
    debt_days_before,
    my_debt_overdue_days_limit,
    owed_debt_overdue_start_after_days,
    owed_debt_overdue_days_limit,
    credit_days_before,
    notification_time_local,
    updated_at
FROM notification_settings
WHERE user_id = ?
`

func (q *Queries) GetNotificationSettings(ctx context.Context, userID string) (NotificationSetting, error) {
	row := q.db.QueryRowContext(ctx, getNotificationSettings, userID)
	var i NotificationSetting
	err := row.Scan(
		&i.UserID,
		&i.TelegramEnabled,
		&i.TelegramBotToken,
		&i.TelegramChatID,
		&i.MaxEnabled,
		&i.MaxProvider,
		&i.MaxToken,
		&i.MaxUserID,
		&i.MaxRecipientID,
		&i.TriggerDebt,
		&i.TriggerCredit,
		&i.TriggerPlanned,
		&i.TriggerNegativeBalance,
		&i.TriggerBudget,
		&i.TriggerAutoTopupDisabled,
		&i.TriggerUserRegistration,
		&i.TriggerPasswordReset,
		&i.DebtDaysBefore,
		&i.MyDebtOverdueDaysLimit,
		&i.OwedDebtOverdueStartAfterDays,
		&i.OwedDebtOverdueDaysLimit,
		&i.CreditDaysBefore,
		&i.NotificationTimeLocal,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNotificationLog = `-- name: InsertNotificationLog :exec
INSERT INTO notification_log (
    id,
    user_id,
    trigger_type,
    channel,
    entity_id,
    dedup_date,
    status,
    message,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertNotificationLogParams struct {
	ID          string  `json:"id"`
	UserID      string  `json:"user_id"`
	TriggerType string  `json:"trigger_type"`
	Channel     string  `json:"channel"`
	EntityID    *string `json:"entity_id"`
	DedupDate   *string `json:"dedup_date"`
	Status      string  `json:"status"`
	Message     *string `json:"message"`
	CreatedAt   string  `json:"created_at"`
}

func (q *Queries) InsertNotificationLog(ctx context.Context, arg InsertNotificationLogParams) error {
	_, err := q.db.ExecContext(ctx, insertNotificationLog,
		arg.ID,
		arg.UserID,
		arg.TriggerType,
		arg.Channel,
		arg.EntityID,
		arg.DedupDate,
		arg.Status,
		arg.Message,
		arg.CreatedAt,
	)
	return err
}

const listNotificationTemplates = `-- name: ListNotificationTemplates :many
SELECT user_id, trigger_type, template, updated_at
FROM notification_templates
WHERE user_id = ?
`

func (q *Queries) ListNotificationTemplates(ctx context.Context, userID string) ([]NotificationTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationTemplates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationTemplate{}
	for rows.Next() {
		var i NotificationTemplate
		if err := rows.Scan(
			&i.UserID,
			&i.TriggerType,
			&i.Template,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNotificationSettings = `-- name: UpsertNotificationSettings :exec
INSERT INTO notification_settings (
    user_id,
    telegram_enabled,
    telegram_bot_token,
    telegram_chat_id,
    max_enabled,
    max_provider,
    max_token,
    max_user_id,
    max_recipient_id,
    trigger_debt,
    trigger_credit,
    trigger_planned,
    trigger_negative_balance,
    trigger_budget,
    trigger_auto_topup_disabled,
    trigger_user_registration,
    trigger_password_reset,
    debt_days_before,
    my_debt_overdue_days_limit,
    owed_debt_overdue_start_after_days,
    owed_debt_overdue_days_limit,
    credit_days_before,
    notification_time_local,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET
    telegram_enabled = excluded.telegram_enabled,
    telegram_bot_token = excluded.telegram_bot_token,
    telegram_chat_id = excluded.telegram_chat_id,
    max_enabled = excluded.max_enabled,
    max_provider = excluded.max_provider,
    max_token = excluded.max_token,
    max_user_id = excluded.max_user_id,
    max_recipient_id = excluded.max_recipient_id,
    trigger_debt = excluded.trigger_debt,
    trigger_credit = excluded.trigger_credit,
    trigger_planned = excluded.trigger_planned,
    trigger_negative_balance = excluded.trigger_negative_balance,
    trigger_budget = excluded.trigger_budget,
    trigger_auto_topup_disabled = excluded.trigger_auto_topup_disabled,
    trigger_user_registration = excluded.trigger_user_registration,
    trigger_password_reset = excluded.trigger_password_reset,
    debt_days_before = excluded.debt_days_before,
    my_debt_overdue_days_limit = excluded.my_debt_overdue_days_limit,
    owed_debt_overdue_start_after_days = excluded.owed_debt_overdue_start_after_days,
    owed_debt_overdue_days_limit = excluded.owed_debt_overdue_days_limit,
    credit_days_before = excluded.credit_days_before,
    notification_time_local = excluded.notification_time_local,
    updated_at = excluded.updated_at
`

type UpsertNotificationSettingsParams struct {
	UserID                        string  `json:"user_id"`
	TelegramEnabled               int64   `json:"telegram_enabled"`
	TelegramBotToken              *string `json:"telegram_bot_token"`
	TelegramChatID                *string `json:"telegram_chat_id"`
	MaxEnabled                    int64   `json:"max_enabled"`
	MaxProvider                   *string `json:"max_provider"`
	MaxToken                      *string `json:"max_token"`
	MaxUserID                     *int64  `json:"max_user_id"`
	MaxRecipientID                *int64  `json:"max_recipient_id"`
	TriggerDebt                   int64   `json:"trigger_debt"`
	TriggerCredit                 int64   `json:"trigger_credit"`
	TriggerPlanned                int64   `json:"trigger_planned"`
	TriggerNegativeBalance        int64   `json:"trigger_negative_balance"`
	TriggerBudget                 int64   `json:"trigger_budget"`
	TriggerAutoTopupDisabled      int64   `json:"trigger_auto_topup_disabled"`
	TriggerUserRegistration       int64   `json:"trigger_user_registration"`
	TriggerPasswordReset          int64   `json:"trigger_password_reset"`
	DebtDaysBefore                int64   `json:"debt_days_before"`
	MyDebtOverdueDaysLimit        int64   `json:"my_debt_overdue_days_limit"`
	OwedDebtOverdueStartAfterDays int64   `json:"owed_debt_overdue_start_after_days"`
	OwedDebtOverdueDaysLimit      int64   `json:"owed_debt_overdue_days_limit"`
	CreditDaysBefore              int64   `json:"credit_days_before"`
	NotificationTimeLocal         string  `json:"notification_time_local"`
	UpdatedAt                     string  `json:"updated_at"`
}

func (q *Queries) UpsertNotificationSettings(ctx context.Context, arg UpsertNotificationSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertNotificationSettings,
		arg.UserID,
		arg.TelegramEnabled,
		arg.TelegramBotToken,
		arg.TelegramChatID,
		arg.MaxEnabled,
		arg.MaxProvider,
		arg.MaxToken,
		arg.MaxUserID,
		arg.MaxRecipientID,
		arg.TriggerDebt,
		arg.TriggerCredit,
		arg.TriggerPlanned,
		arg.TriggerNegativeBalance,
		arg.TriggerBudget,
		arg.TriggerAutoTopupDisabled,
		arg.TriggerUserRegistration,
		arg.TriggerPasswordReset,
		arg.DebtDaysBefore,
		arg.MyDebtOverdueDaysLimit,
		arg.OwedDebtOverdueStartAfterDays,
		arg.OwedDebtOverdueDaysLimit,
		arg.CreditDaysBefore,
		arg.NotificationTimeLocal,
		arg.UpdatedAt,
	)
	return err
}

const upsertNotificationTemplate = `-- name: UpsertNotificationTemplate :exec
INSERT INTO notification_templates (user_id, trigger_type, template, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(user_id, trigger_type) DO UPDATE SET
    template = excluded.template,
    updated_at = excluded.updated_at
`

type UpsertNotificationTemplateParams struct {
	UserID      string `json:"user_id"`
	TriggerType string `json:"trigger_type"`
	Template    string `json:"template"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) UpsertNotificationTemplate(ctx context.Context, arg UpsertNotificationTemplateParams) error {
	_, err := q.db.ExecContext(ctx, upsertNotificationTemplate,
		arg.UserID,
		arg.TriggerType,
		arg.Template,
		arg.UpdatedAt,
	)
	return err
}
