// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_requests.sql

package sqlc

import (
	"context"
)

const dismissPasswordResetRequest = `-- name: DismissPasswordResetRequest :execrows
UPDATE password_reset_requests
SET dismissed_at = ?
WHERE id = ? AND dismissed_at IS NULL
`

type DismissPasswordResetRequestParams struct {
	DismissedAt *string `json:"dismissed_at"`
	ID          string  `json:"id"`
}

func (q *Queries) DismissPasswordResetRequest(ctx context.Context, arg DismissPasswordResetRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, dismissPasswordResetRequest, arg.DismissedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const dismissPasswordResetRequestsForUser = `-- name: DismissPasswordResetRequestsForUser :exec
UPDATE password_reset_requests
SET dismissed_at = ?
WHERE user_id = ? AND dismissed_at IS NULL
`

type DismissPasswordResetRequestsForUserParams struct {
	DismissedAt *string `json:"dismissed_at"`
	UserID      string  `json:"user_id"`
}

func (q *Queries) DismissPasswordResetRequestsForUser(ctx context.Context, arg DismissPasswordResetRequestsForUserParams) error {
	_, err := q.db.ExecContext(ctx, dismissPasswordResetRequestsForUser, arg.DismissedAt, arg.UserID)
	return err
}

const listPendingPasswordResetRequests = `-- name: ListPendingPasswordResetRequests :many
SELECT r.id, r.user_id, u.login, COALESCE(u.display_name, '') AS display_name, r.created_at
FROM password_reset_requests r
JOIN users u ON u.id = r.user_id
WHERE r.dismissed_at IS NULL
ORDER BY r.created_at ASC
`

type ListPendingPasswordResetRequestsRow struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	Login       string `json:"login"`
	DisplayName string `json:"display_name"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) ListPendingPasswordResetRequests(ctx context.Context) ([]ListPendingPasswordResetRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingPasswordResetRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingPasswordResetRequestsRow{}
	for rows.Next() {
		var i ListPendingPasswordResetRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Login,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPasswordResetRequest = `-- name: UpsertPasswordResetRequest :exec
INSERT INTO password_reset_requests (id, user_id, created_at, dismissed_at)
VALUES (?, ?, ?, NULL)
ON CONFLICT(user_id) DO UPDATE SET
    created_at = excluded.created_at,
    dismissed_at = NULL
`

type UpsertPasswordResetRequestParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) UpsertPasswordResetRequest(ctx context.Context, arg UpsertPasswordResetRequestParams) error {
	_, err := q.db.ExecContext(ctx, upsertPasswordResetRequest, arg.ID, arg.UserID, arg.CreatedAt)
	return err
}
