// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring_operations.sql

package sqlc

import (
	"context"
)

const deleteRecurringOperation = `-- name: DeleteRecurringOperation :execrows
DELETE FROM recurring_operations
WHERE id = ? AND user_id = ?
`

type DeleteRecurringOperationParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteRecurringOperation(ctx context.Context, arg DeleteRecurringOperationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRecurringOperation, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRecurringOperationByID = `-- name: GetRecurringOperationByID :one
SELECT
    ro.id,
    ro.user_id,
    ro.type,
    ro.amount,
    ro.description,
    ro.account_id,
    a.name AS account_name,
    ro.category_id,
    c.name AS category_name,
    ro.subcategory_id,
    s.name AS subcategory_name,
    ro.period,
    ro.weekday,
    ro.day_of_month,
    ro.start_date,
    ro.time_local,
    ro.next_run_at,
    ro.last_run_at,
    ro.active,
    ro.created_at,
    ro.updated_at
FROM recurring_operations ro
JOIN accounts a ON a.id = ro.account_id
JOIN categories c ON c.id = ro.category_id
LEFT JOIN subcategories s ON s.id = ro.subcategory_id
WHERE ro.id = ? AND ro.user_id = ?
`

type GetRecurringOperationByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type GetRecurringOperationByIDRow struct {
	ID              string  `json:"id"`
	UserID          string  `json:"user_id"`
	Type            string  `json:"type"`
	Amount          int64   `json:"amount"`
	Description     *string `json:"description"`
	AccountID       string  `json:"account_id"`
	AccountName     string  `json:"account_name"`
	CategoryID      string  `json:"category_id"`
	CategoryName    string  `json:"category_name"`
	SubcategoryID   *string `json:"subcategory_id"`
	SubcategoryName *string `json:"subcategory_name"`
	Period          string  `json:"period"`
	Weekday         *int64  `json:"weekday"`
	DayOfMonth      *int64  `json:"day_of_month"`
	StartDate       string  `json:"start_date"`
	TimeLocal       string  `json:"time_local"`
	NextRunAt       string  `json:"next_run_at"`
	LastRunAt       *string `json:"last_run_at"`
	Active          int64   `json:"active"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

func (q *Queries) GetRecurringOperationByID(ctx context.Context, arg GetRecurringOperationByIDParams) (GetRecurringOperationByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRecurringOperationByID, arg.ID, arg.UserID)
	var i GetRecurringOperationByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.AccountID,
		&i.AccountName,
		&i.CategoryID,
		&i.CategoryName,
		&i.SubcategoryID,
		&i.SubcategoryName,
		&i.Period,
		&i.Weekday,
		&i.DayOfMonth,
		&i.StartDate,
		&i.TimeLocal,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRecurringOperation = `-- name: InsertRecurringOperation :exec
INSERT INTO recurring_operations (
    id, user_id, type, amount, description,
    account_id, category_id, subcategory_id,
    period, weekday, day_of_month,
    start_date, time_local, next_run_at, last_run_at, active,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertRecurringOperationParams struct {
	ID            string  `json:"id"`
	UserID        string  `json:"user_id"`
	Type          string  `json:"type"`
	Amount        int64   `json:"amount"`
	Description   *string `json:"description"`
	AccountID     string  `json:"account_id"`
	CategoryID    string  `json:"category_id"`
	SubcategoryID *string `json:"subcategory_id"`
	Period        string  `json:"period"`
	Weekday       *int64  `json:"weekday"`
	DayOfMonth    *int64  `json:"day_of_month"`
	StartDate     string  `json:"start_date"`
	TimeLocal     string  `json:"time_local"`
	NextRunAt     string  `json:"next_run_at"`
	LastRunAt     *string `json:"last_run_at"`
	Active        int64   `json:"active"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
}

func (q *Queries) InsertRecurringOperation(ctx context.Context, arg InsertRecurringOperationParams) error {
	_, err := q.db.ExecContext(ctx, insertRecurringOperation,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Amount,
		arg.Description,
		arg.AccountID,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.Period,
		arg.Weekday,
		arg.DayOfMonth,
		arg.StartDate,
		arg.TimeLocal,
		arg.NextRunAt,
		arg.LastRunAt,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listDueRecurringOperations = `-- name: ListDueRecurringOperations :many
SELECT
    id,
    user_id,
    type,
    amount,
    description,
    account_id,
    category_id,
    subcategory_id,
    period,
    weekday,
    day_of_month,
    start_date,
    time_local,
    next_run_at,
    last_run_at,
    active,
    created_at,
    updated_at
FROM recurring_operations
WHERE user_id = ? AND active = 1 AND next_run_at <= ?
ORDER BY next_run_at ASC
`

type ListDueRecurringOperationsParams struct {
	UserID    string `json:"user_id"`
	NextRunAt string `json:"next_run_at"`
}

func (q *Queries) ListDueRecurringOperations(ctx context.Context, arg ListDueRecurringOperationsParams) ([]RecurringOperation, error) {
	rows, err := q.db.QueryContext(ctx, listDueRecurringOperations, arg.UserID, arg.NextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringOperation{}
	for rows.Next() {
		var i RecurringOperation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.AccountID,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.Period,
			&i.Weekday,
			&i.DayOfMonth,
			&i.StartDate,
			&i.TimeLocal,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringOperationsByUser = `-- name: ListRecurringOperationsByUser :many
SELECT
    ro.id,
    ro.user_id,
    ro.type,
    ro.amount,
    ro.description,
    ro.account_id,
    a.name AS account_name,
    ro.category_id,
    c.name AS category_name,
    ro.subcategory_id,
    s.name AS subcategory_name,
    ro.period,
    ro.weekday,
    ro.day_of_month,
    ro.start_date,
    ro.time_local,
    ro.next_run_at,
    ro.last_run_at,
    ro.active,
    ro.created_at,
    ro.updated_at
FROM recurring_operations ro
JOIN accounts a ON a.id = ro.account_id
JOIN categories c ON c.id = ro.category_id
LEFT JOIN subcategories s ON s.id = ro.subcategory_id
WHERE ro.user_id = ?
ORDER BY ro.created_at DESC
`

type ListRecurringOperationsByUserRow struct {
	ID              string  `json:"id"`
	UserID          string  `json:"user_id"`
	Type            string  `json:"type"`
	Amount          int64   `json:"amount"`
	Description     *string `json:"description"`
	AccountID       string  `json:"account_id"`
	AccountName     string  `json:"account_name"`
	CategoryID      string  `json:"category_id"`
	CategoryName    string  `json:"category_name"`
	SubcategoryID   *string `json:"subcategory_id"`
	SubcategoryName *string `json:"subcategory_name"`
	Period          string  `json:"period"`
	Weekday         *int64  `json:"weekday"`
	DayOfMonth      *int64  `json:"day_of_month"`
	StartDate       string  `json:"start_date"`
	TimeLocal       string  `json:"time_local"`
	NextRunAt       string  `json:"next_run_at"`
	LastRunAt       *string `json:"last_run_at"`
	Active          int64   `json:"active"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

func (q *Queries) ListRecurringOperationsByUser(ctx context.Context, userID string) ([]ListRecurringOperationsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringOperationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecurringOperationsByUserRow{}
	for rows.Next() {
		var i ListRecurringOperationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.AccountID,
			&i.AccountName,
			&i.CategoryID,
			&i.CategoryName,
			&i.SubcategoryID,
			&i.SubcategoryName,
			&i.Period,
			&i.Weekday,
			&i.DayOfMonth,
			&i.StartDate,
			&i.TimeLocal,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecurringOperationRan = `-- name: MarkRecurringOperationRan :execrows
UPDATE recurring_operations
SET next_run_at = ?, last_run_at = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type MarkRecurringOperationRanParams struct {
	NextRunAt string  `json:"next_run_at"`
	LastRunAt *string `json:"last_run_at"`
	UpdatedAt string  `json:"updated_at"`
	ID        string  `json:"id"`
	UserID    string  `json:"user_id"`
}

func (q *Queries) MarkRecurringOperationRan(ctx context.Context, arg MarkRecurringOperationRanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markRecurringOperationRan,
		arg.NextRunAt,
		arg.LastRunAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reassignRecurringOperationsCategory = `-- name: ReassignRecurringOperationsCategory :exec
UPDATE recurring_operations
SET category_id = ?, updated_at = ?
WHERE user_id = ? AND category_id = ?
`

type ReassignRecurringOperationsCategoryParams struct {
	CategoryID   string `json:"category_id"`
	UpdatedAt    string `json:"updated_at"`
	UserID       string `json:"user_id"`
	CategoryID_2 string `json:"category_id_2"`
}

func (q *Queries) ReassignRecurringOperationsCategory(ctx context.Context, arg ReassignRecurringOperationsCategoryParams) error {
	_, err := q.db.ExecContext(ctx, reassignRecurringOperationsCategory,
		arg.CategoryID,
		arg.UpdatedAt,
		arg.UserID,
		arg.CategoryID_2,
	)
	return err
}

const reassignRecurringSubcategory = `-- name: ReassignRecurringSubcategory :exec
UPDATE recurring_operations
SET subcategory_id = ?, updated_at = ?
WHERE user_id = ? AND subcategory_id = ?
`

type ReassignRecurringSubcategoryParams struct {
	SubcategoryID   *string `json:"subcategory_id"`
	UpdatedAt       string  `json:"updated_at"`
	UserID          string  `json:"user_id"`
	SubcategoryID_2 *string `json:"subcategory_id_2"`
}

func (q *Queries) ReassignRecurringSubcategory(ctx context.Context, arg ReassignRecurringSubcategoryParams) error {
	_, err := q.db.ExecContext(ctx, reassignRecurringSubcategory,
		arg.SubcategoryID,
		arg.UpdatedAt,
		arg.UserID,
		arg.SubcategoryID_2,
	)
	return err
}

const setRecurringOperationNextRunAt = `-- name: SetRecurringOperationNextRunAt :execrows
UPDATE recurring_operations SET next_run_at = ?
WHERE id = ? AND user_id = ?
`

type SetRecurringOperationNextRunAtParams struct {
	NextRunAt string `json:"next_run_at"`
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) SetRecurringOperationNextRunAt(ctx context.Context, arg SetRecurringOperationNextRunAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setRecurringOperationNextRunAt, arg.NextRunAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRecurringOperation = `-- name: UpdateRecurringOperation :execrows
UPDATE recurring_operations
SET type = ?, amount = ?, description = ?,
    account_id = ?, category_id = ?, subcategory_id = ?,
    period = ?, weekday = ?, day_of_month = ?,
    start_date = ?, time_local = ?, next_run_at = ?, active = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateRecurringOperationParams struct {
	Type          string  `json:"type"`
	Amount        int64   `json:"amount"`
	Description   *string `json:"description"`
	AccountID     string  `json:"account_id"`
	CategoryID    string  `json:"category_id"`
	SubcategoryID *string `json:"subcategory_id"`
	Period        string  `json:"period"`
	Weekday       *int64  `json:"weekday"`
	DayOfMonth    *int64  `json:"day_of_month"`
	StartDate     string  `json:"start_date"`
	TimeLocal     string  `json:"time_local"`
	NextRunAt     string  `json:"next_run_at"`
	Active        int64   `json:"active"`
	UpdatedAt     string  `json:"updated_at"`
	ID            string  `json:"id"`
	UserID        string  `json:"user_id"`
}

func (q *Queries) UpdateRecurringOperation(ctx context.Context, arg UpdateRecurringOperationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRecurringOperation,
		arg.Type,
		arg.Amount,
		arg.Description,
		arg.AccountID,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.Period,
		arg.Weekday,
		arg.DayOfMonth,
		arg.StartDate,
		arg.TimeLocal,
		arg.NextRunAt,
		arg.Active,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
