// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
)

const deleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSessionByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByID, id)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUserID, userID)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, last_activity, expires_at
FROM sessions WHERE token_hash = ?
`

type GetSessionByTokenHashRow struct {
	ID           string `json:"id"`
	UserID       string `json:"user_id"`
	LastActivity string `json:"last_activity"`
	ExpiresAt    string `json:"expires_at"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LastActivity,
		&i.ExpiresAt,
	)
	return i, err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT s.id, s.user_id, s.last_activity, s.expires_at,
       u.login, COALESCE(u.display_name, '') AS display_name, u.is_admin, u.status,
       u.language, u.currency, u.timezone, u.theme
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = ?
`

type GetSessionWithUserRow struct {
	ID           string `json:"id"`
	UserID       string `json:"user_id"`
	LastActivity string `json:"last_activity"`
	ExpiresAt    string `json:"expires_at"`
	Login        string `json:"login"`
	DisplayName  string `json:"display_name"`
	IsAdmin      int64  `json:"is_admin"`
	Status       string `json:"status"`
	Language     string `json:"language"`
	Currency     string `json:"currency"`
	Timezone     string `json:"timezone"`
	Theme        string `json:"theme"`
}

func (q *Queries) GetSessionWithUser(ctx context.Context, tokenHash string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionWithUser, tokenHash)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LastActivity,
		&i.ExpiresAt,
		&i.Login,
		&i.DisplayName,
		&i.IsAdmin,
		&i.Status,
		&i.Language,
		&i.Currency,
		&i.Timezone,
		&i.Theme,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, user_id, token_hash, last_activity, expires_at, ip_address, user_agent)
VALUES (?, ?, ?, datetime('now'), ?, ?, ?)
`

type InsertSessionParams struct {
	ID        string  `json:"id"`
	UserID    string  `json:"user_id"`
	TokenHash string  `json:"token_hash"`
	ExpiresAt string  `json:"expires_at"`
	IpAddress *string `json:"ip_address"`
	UserAgent *string `json:"user_agent"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_activity = datetime('now'), expires_at = ?
WHERE id = ?
`

type TouchSessionParams struct {
	ExpiresAt string `json:"expires_at"`
	ID        string `json:"id"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.ExpiresAt, arg.ID)
	return err
}
