// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package sqlc

import (
	"context"
)

const statsByCategory = `-- name: StatsByCategory :many
SELECT
    c.id AS category_id,
    c.name AS category_name,
    c.icon AS category_icon,
    c.type AS category_type,
    CAST(COALESCE(SUM(t.amount), 0) AS INTEGER) AS total,
    COUNT(*) AS tx_count
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id = ?
  AND t.type IN ('income', 'expense')
  AND (? = '' OR t.account_id = ?)
  AND (? = '' OR t.category_id = ?)
  AND (? = '' OR t.type = ?)
  AND (? = '' OR t.kind = ?)
  AND (? = '' OR t.transaction_date >= ?)
  AND (? = '' OR t.transaction_date <= ?)
  AND (? = '' OR t.description LIKE '%' || ? || '%')
  AND NOT EXISTS (
    SELECT 1
    FROM credit_payments cp
    WHERE cp.transaction_id = t.id
      AND cp.exclude_from_stats = 1
  )
GROUP BY c.id, c.name, c.icon, c.type
ORDER BY total DESC
`

type StatsByCategoryParams struct {
	UserID            string      `json:"user_id"`
	Column2           interface{} `json:"column_2"`
	AccountID         string      `json:"account_id"`
	Column4           interface{} `json:"column_4"`
	CategoryID        *string     `json:"category_id"`
	Column6           interface{} `json:"column_6"`
	Type              string      `json:"type"`
	Column8           interface{} `json:"column_8"`
	Kind              string      `json:"kind"`
	Column10          interface{} `json:"column_10"`
	TransactionDate   string      `json:"transaction_date"`
	Column12          interface{} `json:"column_12"`
	TransactionDate_2 string      `json:"transaction_date_2"`
	Column14          interface{} `json:"column_14"`
	Column15          *string     `json:"column_15"`
}

type StatsByCategoryRow struct {
	CategoryID   string `json:"category_id"`
	CategoryName string `json:"category_name"`
	CategoryIcon string `json:"category_icon"`
	CategoryType string `json:"category_type"`
	Total        int64  `json:"total"`
	TxCount      int64  `json:"tx_count"`
}

func (q *Queries) StatsByCategory(ctx context.Context, arg StatsByCategoryParams) ([]StatsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, statsByCategory,
		arg.UserID,
		arg.Column2,
		arg.AccountID,
		arg.Column4,
		arg.CategoryID,
		arg.Column6,
		arg.Type,
		arg.Column8,
		arg.Kind,
		arg.Column10,
		arg.TransactionDate,
		arg.Column12,
		arg.TransactionDate_2,
		arg.Column14,
		arg.Column15,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsByCategoryRow{}
	for rows.Next() {
		var i StatsByCategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryType,
			&i.Total,
			&i.TxCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsBySubcategory = `-- name: StatsBySubcategory :many
SELECT
    c.id AS category_id,
    c.name AS category_name,
    c.icon AS category_icon,
    s.id AS subcategory_id,
    s.name AS subcategory_name,
    CAST(COALESCE(SUM(t.amount), 0) AS INTEGER) AS total,
    COUNT(*) AS tx_count
FROM transactions t
JOIN categories c ON c.id = t.category_id
JOIN subcategories s ON s.id = t.subcategory_id
WHERE t.user_id = ?
  AND t.type IN ('income', 'expense')
  AND (? = '' OR t.account_id = ?)
  AND (? = '' OR t.category_id = ?)
  AND (? = '' OR t.type = ?)
  AND (? = '' OR t.kind = ?)
  AND (? = '' OR t.transaction_date >= ?)
  AND (? = '' OR t.transaction_date <= ?)
  AND (? = '' OR t.description LIKE '%' || ? || '%')
  AND NOT EXISTS (
    SELECT 1
    FROM credit_payments cp
    WHERE cp.transaction_id = t.id
      AND cp.exclude_from_stats = 1
  )
GROUP BY c.id, c.name, c.icon, s.id, s.name
ORDER BY total DESC
`

type StatsBySubcategoryParams struct {
	UserID            string      `json:"user_id"`
	Column2           interface{} `json:"column_2"`
	AccountID         string      `json:"account_id"`
	Column4           interface{} `json:"column_4"`
	CategoryID        *string     `json:"category_id"`
	Column6           interface{} `json:"column_6"`
	Type              string      `json:"type"`
	Column8           interface{} `json:"column_8"`
	Kind              string      `json:"kind"`
	Column10          interface{} `json:"column_10"`
	TransactionDate   string      `json:"transaction_date"`
	Column12          interface{} `json:"column_12"`
	TransactionDate_2 string      `json:"transaction_date_2"`
	Column14          interface{} `json:"column_14"`
	Column15          *string     `json:"column_15"`
}

type StatsBySubcategoryRow struct {
	CategoryID      string `json:"category_id"`
	CategoryName    string `json:"category_name"`
	CategoryIcon    string `json:"category_icon"`
	SubcategoryID   string `json:"subcategory_id"`
	SubcategoryName string `json:"subcategory_name"`
	Total           int64  `json:"total"`
	TxCount         int64  `json:"tx_count"`
}

func (q *Queries) StatsBySubcategory(ctx context.Context, arg StatsBySubcategoryParams) ([]StatsBySubcategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, statsBySubcategory,
		arg.UserID,
		arg.Column2,
		arg.AccountID,
		arg.Column4,
		arg.CategoryID,
		arg.Column6,
		arg.Type,
		arg.Column8,
		arg.Kind,
		arg.Column10,
		arg.TransactionDate,
		arg.Column12,
		arg.TransactionDate_2,
		arg.Column14,
		arg.Column15,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsBySubcategoryRow{}
	for rows.Next() {
		var i StatsBySubcategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.SubcategoryID,
			&i.SubcategoryName,
			&i.Total,
			&i.TxCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsContextCredit = `-- name: StatsContextCredit :one
SELECT
    CAST(COALESCE(SUM(CASE WHEN t.type = 'income' THEN t.amount ELSE 0 END), 0) AS INTEGER) AS income_total,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'expense' THEN t.amount ELSE 0 END), 0) AS INTEGER) AS expense_total,
    COUNT(DISTINCT t.id) AS transaction_count
FROM transactions t
JOIN credit_payments cp ON cp.transaction_id = t.id
JOIN credits c ON c.id = cp.credit_id
WHERE t.user_id = ?
  AND c.user_id = ?
  AND c.id = ?
  AND t.type IN ('income', 'expense')
  AND cp.exclude_from_stats = 0
  AND (? = '' OR t.kind = ?)
  AND (? = '' OR t.transaction_date >= ?)
  AND (? = '' OR t.transaction_date <= ?)
`

type StatsContextCreditParams struct {
	UserID            string      `json:"user_id"`
	UserID_2          string      `json:"user_id_2"`
	ID                string      `json:"id"`
	Column4           interface{} `json:"column_4"`
	Kind              string      `json:"kind"`
	Column6           interface{} `json:"column_6"`
	TransactionDate   string      `json:"transaction_date"`
	Column8           interface{} `json:"column_8"`
	TransactionDate_2 string      `json:"transaction_date_2"`
}

type StatsContextCreditRow struct {
	IncomeTotal      int64 `json:"income_total"`
	ExpenseTotal     int64 `json:"expense_total"`
	TransactionCount int64 `json:"transaction_count"`
}

func (q *Queries) StatsContextCredit(ctx context.Context, arg StatsContextCreditParams) (StatsContextCreditRow, error) {
	row := q.db.QueryRowContext(ctx, statsContextCredit,
		arg.UserID,
		arg.UserID_2,
		arg.ID,
		arg.Column4,
		arg.Kind,
		arg.Column6,
		arg.TransactionDate,
		arg.Column8,
		arg.TransactionDate_2,
	)
	var i StatsContextCreditRow
	err := row.Scan(&i.IncomeTotal, &i.ExpenseTotal, &i.TransactionCount)
	return i, err
}

const statsContextCreditPaid = `-- name: StatsContextCreditPaid :one
SELECT
    CAST(COALESCE(SUM(cp.amount), 0) AS INTEGER) AS paid_total,
    COUNT(*) AS payment_count
FROM credit_payments cp
JOIN credits c ON c.id = cp.credit_id
WHERE c.user_id = ?
  AND c.id = ?
  AND cp.transaction_id IS NOT NULL
  AND cp.exclude_from_stats = 0
  AND (? = '' OR cp.payment_date >= ?)
  AND (? = '' OR cp.payment_date <= ?)
`

type StatsContextCreditPaidParams struct {
	UserID        string      `json:"user_id"`
	ID            string      `json:"id"`
	Column3       interface{} `json:"column_3"`
	PaymentDate   string      `json:"payment_date"`
	Column5       interface{} `json:"column_5"`
	PaymentDate_2 string      `json:"payment_date_2"`
}

type StatsContextCreditPaidRow struct {
	PaidTotal    int64 `json:"paid_total"`
	PaymentCount int64 `json:"payment_count"`
}

func (q *Queries) StatsContextCreditPaid(ctx context.Context, arg StatsContextCreditPaidParams) (StatsContextCreditPaidRow, error) {
	row := q.db.QueryRowContext(ctx, statsContextCreditPaid,
		arg.UserID,
		arg.ID,
		arg.Column3,
		arg.PaymentDate,
		arg.Column5,
		arg.PaymentDate_2,
	)
	var i StatsContextCreditPaidRow
	err := row.Scan(&i.PaidTotal, &i.PaymentCount)
	return i, err
}

const statsContextCreditRemaining = `-- name: StatsContextCreditRemaining :one
SELECT
    principal_amount,
    paid_amount
FROM credits
WHERE id = ? AND user_id = ?
`

type StatsContextCreditRemainingParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type StatsContextCreditRemainingRow struct {
	PrincipalAmount int64 `json:"principal_amount"`
	PaidAmount      int64 `json:"paid_amount"`
}

func (q *Queries) StatsContextCreditRemaining(ctx context.Context, arg StatsContextCreditRemainingParams) (StatsContextCreditRemainingRow, error) {
	row := q.db.QueryRowContext(ctx, statsContextCreditRemaining, arg.ID, arg.UserID)
	var i StatsContextCreditRemainingRow
	err := row.Scan(&i.PrincipalAmount, &i.PaidAmount)
	return i, err
}

const statsContextDebtor = `-- name: StatsContextDebtor :one
SELECT
    CAST(COALESCE(SUM(CASE WHEN t.type = 'income' THEN t.amount ELSE 0 END), 0) AS INTEGER) AS income_total,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'expense' THEN t.amount ELSE 0 END), 0) AS INTEGER) AS expense_total,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'expense' THEN t.amount ELSE 0 END), 0) AS INTEGER) AS lent_total,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'income' THEN t.amount ELSE 0 END), 0) AS INTEGER) AS borrowed_total,
    COUNT(DISTINCT t.id) AS transaction_count
FROM transactions t
JOIN debt_transactions dtx ON dtx.transaction_id = t.id
JOIN debts d ON d.id = dtx.debt_id
WHERE t.user_id = ?
  AND d.user_id = ?
  AND d.debtor_id = ?
  AND t.type IN ('income', 'expense')
  AND (? = '' OR t.kind = ?)
  AND (? = '' OR t.transaction_date >= ?)
  AND (? = '' OR t.transaction_date <= ?)
`

type StatsContextDebtorParams struct {
	UserID            string      `json:"user_id"`
	UserID_2          string      `json:"user_id_2"`
	DebtorID          string      `json:"debtor_id"`
	Column4           interface{} `json:"column_4"`
	Kind              string      `json:"kind"`
	Column6           interface{} `json:"column_6"`
	TransactionDate   string      `json:"transaction_date"`
	Column8           interface{} `json:"column_8"`
	TransactionDate_2 string      `json:"transaction_date_2"`
}

type StatsContextDebtorRow struct {
	IncomeTotal      int64 `json:"income_total"`
	ExpenseTotal     int64 `json:"expense_total"`
	LentTotal        int64 `json:"lent_total"`
	BorrowedTotal    int64 `json:"borrowed_total"`
	TransactionCount int64 `json:"transaction_count"`
}

func (q *Queries) StatsContextDebtor(ctx context.Context, arg StatsContextDebtorParams) (StatsContextDebtorRow, error) {
	row := q.db.QueryRowContext(ctx, statsContextDebtor,
		arg.UserID,
		arg.UserID_2,
		arg.DebtorID,
		arg.Column4,
		arg.Kind,
		arg.Column6,
		arg.TransactionDate,
		arg.Column8,
		arg.TransactionDate_2,
	)
	var i StatsContextDebtorRow
	err := row.Scan(
		&i.IncomeTotal,
		&i.ExpenseTotal,
		&i.LentTotal,
		&i.BorrowedTotal,
		&i.TransactionCount,
	)
	return i, err
}

const statsContextDebts = `-- name: StatsContextDebts :one
SELECT
    CAST(COALESCE(SUM(CASE WHEN t.type = 'income' THEN t.amount ELSE 0 END), 0) AS INTEGER) AS income_total,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'expense' THEN t.amount ELSE 0 END), 0) AS INTEGER) AS expense_total,
    COUNT(DISTINCT t.id) AS transaction_count
FROM transactions t
JOIN debt_transactions dtx ON dtx.transaction_id = t.id
JOIN debts d ON d.id = dtx.debt_id
WHERE t.user_id = ?
  AND d.user_id = ?
  AND t.type IN ('income', 'expense')
  AND (? = '' OR t.kind = ?)
  AND (? = '' OR t.transaction_date >= ?)
  AND (? = '' OR t.transaction_date <= ?)
`

type StatsContextDebtsParams struct {
	UserID            string      `json:"user_id"`
	UserID_2          string      `json:"user_id_2"`
	Column3           interface{} `json:"column_3"`
	Kind              string      `json:"kind"`
	Column5           interface{} `json:"column_5"`
	TransactionDate   string      `json:"transaction_date"`
	Column7           interface{} `json:"column_7"`
	TransactionDate_2 string      `json:"transaction_date_2"`
}

type StatsContextDebtsRow struct {
	IncomeTotal      int64 `json:"income_total"`
	ExpenseTotal     int64 `json:"expense_total"`
	TransactionCount int64 `json:"transaction_count"`
}

func (q *Queries) StatsContextDebts(ctx context.Context, arg StatsContextDebtsParams) (StatsContextDebtsRow, error) {
	row := q.db.QueryRowContext(ctx, statsContextDebts,
		arg.UserID,
		arg.UserID_2,
		arg.Column3,
		arg.Kind,
		arg.Column5,
		arg.TransactionDate,
		arg.Column7,
		arg.TransactionDate_2,
	)
	var i StatsContextDebtsRow
	err := row.Scan(&i.IncomeTotal, &i.ExpenseTotal, &i.TransactionCount)
	return i, err
}

const statsPeriodRows = `-- name: StatsPeriodRows :many
SELECT
    t.transaction_date,
    t.type,
    t.amount
FROM transactions t
WHERE t.user_id = ?
  AND t.type IN ('income', 'expense')
  AND (? = '' OR t.account_id = ?)
  AND (? = '' OR t.category_id = ?)
  AND (? = '' OR t.type = ?)
  AND (? = '' OR t.kind = ?)
  AND (? = '' OR t.transaction_date >= ?)
  AND (? = '' OR t.transaction_date <= ?)
  AND (? = '' OR t.description LIKE '%' || ? || '%')
  AND NOT EXISTS (
    SELECT 1
    FROM credit_payments cp
    WHERE cp.transaction_id = t.id
      AND cp.exclude_from_stats = 1
  )
ORDER BY t.transaction_date ASC
`

type StatsPeriodRowsParams struct {
	UserID            string      `json:"user_id"`
	Column2           interface{} `json:"column_2"`
	AccountID         string      `json:"account_id"`
	Column4           interface{} `json:"column_4"`
	CategoryID        *string     `json:"category_id"`
	Column6           interface{} `json:"column_6"`
	Type              string      `json:"type"`
	Column8           interface{} `json:"column_8"`
	Kind              string      `json:"kind"`
	Column10          interface{} `json:"column_10"`
	TransactionDate   string      `json:"transaction_date"`
	Column12          interface{} `json:"column_12"`
	TransactionDate_2 string      `json:"transaction_date_2"`
	Column14          interface{} `json:"column_14"`
	Column15          *string     `json:"column_15"`
}

type StatsPeriodRowsRow struct {
	TransactionDate string `json:"transaction_date"`
	Type            string `json:"type"`
	Amount          int64  `json:"amount"`
}

func (q *Queries) StatsPeriodRows(ctx context.Context, arg StatsPeriodRowsParams) ([]StatsPeriodRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, statsPeriodRows,
		arg.UserID,
		arg.Column2,
		arg.AccountID,
		arg.Column4,
		arg.CategoryID,
		arg.Column6,
		arg.Type,
		arg.Column8,
		arg.Kind,
		arg.Column10,
		arg.TransactionDate,
		arg.Column12,
		arg.TransactionDate_2,
		arg.Column14,
		arg.Column15,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsPeriodRowsRow{}
	for rows.Next() {
		var i StatsPeriodRowsRow
		if err := rows.Scan(&i.TransactionDate, &i.Type, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsSummary = `-- name: StatsSummary :one
SELECT
    CAST(COALESCE(SUM(CASE WHEN t.type = 'income' THEN t.amount ELSE 0 END), 0) AS INTEGER) AS income_total,
    CAST(COALESCE(SUM(CASE WHEN t.type = 'expense' THEN t.amount ELSE 0 END), 0) AS INTEGER) AS expense_total,
    COUNT(*) AS transaction_count
FROM transactions t
WHERE t.user_id = ?
  AND t.type IN ('income', 'expense')
  AND (? = '' OR t.account_id = ?)
  AND (? = '' OR t.category_id = ?)
  AND (? = '' OR t.type = ?)
  AND (? = '' OR t.kind = ?)
  AND (? = '' OR t.transaction_date >= ?)
  AND (? = '' OR t.transaction_date <= ?)
  AND (? = '' OR t.description LIKE '%' || ? || '%')
  AND NOT EXISTS (
    SELECT 1
    FROM credit_payments cp
    WHERE cp.transaction_id = t.id
      AND cp.exclude_from_stats = 1
  )
`

type StatsSummaryParams struct {
	UserID            string      `json:"user_id"`
	Column2           interface{} `json:"column_2"`
	AccountID         string      `json:"account_id"`
	Column4           interface{} `json:"column_4"`
	CategoryID        *string     `json:"category_id"`
	Column6           interface{} `json:"column_6"`
	Type              string      `json:"type"`
	Column8           interface{} `json:"column_8"`
	Kind              string      `json:"kind"`
	Column10          interface{} `json:"column_10"`
	TransactionDate   string      `json:"transaction_date"`
	Column12          interface{} `json:"column_12"`
	TransactionDate_2 string      `json:"transaction_date_2"`
	Column14          interface{} `json:"column_14"`
	Column15          *string     `json:"column_15"`
}

type StatsSummaryRow struct {
	IncomeTotal      int64 `json:"income_total"`
	ExpenseTotal     int64 `json:"expense_total"`
	TransactionCount int64 `json:"transaction_count"`
}

func (q *Queries) StatsSummary(ctx context.Context, arg StatsSummaryParams) (StatsSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, statsSummary,
		arg.UserID,
		arg.Column2,
		arg.AccountID,
		arg.Column4,
		arg.CategoryID,
		arg.Column6,
		arg.Type,
		arg.Column8,
		arg.Kind,
		arg.Column10,
		arg.TransactionDate,
		arg.Column12,
		arg.TransactionDate_2,
		arg.Column14,
		arg.Column15,
	)
	var i StatsSummaryRow
	err := row.Scan(&i.IncomeTotal, &i.ExpenseTotal, &i.TransactionCount)
	return i, err
}

const statsSummaryAccount = `-- name: StatsSummaryAccount :one
SELECT
    CAST(COALESCE(SUM(
        CASE
            WHEN t.type = 'income' THEN t.amount
            WHEN t.type = 'transfer' AND t.transfer_group_id IS NOT NULL AND t.id = (
                SELECT x.id FROM transactions x
                WHERE x.transfer_group_id = t.transfer_group_id
                ORDER BY x.created_at ASC, x.id ASC
                LIMIT 1 OFFSET 1
            ) THEN t.amount
            ELSE 0
        END
    ), 0) AS INTEGER) AS income_total,
    CAST(COALESCE(SUM(
        CASE
            WHEN t.type = 'expense' THEN t.amount
            WHEN t.type = 'transfer' AND t.transfer_group_id IS NOT NULL AND t.id = (
                SELECT x.id FROM transactions x
                WHERE x.transfer_group_id = t.transfer_group_id
                ORDER BY x.created_at ASC, x.id ASC
                LIMIT 1
            ) THEN t.amount
            ELSE 0
        END
    ), 0) AS INTEGER) AS expense_total,
    COUNT(*) AS transaction_count
FROM transactions t
WHERE t.user_id = ?
  AND t.account_id = ?
  AND t.type IN ('income', 'expense', 'transfer')
  AND (? = '' OR t.category_id = ?)
  AND (? = '' OR t.type = ?)
  AND (? = '' OR t.kind = ?)
  AND (? = '' OR t.transaction_date >= ?)
  AND (? = '' OR t.transaction_date <= ?)
  AND (? = '' OR t.description LIKE '%' || ? || '%')
  AND NOT EXISTS (
    SELECT 1
    FROM credit_payments cp
    WHERE cp.transaction_id = t.id
      AND cp.exclude_from_stats = 1
  )
`

type StatsSummaryAccountParams struct {
	UserID            string      `json:"user_id"`
	AccountID         string      `json:"account_id"`
	Column3           interface{} `json:"column_3"`
	CategoryID        *string     `json:"category_id"`
	Column5           interface{} `json:"column_5"`
	Type              string      `json:"type"`
	Column7           interface{} `json:"column_7"`
	Kind              string      `json:"kind"`
	Column9           interface{} `json:"column_9"`
	TransactionDate   string      `json:"transaction_date"`
	Column11          interface{} `json:"column_11"`
	TransactionDate_2 string      `json:"transaction_date_2"`
	Column13          interface{} `json:"column_13"`
	Column14          *string     `json:"column_14"`
}

type StatsSummaryAccountRow struct {
	IncomeTotal      int64 `json:"income_total"`
	ExpenseTotal     int64 `json:"expense_total"`
	TransactionCount int64 `json:"transaction_count"`
}

// Account-scoped totals: incoming transfers count as income, outgoing as expense (matches balance).
func (q *Queries) StatsSummaryAccount(ctx context.Context, arg StatsSummaryAccountParams) (StatsSummaryAccountRow, error) {
	row := q.db.QueryRowContext(ctx, statsSummaryAccount,
		arg.UserID,
		arg.AccountID,
		arg.Column3,
		arg.CategoryID,
		arg.Column5,
		arg.Type,
		arg.Column7,
		arg.Kind,
		arg.Column9,
		arg.TransactionDate,
		arg.Column11,
		arg.TransactionDate_2,
		arg.Column13,
		arg.Column14,
	)
	var i StatsSummaryAccountRow
	err := row.Scan(&i.IncomeTotal, &i.ExpenseTotal, &i.TransactionCount)
	return i, err
}
