// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package sqlc

import (
	"context"
)

const attachTransactionToSubscription = `-- name: AttachTransactionToSubscription :execrows
UPDATE transactions
SET category_id = ?, subcategory_id = ?, subscription_id = ?, description = ?, updated_at = ?
WHERE id = ? AND user_id = ? AND type = 'expense' AND subscription_id IS NULL
`

type AttachTransactionToSubscriptionParams struct {
	CategoryID     *string `json:"category_id"`
	SubcategoryID  *string `json:"subcategory_id"`
	SubscriptionID *string `json:"subscription_id"`
	Description    *string `json:"description"`
	UpdatedAt      string  `json:"updated_at"`
	ID             string  `json:"id"`
	UserID         string  `json:"user_id"`
}

func (q *Queries) AttachTransactionToSubscription(ctx context.Context, arg AttachTransactionToSubscriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, attachTransactionToSubscription,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.SubscriptionID,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countSubscriptionsBySubcategory = `-- name: CountSubscriptionsBySubcategory :one
SELECT COUNT(*)
FROM subscriptions
WHERE user_id = ? AND subcategory_id = ?
`

type CountSubscriptionsBySubcategoryParams struct {
	UserID        string  `json:"user_id"`
	SubcategoryID *string `json:"subcategory_id"`
}

func (q *Queries) CountSubscriptionsBySubcategory(ctx context.Context, arg CountSubscriptionsBySubcategoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubscriptionsBySubcategory, arg.UserID, arg.SubcategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSubscription = `-- name: DeleteSubscription :execrows
DELETE FROM subscriptions
WHERE id = ? AND user_id = ?
`

type DeleteSubscriptionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSubscription, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSubcategoryByCategoryAndName = `-- name: GetSubcategoryByCategoryAndName :one
SELECT s.id, s.category_id, s.name, s.icon, s.sort_order, s.created_at
FROM subcategories s
JOIN categories c ON c.id = s.category_id
WHERE s.category_id = ? AND s.name = ? AND c.user_id = ?
`

type GetSubcategoryByCategoryAndNameParams struct {
	CategoryID string `json:"category_id"`
	Name       string `json:"name"`
	UserID     string `json:"user_id"`
}

func (q *Queries) GetSubcategoryByCategoryAndName(ctx context.Context, arg GetSubcategoryByCategoryAndNameParams) (Subcategory, error) {
	row := q.db.QueryRowContext(ctx, getSubcategoryByCategoryAndName, arg.CategoryID, arg.Name, arg.UserID)
	var i Subcategory
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Icon,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT
    s.id,
    s.user_id,
    s.name,
    s.description,
    s.icon,
    s.website_url,
    s.amount,
    s.account_id,
    a.name AS account_name,
    s.subcategory_id,
    sub.name AS subcategory_name,
    sub.icon AS subcategory_icon,
    s.period,
    s.weekday,
    s.day_of_month,
    s.start_date,
    s.time_local,
    s.next_run_at,
    s.upcoming_run_ats,
    s.last_run_at,
    s.active,
    s.created_at,
    s.updated_at
FROM subscriptions s
JOIN accounts a ON a.id = s.account_id
LEFT JOIN subcategories sub ON sub.id = s.subcategory_id
WHERE s.id = ? AND s.user_id = ?
`

type GetSubscriptionByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type GetSubscriptionByIDRow struct {
	ID              string  `json:"id"`
	UserID          string  `json:"user_id"`
	Name            string  `json:"name"`
	Description     *string `json:"description"`
	Icon            *string `json:"icon"`
	WebsiteUrl      *string `json:"website_url"`
	Amount          int64   `json:"amount"`
	AccountID       string  `json:"account_id"`
	AccountName     string  `json:"account_name"`
	SubcategoryID   *string `json:"subcategory_id"`
	SubcategoryName *string `json:"subcategory_name"`
	SubcategoryIcon *string `json:"subcategory_icon"`
	Period          string  `json:"period"`
	Weekday         *int64  `json:"weekday"`
	DayOfMonth      *int64  `json:"day_of_month"`
	StartDate       string  `json:"start_date"`
	TimeLocal       string  `json:"time_local"`
	NextRunAt       string  `json:"next_run_at"`
	UpcomingRunAts  string  `json:"upcoming_run_ats"`
	LastRunAt       *string `json:"last_run_at"`
	Active          int64   `json:"active"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

func (q *Queries) GetSubscriptionByID(ctx context.Context, arg GetSubscriptionByIDParams) (GetSubscriptionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByID, arg.ID, arg.UserID)
	var i GetSubscriptionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.WebsiteUrl,
		&i.Amount,
		&i.AccountID,
		&i.AccountName,
		&i.SubcategoryID,
		&i.SubcategoryName,
		&i.SubcategoryIcon,
		&i.Period,
		&i.Weekday,
		&i.DayOfMonth,
		&i.StartDate,
		&i.TimeLocal,
		&i.NextRunAt,
		&i.UpcomingRunAts,
		&i.LastRunAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSubscription = `-- name: InsertSubscription :exec
INSERT INTO subscriptions (
    id, user_id, name, description, icon, website_url,
    amount, account_id, subcategory_id,
    period, weekday, day_of_month,
    start_date, time_local, next_run_at, upcoming_run_ats, last_run_at, active,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSubscriptionParams struct {
	ID             string  `json:"id"`
	UserID         string  `json:"user_id"`
	Name           string  `json:"name"`
	Description    *string `json:"description"`
	Icon           *string `json:"icon"`
	WebsiteUrl     *string `json:"website_url"`
	Amount         int64   `json:"amount"`
	AccountID      string  `json:"account_id"`
	SubcategoryID  *string `json:"subcategory_id"`
	Period         string  `json:"period"`
	Weekday        *int64  `json:"weekday"`
	DayOfMonth     *int64  `json:"day_of_month"`
	StartDate      string  `json:"start_date"`
	TimeLocal      string  `json:"time_local"`
	NextRunAt      string  `json:"next_run_at"`
	UpcomingRunAts string  `json:"upcoming_run_ats"`
	LastRunAt      *string `json:"last_run_at"`
	Active         int64   `json:"active"`
	CreatedAt      string  `json:"created_at"`
	UpdatedAt      string  `json:"updated_at"`
}

func (q *Queries) InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, insertSubscription,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.WebsiteUrl,
		arg.Amount,
		arg.AccountID,
		arg.SubcategoryID,
		arg.Period,
		arg.Weekday,
		arg.DayOfMonth,
		arg.StartDate,
		arg.TimeLocal,
		arg.NextRunAt,
		arg.UpcomingRunAts,
		arg.LastRunAt,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listActiveSubscriptionsForForecast = `-- name: ListActiveSubscriptionsForForecast :many
SELECT
    amount,
    account_id,
    period,
    weekday,
    day_of_month,
    start_date,
    time_local,
    next_run_at,
    upcoming_run_ats
FROM subscriptions
WHERE user_id = ? AND active = 1 AND next_run_at <= ?
ORDER BY next_run_at ASC
`

type ListActiveSubscriptionsForForecastParams struct {
	UserID    string `json:"user_id"`
	NextRunAt string `json:"next_run_at"`
}

type ListActiveSubscriptionsForForecastRow struct {
	Amount         int64  `json:"amount"`
	AccountID      string `json:"account_id"`
	Period         string `json:"period"`
	Weekday        *int64 `json:"weekday"`
	DayOfMonth     *int64 `json:"day_of_month"`
	StartDate      string `json:"start_date"`
	TimeLocal      string `json:"time_local"`
	NextRunAt      string `json:"next_run_at"`
	UpcomingRunAts string `json:"upcoming_run_ats"`
}

func (q *Queries) ListActiveSubscriptionsForForecast(ctx context.Context, arg ListActiveSubscriptionsForForecastParams) ([]ListActiveSubscriptionsForForecastRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSubscriptionsForForecast, arg.UserID, arg.NextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSubscriptionsForForecastRow{}
	for rows.Next() {
		var i ListActiveSubscriptionsForForecastRow
		if err := rows.Scan(
			&i.Amount,
			&i.AccountID,
			&i.Period,
			&i.Weekday,
			&i.DayOfMonth,
			&i.StartDate,
			&i.TimeLocal,
			&i.NextRunAt,
			&i.UpcomingRunAts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSubscriptionsForNotify = `-- name: ListActiveSubscriptionsForNotify :many
SELECT
    s.id,
    s.name,
    s.description,
    s.website_url,
    s.amount,
    s.account_id,
    a.name AS account_name,
    s.next_run_at
FROM subscriptions s
JOIN accounts a ON a.id = s.account_id
WHERE s.user_id = ? AND s.active = 1
`

type ListActiveSubscriptionsForNotifyRow struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	WebsiteUrl  *string `json:"website_url"`
	Amount      int64   `json:"amount"`
	AccountID   string  `json:"account_id"`
	AccountName string  `json:"account_name"`
	NextRunAt   string  `json:"next_run_at"`
}

func (q *Queries) ListActiveSubscriptionsForNotify(ctx context.Context, userID string) ([]ListActiveSubscriptionsForNotifyRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSubscriptionsForNotify, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSubscriptionsForNotifyRow{}
	for rows.Next() {
		var i ListActiveSubscriptionsForNotifyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.WebsiteUrl,
			&i.Amount,
			&i.AccountID,
			&i.AccountName,
			&i.NextRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCandidateExpenseTransactions = `-- name: ListCandidateExpenseTransactions :many
SELECT
    t.id,
    t.user_id,
    t.account_id,
    a.name AS account_name,
    t.type,
    t.kind,
    t.amount,
    t.description,
    t.category_id,
    c.name AS category_name,
    c.is_system AS category_is_system,
    t.subcategory_id,
    s.name AS subcategory_name,
    t.transaction_date,
    t.created_at,
    t.updated_at
FROM transactions t
JOIN accounts a ON a.id = t.account_id
LEFT JOIN categories c ON c.id = t.category_id
LEFT JOIN subcategories s ON s.id = t.subcategory_id
WHERE t.user_id = ?
  AND t.type = 'expense'
  AND t.subscription_id IS NULL
  AND (?2 IS NULL OR t.account_id = ?2)
  AND (?3 IS NULL OR t.amount >= ?3)
  AND (?4 IS NULL OR t.amount <= ?4)
  AND (?5 IS NULL OR t.transaction_date >= ?5)
  AND (?6 IS NULL OR t.transaction_date <= ?6)
ORDER BY t.transaction_date DESC, t.created_at DESC
`

type ListCandidateExpenseTransactionsParams struct {
	UserID    string      `json:"user_id"`
	AccountID interface{} `json:"account_id"`
	AmountMin interface{} `json:"amount_min"`
	AmountMax interface{} `json:"amount_max"`
	DateFrom  interface{} `json:"date_from"`
	DateTo    interface{} `json:"date_to"`
}

type ListCandidateExpenseTransactionsRow struct {
	ID               string  `json:"id"`
	UserID           string  `json:"user_id"`
	AccountID        string  `json:"account_id"`
	AccountName      string  `json:"account_name"`
	Type             string  `json:"type"`
	Kind             string  `json:"kind"`
	Amount           int64   `json:"amount"`
	Description      *string `json:"description"`
	CategoryID       *string `json:"category_id"`
	CategoryName     *string `json:"category_name"`
	CategoryIsSystem *int64  `json:"category_is_system"`
	SubcategoryID    *string `json:"subcategory_id"`
	SubcategoryName  *string `json:"subcategory_name"`
	TransactionDate  string  `json:"transaction_date"`
	CreatedAt        string  `json:"created_at"`
	UpdatedAt        string  `json:"updated_at"`
}

func (q *Queries) ListCandidateExpenseTransactions(ctx context.Context, arg ListCandidateExpenseTransactionsParams) ([]ListCandidateExpenseTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCandidateExpenseTransactions,
		arg.UserID,
		arg.AccountID,
		arg.AmountMin,
		arg.AmountMax,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCandidateExpenseTransactionsRow{}
	for rows.Next() {
		var i ListCandidateExpenseTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.AccountName,
			&i.Type,
			&i.Kind,
			&i.Amount,
			&i.Description,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIsSystem,
			&i.SubcategoryID,
			&i.SubcategoryName,
			&i.TransactionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueSubscriptions = `-- name: ListDueSubscriptions :many
SELECT
    id,
    user_id,
    name,
    description,
    icon,
    website_url,
    amount,
    account_id,
    subcategory_id,
    period,
    weekday,
    day_of_month,
    start_date,
    time_local,
    next_run_at,
    upcoming_run_ats,
    last_run_at,
    active,
    created_at,
    updated_at
FROM subscriptions
WHERE user_id = ? AND active = 1 AND next_run_at <= ?
ORDER BY next_run_at ASC
`

type ListDueSubscriptionsParams struct {
	UserID    string `json:"user_id"`
	NextRunAt string `json:"next_run_at"`
}

func (q *Queries) ListDueSubscriptions(ctx context.Context, arg ListDueSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listDueSubscriptions, arg.UserID, arg.NextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.WebsiteUrl,
			&i.Amount,
			&i.AccountID,
			&i.SubcategoryID,
			&i.Period,
			&i.Weekday,
			&i.DayOfMonth,
			&i.StartDate,
			&i.TimeLocal,
			&i.NextRunAt,
			&i.UpcomingRunAts,
			&i.LastRunAt,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByUser = `-- name: ListSubscriptionsByUser :many
SELECT
    s.id,
    s.user_id,
    s.name,
    s.description,
    s.icon,
    s.website_url,
    s.amount,
    s.account_id,
    a.name AS account_name,
    s.subcategory_id,
    sub.name AS subcategory_name,
    sub.icon AS subcategory_icon,
    s.period,
    s.weekday,
    s.day_of_month,
    s.start_date,
    s.time_local,
    s.next_run_at,
    s.upcoming_run_ats,
    s.last_run_at,
    s.active,
    s.created_at,
    s.updated_at
FROM subscriptions s
JOIN accounts a ON a.id = s.account_id
LEFT JOIN subcategories sub ON sub.id = s.subcategory_id
WHERE s.user_id = ?
ORDER BY s.next_run_at ASC, s.created_at DESC
`

type ListSubscriptionsByUserRow struct {
	ID              string  `json:"id"`
	UserID          string  `json:"user_id"`
	Name            string  `json:"name"`
	Description     *string `json:"description"`
	Icon            *string `json:"icon"`
	WebsiteUrl      *string `json:"website_url"`
	Amount          int64   `json:"amount"`
	AccountID       string  `json:"account_id"`
	AccountName     string  `json:"account_name"`
	SubcategoryID   *string `json:"subcategory_id"`
	SubcategoryName *string `json:"subcategory_name"`
	SubcategoryIcon *string `json:"subcategory_icon"`
	Period          string  `json:"period"`
	Weekday         *int64  `json:"weekday"`
	DayOfMonth      *int64  `json:"day_of_month"`
	StartDate       string  `json:"start_date"`
	TimeLocal       string  `json:"time_local"`
	NextRunAt       string  `json:"next_run_at"`
	UpcomingRunAts  string  `json:"upcoming_run_ats"`
	LastRunAt       *string `json:"last_run_at"`
	Active          int64   `json:"active"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

func (q *Queries) ListSubscriptionsByUser(ctx context.Context, userID string) ([]ListSubscriptionsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsByUserRow{}
	for rows.Next() {
		var i ListSubscriptionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.WebsiteUrl,
			&i.Amount,
			&i.AccountID,
			&i.AccountName,
			&i.SubcategoryID,
			&i.SubcategoryName,
			&i.SubcategoryIcon,
			&i.Period,
			&i.Weekday,
			&i.DayOfMonth,
			&i.StartDate,
			&i.TimeLocal,
			&i.NextRunAt,
			&i.UpcomingRunAts,
			&i.LastRunAt,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsForUpcomingBackfill = `-- name: ListSubscriptionsForUpcomingBackfill :many
SELECT
    id,
    user_id,
    period,
    weekday,
    day_of_month,
    start_date,
    time_local,
    next_run_at,
    upcoming_run_ats
FROM subscriptions
WHERE upcoming_run_ats = '[]' OR upcoming_run_ats = '' OR upcoming_run_ats IS NULL
`

type ListSubscriptionsForUpcomingBackfillRow struct {
	ID             string `json:"id"`
	UserID         string `json:"user_id"`
	Period         string `json:"period"`
	Weekday        *int64 `json:"weekday"`
	DayOfMonth     *int64 `json:"day_of_month"`
	StartDate      string `json:"start_date"`
	TimeLocal      string `json:"time_local"`
	NextRunAt      string `json:"next_run_at"`
	UpcomingRunAts string `json:"upcoming_run_ats"`
}

func (q *Queries) ListSubscriptionsForUpcomingBackfill(ctx context.Context) ([]ListSubscriptionsForUpcomingBackfillRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsForUpcomingBackfill)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsForUpcomingBackfillRow{}
	for rows.Next() {
		var i ListSubscriptionsForUpcomingBackfillRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Period,
			&i.Weekday,
			&i.DayOfMonth,
			&i.StartDate,
			&i.TimeLocal,
			&i.NextRunAt,
			&i.UpcomingRunAts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubscriptionRan = `-- name: MarkSubscriptionRan :execrows
UPDATE subscriptions
SET next_run_at = ?, upcoming_run_ats = ?, last_run_at = ?, subcategory_id = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type MarkSubscriptionRanParams struct {
	NextRunAt      string  `json:"next_run_at"`
	UpcomingRunAts string  `json:"upcoming_run_ats"`
	LastRunAt      *string `json:"last_run_at"`
	SubcategoryID  *string `json:"subcategory_id"`
	UpdatedAt      string  `json:"updated_at"`
	ID             string  `json:"id"`
	UserID         string  `json:"user_id"`
}

func (q *Queries) MarkSubscriptionRan(ctx context.Context, arg MarkSubscriptionRanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markSubscriptionRan,
		arg.NextRunAt,
		arg.UpcomingRunAts,
		arg.LastRunAt,
		arg.SubcategoryID,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSubscriptionSubcategory = `-- name: SetSubscriptionSubcategory :execrows
UPDATE subscriptions
SET subcategory_id = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type SetSubscriptionSubcategoryParams struct {
	SubcategoryID *string `json:"subcategory_id"`
	UpdatedAt     string  `json:"updated_at"`
	ID            string  `json:"id"`
	UserID        string  `json:"user_id"`
}

func (q *Queries) SetSubscriptionSubcategory(ctx context.Context, arg SetSubscriptionSubcategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSubscriptionSubcategory,
		arg.SubcategoryID,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSubscriptionUpcoming = `-- name: SetSubscriptionUpcoming :execrows
UPDATE subscriptions
SET next_run_at = ?, upcoming_run_ats = ?, updated_at = ?
WHERE id = ?
`

type SetSubscriptionUpcomingParams struct {
	NextRunAt      string `json:"next_run_at"`
	UpcomingRunAts string `json:"upcoming_run_ats"`
	UpdatedAt      string `json:"updated_at"`
	ID             string `json:"id"`
}

func (q *Queries) SetSubscriptionUpcoming(ctx context.Context, arg SetSubscriptionUpcomingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSubscriptionUpcoming,
		arg.NextRunAt,
		arg.UpcomingRunAts,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSubscription = `-- name: UpdateSubscription :execrows
UPDATE subscriptions
SET name = ?, description = ?, icon = ?, website_url = ?,
    amount = ?, account_id = ?, subcategory_id = ?,
    period = ?, weekday = ?, day_of_month = ?,
    start_date = ?, time_local = ?, next_run_at = ?, upcoming_run_ats = ?, active = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateSubscriptionParams struct {
	Name           string  `json:"name"`
	Description    *string `json:"description"`
	Icon           *string `json:"icon"`
	WebsiteUrl     *string `json:"website_url"`
	Amount         int64   `json:"amount"`
	AccountID      string  `json:"account_id"`
	SubcategoryID  *string `json:"subcategory_id"`
	Period         string  `json:"period"`
	Weekday        *int64  `json:"weekday"`
	DayOfMonth     *int64  `json:"day_of_month"`
	StartDate      string  `json:"start_date"`
	TimeLocal      string  `json:"time_local"`
	NextRunAt      string  `json:"next_run_at"`
	UpcomingRunAts string  `json:"upcoming_run_ats"`
	Active         int64   `json:"active"`
	UpdatedAt      string  `json:"updated_at"`
	ID             string  `json:"id"`
	UserID         string  `json:"user_id"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSubscription,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.WebsiteUrl,
		arg.Amount,
		arg.AccountID,
		arg.SubcategoryID,
		arg.Period,
		arg.Weekday,
		arg.DayOfMonth,
		arg.StartDate,
		arg.TimeLocal,
		arg.NextRunAt,
		arg.UpcomingRunAts,
		arg.Active,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
