// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_settings.sql

package sqlc

import (
	"context"
)

const completeSetup = `-- name: CompleteSetup :exec
UPDATE system_settings
SET is_configured = 1, external_url = ?, registration_enabled = ?, updated_at = datetime('now')
WHERE id = 1
`

type CompleteSetupParams struct {
	ExternalUrl         *string `json:"external_url"`
	RegistrationEnabled int64   `json:"registration_enabled"`
}

func (q *Queries) CompleteSetup(ctx context.Context, arg CompleteSetupParams) error {
	_, err := q.db.ExecContext(ctx, completeSetup, arg.ExternalUrl, arg.RegistrationEnabled)
	return err
}

const getAdminSettings = `-- name: GetAdminSettings :one
SELECT registration_enabled, external_url, notification_secret_key
FROM system_settings WHERE id = 1
`

type GetAdminSettingsRow struct {
	RegistrationEnabled   int64   `json:"registration_enabled"`
	ExternalUrl           *string `json:"external_url"`
	NotificationSecretKey string  `json:"notification_secret_key"`
}

func (q *Queries) GetAdminSettings(ctx context.Context) (GetAdminSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminSettings)
	var i GetAdminSettingsRow
	err := row.Scan(&i.RegistrationEnabled, &i.ExternalUrl, &i.NotificationSecretKey)
	return i, err
}

const getAppVersion = `-- name: GetAppVersion :one
SELECT app_version FROM system_settings WHERE id = 1
`

func (q *Queries) GetAppVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getAppVersion)
	var app_version string
	err := row.Scan(&app_version)
	return app_version, err
}

const getBackupRetention = `-- name: GetBackupRetention :one
SELECT backup_retention FROM system_settings WHERE id = 1
`

func (q *Queries) GetBackupRetention(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBackupRetention)
	var backup_retention int64
	err := row.Scan(&backup_retention)
	return backup_retention, err
}

const getBackupSettings = `-- name: GetBackupSettings :one
SELECT backup_enabled, backup_time, backup_retention FROM system_settings WHERE id = 1
`

type GetBackupSettingsRow struct {
	BackupEnabled   int64   `json:"backup_enabled"`
	BackupTime      *string `json:"backup_time"`
	BackupRetention int64   `json:"backup_retention"`
}

func (q *Queries) GetBackupSettings(ctx context.Context) (GetBackupSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getBackupSettings)
	var i GetBackupSettingsRow
	err := row.Scan(&i.BackupEnabled, &i.BackupTime, &i.BackupRetention)
	return i, err
}

const getDiagnosticsSettings = `-- name: GetDiagnosticsSettings :one
SELECT external_url, previous_app_version FROM system_settings WHERE id = 1
`

type GetDiagnosticsSettingsRow struct {
	ExternalUrl        *string `json:"external_url"`
	PreviousAppVersion *string `json:"previous_app_version"`
}

func (q *Queries) GetDiagnosticsSettings(ctx context.Context) (GetDiagnosticsSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getDiagnosticsSettings)
	var i GetDiagnosticsSettingsRow
	err := row.Scan(&i.ExternalUrl, &i.PreviousAppVersion)
	return i, err
}

const getExternalURL = `-- name: GetExternalURL :one
SELECT external_url FROM system_settings WHERE id = 1
`

func (q *Queries) GetExternalURL(ctx context.Context) (*string, error) {
	row := q.db.QueryRowContext(ctx, getExternalURL)
	var external_url *string
	err := row.Scan(&external_url)
	return external_url, err
}

const getIsConfigured = `-- name: GetIsConfigured :one
SELECT is_configured FROM system_settings WHERE id = 1
`

func (q *Queries) GetIsConfigured(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getIsConfigured)
	var is_configured int64
	err := row.Scan(&is_configured)
	return is_configured, err
}

const getNotificationSecretKey = `-- name: GetNotificationSecretKey :one
SELECT notification_secret_key FROM system_settings WHERE id = 1
`

func (q *Queries) GetNotificationSecretKey(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getNotificationSecretKey)
	var notification_secret_key string
	err := row.Scan(&notification_secret_key)
	return notification_secret_key, err
}

const getRegistrationEnabled = `-- name: GetRegistrationEnabled :one
SELECT registration_enabled FROM system_settings WHERE id = 1
`

func (q *Queries) GetRegistrationEnabled(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRegistrationEnabled)
	var registration_enabled int64
	err := row.Scan(&registration_enabled)
	return registration_enabled, err
}

const getSetupStatus = `-- name: GetSetupStatus :one
SELECT registration_enabled, external_url FROM system_settings WHERE id = 1
`

type GetSetupStatusRow struct {
	RegistrationEnabled int64   `json:"registration_enabled"`
	ExternalUrl         *string `json:"external_url"`
}

func (q *Queries) GetSetupStatus(ctx context.Context) (GetSetupStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getSetupStatus)
	var i GetSetupStatusRow
	err := row.Scan(&i.RegistrationEnabled, &i.ExternalUrl)
	return i, err
}

const setAppVersionFirst = `-- name: SetAppVersionFirst :exec
UPDATE system_settings
SET app_version = ?, previous_app_version = NULL, updated_at = datetime('now')
WHERE id = 1
`

func (q *Queries) SetAppVersionFirst(ctx context.Context, appVersion string) error {
	_, err := q.db.ExecContext(ctx, setAppVersionFirst, appVersion)
	return err
}

const setAppVersionUpgrade = `-- name: SetAppVersionUpgrade :exec
UPDATE system_settings
SET previous_app_version = ?, app_version = ?, updated_at = datetime('now')
WHERE id = 1
`

type SetAppVersionUpgradeParams struct {
	PreviousAppVersion *string `json:"previous_app_version"`
	AppVersion         string  `json:"app_version"`
}

func (q *Queries) SetAppVersionUpgrade(ctx context.Context, arg SetAppVersionUpgradeParams) error {
	_, err := q.db.ExecContext(ctx, setAppVersionUpgrade, arg.PreviousAppVersion, arg.AppVersion)
	return err
}

const updateAdminSettings = `-- name: UpdateAdminSettings :exec
UPDATE system_settings
SET registration_enabled = ?, external_url = ?, updated_at = datetime('now')
WHERE id = 1
`

type UpdateAdminSettingsParams struct {
	RegistrationEnabled int64   `json:"registration_enabled"`
	ExternalUrl         *string `json:"external_url"`
}

func (q *Queries) UpdateAdminSettings(ctx context.Context, arg UpdateAdminSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminSettings, arg.RegistrationEnabled, arg.ExternalUrl)
	return err
}

const updateBackupSettings = `-- name: UpdateBackupSettings :exec
UPDATE system_settings
SET backup_enabled = ?, backup_time = ?, backup_retention = ?, updated_at = datetime('now')
WHERE id = 1
`

type UpdateBackupSettingsParams struct {
	BackupEnabled   int64   `json:"backup_enabled"`
	BackupTime      *string `json:"backup_time"`
	BackupRetention int64   `json:"backup_retention"`
}

func (q *Queries) UpdateBackupSettings(ctx context.Context, arg UpdateBackupSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateBackupSettings, arg.BackupEnabled, arg.BackupTime, arg.BackupRetention)
	return err
}

const updateDBPath = `-- name: UpdateDBPath :exec
UPDATE system_settings SET db_path = ? WHERE id = 1
`

func (q *Queries) UpdateDBPath(ctx context.Context, dbPath string) error {
	_, err := q.db.ExecContext(ctx, updateDBPath, dbPath)
	return err
}

const updateNotificationSecretKey = `-- name: UpdateNotificationSecretKey :exec
UPDATE system_settings
SET notification_secret_key = ?, updated_at = datetime('now')
WHERE id = 1
`

func (q *Queries) UpdateNotificationSecretKey(ctx context.Context, notificationSecretKey string) error {
	_, err := q.db.ExecContext(ctx, updateNotificationSecretKey, notificationSecretKey)
	return err
}
