// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package sqlc

import (
	"context"
	"strings"
)

const deleteTag = `-- name: DeleteTag :execrows
DELETE FROM tags
WHERE id = ? AND user_id = ?
`

type DeleteTagParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTag, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTransactionTags = `-- name: DeleteTransactionTags :exec
DELETE FROM transaction_tags WHERE transaction_id = ?
`

func (q *Queries) DeleteTransactionTags(ctx context.Context, transactionID string) error {
	_, err := q.db.ExecContext(ctx, deleteTransactionTags, transactionID)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, user_id, name, created_at
FROM tags
WHERE id = ? AND user_id = ?
`

type GetTagByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetTagByID(ctx context.Context, arg GetTagByIDParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByID, arg.ID, arg.UserID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, user_id, name, created_at
FROM tags
WHERE user_id = ?1 AND lower(name) = lower(?2)
`

type GetTagByNameParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, arg.UserID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const insertTag = `-- name: InsertTag :exec
INSERT INTO tags (id, user_id, name, created_at)
VALUES (?, ?, ?, ?)
`

type InsertTagParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) error {
	_, err := q.db.ExecContext(ctx, insertTag,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const insertTransactionTag = `-- name: InsertTransactionTag :exec
INSERT INTO transaction_tags (transaction_id, tag_id)
VALUES (?, ?)
`

type InsertTransactionTagParams struct {
	TransactionID string `json:"transaction_id"`
	TagID         string `json:"tag_id"`
}

func (q *Queries) InsertTransactionTag(ctx context.Context, arg InsertTransactionTagParams) error {
	_, err := q.db.ExecContext(ctx, insertTransactionTag, arg.TransactionID, arg.TagID)
	return err
}

const listTagsByTransactionID = `-- name: ListTagsByTransactionID :many
SELECT tg.id, tg.user_id, tg.name, tg.created_at
FROM transaction_tags tt
JOIN tags tg ON tg.id = tt.tag_id
WHERE tt.transaction_id = ?
ORDER BY tg.name COLLATE NOCASE ASC
`

func (q *Queries) ListTagsByTransactionID(ctx context.Context, transactionID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByTransactionID, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByUser = `-- name: ListTagsByUser :many
SELECT id, user_id, name, created_at
FROM tags
WHERE user_id = ?
  AND (? = '' OR name LIKE '%' || ? || '%')
ORDER BY name COLLATE NOCASE ASC
`

type ListTagsByUserParams struct {
	UserID  string      `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Column3 *string     `json:"column_3"`
}

func (q *Queries) ListTagsByUser(ctx context.Context, arg ListTagsByUserParams) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByUser, arg.UserID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForTransactions = `-- name: ListTagsForTransactions :many
SELECT tt.transaction_id, tg.id AS tag_id, tg.name AS tag_name
FROM transaction_tags tt
JOIN tags tg ON tg.id = tt.tag_id
WHERE tt.transaction_id IN (/*SLICE:transaction_ids*/?)
ORDER BY tg.name COLLATE NOCASE ASC
`

type ListTagsForTransactionsRow struct {
	TransactionID string `json:"transaction_id"`
	TagID         string `json:"tag_id"`
	TagName       string `json:"tag_name"`
}

func (q *Queries) ListTagsForTransactions(ctx context.Context, transactionIds []string) ([]ListTagsForTransactionsRow, error) {
	query := listTagsForTransactions
	var queryParams []interface{}
	if len(transactionIds) > 0 {
		for _, v := range transactionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:transaction_ids*/?", strings.Repeat(",?", len(transactionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:transaction_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsForTransactionsRow{}
	for rows.Next() {
		var i ListTagsForTransactionsRow
		if err := rows.Scan(&i.TransactionID, &i.TagID, &i.TagName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTagName = `-- name: UpdateTagName :execrows
UPDATE tags
SET name = ?
WHERE id = ? AND user_id = ?
`

type UpdateTagNameParams struct {
	Name   string `json:"name"`
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpdateTagName(ctx context.Context, arg UpdateTagNameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTagName, arg.Name, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
