// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction_templates.sql

package sqlc

import (
	"context"
	"strings"
)

const countTransactionTemplatesByUser = `-- name: CountTransactionTemplatesByUser :one
SELECT COUNT(*) FROM transaction_templates WHERE user_id = ?
`

func (q *Queries) CountTransactionTemplatesByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionTemplatesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTransactionTemplate = `-- name: DeleteTransactionTemplate :execrows
DELETE FROM transaction_templates
WHERE id = ? AND user_id = ?
`

type DeleteTransactionTemplateParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteTransactionTemplate(ctx context.Context, arg DeleteTransactionTemplateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTransactionTemplate, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTransactionTemplateTags = `-- name: DeleteTransactionTemplateTags :exec
DELETE FROM transaction_template_tags WHERE template_id = ?
`

func (q *Queries) DeleteTransactionTemplateTags(ctx context.Context, templateID string) error {
	_, err := q.db.ExecContext(ctx, deleteTransactionTemplateTags, templateID)
	return err
}

const getTransactionTemplateByID = `-- name: GetTransactionTemplateByID :one
SELECT
    id, user_id, name, type,
    account_id, to_account_id, category_id, subcategory_id,
    amount, description, merchant_id, icon, sort_order,
    created_at, updated_at
FROM transaction_templates
WHERE id = ? AND user_id = ?
`

type GetTransactionTemplateByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetTransactionTemplateByID(ctx context.Context, arg GetTransactionTemplateByIDParams) (TransactionTemplate, error) {
	row := q.db.QueryRowContext(ctx, getTransactionTemplateByID, arg.ID, arg.UserID)
	var i TransactionTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.AccountID,
		&i.ToAccountID,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.Amount,
		&i.Description,
		&i.MerchantID,
		&i.Icon,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTransactionTemplate = `-- name: InsertTransactionTemplate :exec
INSERT INTO transaction_templates (
    id, user_id, name, type,
    account_id, to_account_id, category_id, subcategory_id,
    amount, description, merchant_id, icon, sort_order,
    created_at, updated_at
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?
)
`

type InsertTransactionTemplateParams struct {
	ID            string  `json:"id"`
	UserID        string  `json:"user_id"`
	Name          string  `json:"name"`
	Type          string  `json:"type"`
	AccountID     *string `json:"account_id"`
	ToAccountID   *string `json:"to_account_id"`
	CategoryID    *string `json:"category_id"`
	SubcategoryID *string `json:"subcategory_id"`
	Amount        *int64  `json:"amount"`
	Description   *string `json:"description"`
	MerchantID    *string `json:"merchant_id"`
	Icon          *string `json:"icon"`
	SortOrder     int64   `json:"sort_order"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
}

func (q *Queries) InsertTransactionTemplate(ctx context.Context, arg InsertTransactionTemplateParams) error {
	_, err := q.db.ExecContext(ctx, insertTransactionTemplate,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.AccountID,
		arg.ToAccountID,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.Amount,
		arg.Description,
		arg.MerchantID,
		arg.Icon,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertTransactionTemplateTag = `-- name: InsertTransactionTemplateTag :exec
INSERT INTO transaction_template_tags (template_id, tag_id)
VALUES (?, ?)
`

type InsertTransactionTemplateTagParams struct {
	TemplateID string `json:"template_id"`
	TagID      string `json:"tag_id"`
}

func (q *Queries) InsertTransactionTemplateTag(ctx context.Context, arg InsertTransactionTemplateTagParams) error {
	_, err := q.db.ExecContext(ctx, insertTransactionTemplateTag, arg.TemplateID, arg.TagID)
	return err
}

const listTagsByTemplateID = `-- name: ListTagsByTemplateID :many
SELECT tg.id, tg.user_id, tg.name, tg.created_at
FROM transaction_template_tags tt
JOIN tags tg ON tg.id = tt.tag_id
WHERE tt.template_id = ?
ORDER BY tg.name COLLATE NOCASE ASC
`

func (q *Queries) ListTagsByTemplateID(ctx context.Context, templateID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByTemplateID, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForTemplates = `-- name: ListTagsForTemplates :many
SELECT tt.template_id, tg.id AS tag_id, tg.name AS tag_name
FROM transaction_template_tags tt
JOIN tags tg ON tg.id = tt.tag_id
WHERE tt.template_id IN (/*SLICE:template_ids*/?)
ORDER BY tg.name COLLATE NOCASE ASC
`

type ListTagsForTemplatesRow struct {
	TemplateID string `json:"template_id"`
	TagID      string `json:"tag_id"`
	TagName    string `json:"tag_name"`
}

func (q *Queries) ListTagsForTemplates(ctx context.Context, templateIds []string) ([]ListTagsForTemplatesRow, error) {
	query := listTagsForTemplates
	var queryParams []interface{}
	if len(templateIds) > 0 {
		for _, v := range templateIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:template_ids*/?", strings.Repeat(",?", len(templateIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:template_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsForTemplatesRow{}
	for rows.Next() {
		var i ListTagsForTemplatesRow
		if err := rows.Scan(&i.TemplateID, &i.TagID, &i.TagName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionTemplatesByUser = `-- name: ListTransactionTemplatesByUser :many
SELECT
    id, user_id, name, type,
    account_id, to_account_id, category_id, subcategory_id,
    amount, description, merchant_id, icon, sort_order,
    created_at, updated_at
FROM transaction_templates
WHERE user_id = ?
ORDER BY sort_order ASC, name COLLATE NOCASE ASC
`

func (q *Queries) ListTransactionTemplatesByUser(ctx context.Context, userID string) ([]TransactionTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionTemplatesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionTemplate{}
	for rows.Next() {
		var i TransactionTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.AccountID,
			&i.ToAccountID,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.Amount,
			&i.Description,
			&i.MerchantID,
			&i.Icon,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxTransactionTemplateSortOrder = `-- name: MaxTransactionTemplateSortOrder :one
SELECT COALESCE(MAX(sort_order), 0)
FROM transaction_templates
WHERE user_id = ?
`

func (q *Queries) MaxTransactionTemplateSortOrder(ctx context.Context, userID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxTransactionTemplateSortOrder, userID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const updateTransactionTemplate = `-- name: UpdateTransactionTemplate :execrows
UPDATE transaction_templates
SET name = ?,
    type = ?,
    account_id = ?,
    to_account_id = ?,
    category_id = ?,
    subcategory_id = ?,
    amount = ?,
    description = ?,
    merchant_id = ?,
    icon = ?,
    updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateTransactionTemplateParams struct {
	Name          string  `json:"name"`
	Type          string  `json:"type"`
	AccountID     *string `json:"account_id"`
	ToAccountID   *string `json:"to_account_id"`
	CategoryID    *string `json:"category_id"`
	SubcategoryID *string `json:"subcategory_id"`
	Amount        *int64  `json:"amount"`
	Description   *string `json:"description"`
	MerchantID    *string `json:"merchant_id"`
	Icon          *string `json:"icon"`
	UpdatedAt     string  `json:"updated_at"`
	ID            string  `json:"id"`
	UserID        string  `json:"user_id"`
}

func (q *Queries) UpdateTransactionTemplate(ctx context.Context, arg UpdateTransactionTemplateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTransactionTemplate,
		arg.Name,
		arg.Type,
		arg.AccountID,
		arg.ToAccountID,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.Amount,
		arg.Description,
		arg.MerchantID,
		arg.Icon,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTransactionTemplateSortOrder = `-- name: UpdateTransactionTemplateSortOrder :exec
UPDATE transaction_templates
SET sort_order = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateTransactionTemplateSortOrderParams struct {
	SortOrder int64  `json:"sort_order"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) UpdateTransactionTemplateSortOrder(ctx context.Context, arg UpdateTransactionTemplateSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateTransactionTemplateSortOrder,
		arg.SortOrder,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}
