// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"
)

const activateAppliedCreditFutureTransactions = `-- name: ActivateAppliedCreditFutureTransactions :execrows
UPDATE transactions
SET kind = 'manual', updated_at = ?
WHERE user_id = ?
  AND kind = 'future'
  AND id IN (
    SELECT cp.transaction_id
    FROM credit_payments cp
    WHERE cp.transaction_id IS NOT NULL
      AND cp.is_applied = 1
      AND cp.exclude_from_stats = 0
  )
`

type ActivateAppliedCreditFutureTransactionsParams struct {
	UpdatedAt string `json:"updated_at"`
	UserID    string `json:"user_id"`
}

func (q *Queries) ActivateAppliedCreditFutureTransactions(ctx context.Context, arg ActivateAppliedCreditFutureTransactionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, activateAppliedCreditFutureTransactions, arg.UpdatedAt, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const activateFutureTransactionsBefore = `-- name: ActivateFutureTransactionsBefore :execrows
UPDATE transactions
SET kind = 'manual', updated_at = ?
WHERE user_id = ?
  AND kind = 'future'
  AND transaction_date <= ?
`

type ActivateFutureTransactionsBeforeParams struct {
	UpdatedAt       string `json:"updated_at"`
	UserID          string `json:"user_id"`
	TransactionDate string `json:"transaction_date"`
}

func (q *Queries) ActivateFutureTransactionsBefore(ctx context.Context, arg ActivateFutureTransactionsBeforeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, activateFutureTransactionsBefore, arg.UpdatedAt, arg.UserID, arg.TransactionDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const activateTransaction = `-- name: ActivateTransaction :execrows
UPDATE transactions SET kind = 'manual', updated_at = ? WHERE id = ? AND user_id = ? AND kind = 'future'
`

type ActivateTransactionParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) ActivateTransaction(ctx context.Context, arg ActivateTransactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, activateTransaction, arg.UpdatedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countTransactionsFiltered = `-- name: CountTransactionsFiltered :one
SELECT COUNT(*) AS count
FROM transactions t
WHERE t.user_id = ?
  AND (? = '' OR t.account_id = ?)
  AND (? = '' OR t.type = ?)
  AND (? = '' OR t.category_id = ?)
  AND (? = '' OR t.kind = ?)
  AND (? = '' OR t.transaction_date >= ?)
  AND (? = '' OR t.transaction_date <= ?)
  AND (? = '' OR t.description LIKE '%' || ? || '%')
`

type CountTransactionsFilteredParams struct {
	UserID            string      `json:"user_id"`
	Column2           interface{} `json:"column_2"`
	AccountID         string      `json:"account_id"`
	Column4           interface{} `json:"column_4"`
	Type              string      `json:"type"`
	Column6           interface{} `json:"column_6"`
	CategoryID        *string     `json:"category_id"`
	Column8           interface{} `json:"column_8"`
	Kind              string      `json:"kind"`
	Column10          interface{} `json:"column_10"`
	TransactionDate   string      `json:"transaction_date"`
	Column12          interface{} `json:"column_12"`
	TransactionDate_2 string      `json:"transaction_date_2"`
	Column14          interface{} `json:"column_14"`
	Column15          *string     `json:"column_15"`
}

func (q *Queries) CountTransactionsFiltered(ctx context.Context, arg CountTransactionsFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionsFiltered,
		arg.UserID,
		arg.Column2,
		arg.AccountID,
		arg.Column4,
		arg.Type,
		arg.Column6,
		arg.CategoryID,
		arg.Column8,
		arg.Kind,
		arg.Column10,
		arg.TransactionDate,
		arg.Column12,
		arg.TransactionDate_2,
		arg.Column14,
		arg.Column15,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions WHERE id = ? AND user_id = ?
`

type DeleteTransactionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTransaction, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTransactionsByGroup = `-- name: DeleteTransactionsByGroup :execrows
DELETE FROM transactions WHERE transfer_group_id = ? AND user_id = ?
`

type DeleteTransactionsByGroupParams struct {
	TransferGroupID *string `json:"transfer_group_id"`
	UserID          string  `json:"user_id"`
}

func (q *Queries) DeleteTransactionsByGroup(ctx context.Context, arg DeleteTransactionsByGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTransactionsByGroup, arg.TransferGroupID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCategoryByNameAndType = `-- name: GetCategoryByNameAndType :one
SELECT id, name, type, icon, sort_order, is_primary, is_system, created_at
FROM categories
WHERE user_id = ? AND name = ? AND type = ?
`

type GetCategoryByNameAndTypeParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
	Type   string `json:"type"`
}

type GetCategoryByNameAndTypeRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	Icon      string `json:"icon"`
	SortOrder int64  `json:"sort_order"`
	IsPrimary int64  `json:"is_primary"`
	IsSystem  int64  `json:"is_system"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) GetCategoryByNameAndType(ctx context.Context, arg GetCategoryByNameAndTypeParams) (GetCategoryByNameAndTypeRow, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByNameAndType, arg.UserID, arg.Name, arg.Type)
	var i GetCategoryByNameAndTypeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.SortOrder,
		&i.IsPrimary,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT
    t.id,
    t.user_id,
    t.account_id,
    t.type,
    t.kind,
    t.amount,
    t.description,
    t.category_id,
    t.subcategory_id,
    t.transfer_group_id,
    t.transfer_account_id,
    t.transaction_date,
    t.created_at,
    t.updated_at,
    c.name AS category_name,
    c.icon AS category_icon,
    c.is_system AS category_is_system,
    s.name AS subcategory_name,
    a.name AS account_name,
    ta.name AS transfer_account_name,
    CASE
        WHEN t.transfer_group_id IS NULL THEN 0
        WHEN t.id = (
            SELECT x.id FROM transactions x
            WHERE x.transfer_group_id = t.transfer_group_id
            ORDER BY x.created_at ASC, x.id ASC
            LIMIT 1
        ) THEN 1
        ELSE 0
    END AS transfer_is_out,
    CASE WHEN cp.id IS NOT NULL THEN 1 ELSE 0 END AS credit_payment_linked
FROM transactions t
LEFT JOIN categories c ON c.id = t.category_id
LEFT JOIN subcategories s ON s.id = t.subcategory_id
LEFT JOIN accounts a ON a.id = t.account_id
LEFT JOIN accounts ta ON ta.id = t.transfer_account_id
LEFT JOIN credit_payments cp ON cp.transaction_id = t.id
WHERE t.id = ? AND t.user_id = ?
`

type GetTransactionByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type GetTransactionByIDRow struct {
	ID                  string  `json:"id"`
	UserID              string  `json:"user_id"`
	AccountID           string  `json:"account_id"`
	Type                string  `json:"type"`
	Kind                string  `json:"kind"`
	Amount              int64   `json:"amount"`
	Description         *string `json:"description"`
	CategoryID          *string `json:"category_id"`
	SubcategoryID       *string `json:"subcategory_id"`
	TransferGroupID     *string `json:"transfer_group_id"`
	TransferAccountID   *string `json:"transfer_account_id"`
	TransactionDate     string  `json:"transaction_date"`
	CreatedAt           string  `json:"created_at"`
	UpdatedAt           string  `json:"updated_at"`
	CategoryName        *string `json:"category_name"`
	CategoryIcon        *string `json:"category_icon"`
	CategoryIsSystem    *int64  `json:"category_is_system"`
	SubcategoryName     *string `json:"subcategory_name"`
	AccountName         *string `json:"account_name"`
	TransferAccountName *string `json:"transfer_account_name"`
	TransferIsOut       int64   `json:"transfer_is_out"`
	CreditPaymentLinked int64   `json:"credit_payment_linked"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (GetTransactionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, arg.ID, arg.UserID)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Type,
		&i.Kind,
		&i.Amount,
		&i.Description,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.TransferGroupID,
		&i.TransferAccountID,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategoryIcon,
		&i.CategoryIsSystem,
		&i.SubcategoryName,
		&i.AccountName,
		&i.TransferAccountName,
		&i.TransferIsOut,
		&i.CreditPaymentLinked,
	)
	return i, err
}

const getUserTimezone = `-- name: GetUserTimezone :one
SELECT timezone FROM users WHERE id = ?
`

func (q *Queries) GetUserTimezone(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserTimezone, id)
	var timezone string
	err := row.Scan(&timezone)
	return timezone, err
}

const hasFutureInMonth = `-- name: HasFutureInMonth :one
SELECT COUNT(*) AS count
FROM transactions
WHERE user_id = ? AND account_id = ? AND kind = 'future'
  AND transaction_date >= ? AND transaction_date <= ?
`

type HasFutureInMonthParams struct {
	UserID            string `json:"user_id"`
	AccountID         string `json:"account_id"`
	TransactionDate   string `json:"transaction_date"`
	TransactionDate_2 string `json:"transaction_date_2"`
}

func (q *Queries) HasFutureInMonth(ctx context.Context, arg HasFutureInMonthParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasFutureInMonth,
		arg.UserID,
		arg.AccountID,
		arg.TransactionDate,
		arg.TransactionDate_2,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO transactions (
    id, user_id, account_id, type, kind, amount, description,
    category_id, subcategory_id, transfer_group_id, transfer_account_id,
    transaction_date, affects_balance, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTransactionParams struct {
	ID                string  `json:"id"`
	UserID            string  `json:"user_id"`
	AccountID         string  `json:"account_id"`
	Type              string  `json:"type"`
	Kind              string  `json:"kind"`
	Amount            int64   `json:"amount"`
	Description       *string `json:"description"`
	CategoryID        *string `json:"category_id"`
	SubcategoryID     *string `json:"subcategory_id"`
	TransferGroupID   *string `json:"transfer_group_id"`
	TransferAccountID *string `json:"transfer_account_id"`
	TransactionDate   string  `json:"transaction_date"`
	AffectsBalance    int64   `json:"affects_balance"`
	CreatedAt         string  `json:"created_at"`
	UpdatedAt         string  `json:"updated_at"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.ExecContext(ctx, insertTransaction,
		arg.ID,
		arg.UserID,
		arg.AccountID,
		arg.Type,
		arg.Kind,
		arg.Amount,
		arg.Description,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.TransferGroupID,
		arg.TransferAccountID,
		arg.TransactionDate,
		arg.AffectsBalance,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listDueFutureTransactions = `-- name: ListDueFutureTransactions :many
SELECT
    t.id,
    t.user_id,
    t.account_id,
    t.type,
    t.kind,
    t.amount,
    t.description,
    t.category_id,
    t.subcategory_id,
    t.transfer_group_id,
    t.transfer_account_id,
    t.transaction_date,
    t.affects_balance,
    t.created_at,
    t.updated_at
FROM transactions t
WHERE t.user_id = ?
  AND t.kind = 'future'
  AND t.transaction_date <= ?
ORDER BY t.transaction_date ASC, t.created_at ASC
`

type ListDueFutureTransactionsParams struct {
	UserID          string `json:"user_id"`
	TransactionDate string `json:"transaction_date"`
}

func (q *Queries) ListDueFutureTransactions(ctx context.Context, arg ListDueFutureTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listDueFutureTransactions, arg.UserID, arg.TransactionDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Type,
			&i.Kind,
			&i.Amount,
			&i.Description,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.TransferGroupID,
			&i.TransferAccountID,
			&i.TransactionDate,
			&i.AffectsBalance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentTransactions = `-- name: ListRecentTransactions :many
SELECT
    t.id,
    t.user_id,
    t.account_id,
    t.type,
    t.kind,
    t.amount,
    t.description,
    t.category_id,
    t.subcategory_id,
    t.transfer_group_id,
    t.transfer_account_id,
    t.transaction_date,
    t.created_at,
    t.updated_at,
    c.name AS category_name,
    c.icon AS category_icon,
    c.is_system AS category_is_system,
    s.name AS subcategory_name,
    a.name AS account_name,
    ta.name AS transfer_account_name,
    CASE
        WHEN t.transfer_group_id IS NULL THEN 0
        WHEN t.id = (
            SELECT x.id FROM transactions x
            WHERE x.transfer_group_id = t.transfer_group_id
            ORDER BY x.created_at ASC, x.id ASC
            LIMIT 1
        ) THEN 1
        ELSE 0
    END AS transfer_is_out,
    CASE WHEN cp.id IS NOT NULL THEN 1 ELSE 0 END AS credit_payment_linked
FROM transactions t
LEFT JOIN categories c ON c.id = t.category_id
LEFT JOIN subcategories s ON s.id = t.subcategory_id
LEFT JOIN accounts a ON a.id = t.account_id
LEFT JOIN accounts ta ON ta.id = t.transfer_account_id
LEFT JOIN credit_payments cp ON cp.transaction_id = t.id
WHERE t.user_id = ?
ORDER BY t.transaction_date DESC, t.created_at DESC
LIMIT ?
`

type ListRecentTransactionsParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
}

type ListRecentTransactionsRow struct {
	ID                  string  `json:"id"`
	UserID              string  `json:"user_id"`
	AccountID           string  `json:"account_id"`
	Type                string  `json:"type"`
	Kind                string  `json:"kind"`
	Amount              int64   `json:"amount"`
	Description         *string `json:"description"`
	CategoryID          *string `json:"category_id"`
	SubcategoryID       *string `json:"subcategory_id"`
	TransferGroupID     *string `json:"transfer_group_id"`
	TransferAccountID   *string `json:"transfer_account_id"`
	TransactionDate     string  `json:"transaction_date"`
	CreatedAt           string  `json:"created_at"`
	UpdatedAt           string  `json:"updated_at"`
	CategoryName        *string `json:"category_name"`
	CategoryIcon        *string `json:"category_icon"`
	CategoryIsSystem    *int64  `json:"category_is_system"`
	SubcategoryName     *string `json:"subcategory_name"`
	AccountName         *string `json:"account_name"`
	TransferAccountName *string `json:"transfer_account_name"`
	TransferIsOut       int64   `json:"transfer_is_out"`
	CreditPaymentLinked int64   `json:"credit_payment_linked"`
}

func (q *Queries) ListRecentTransactions(ctx context.Context, arg ListRecentTransactionsParams) ([]ListRecentTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentTransactions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentTransactionsRow{}
	for rows.Next() {
		var i ListRecentTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Type,
			&i.Kind,
			&i.Amount,
			&i.Description,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.TransferGroupID,
			&i.TransferAccountID,
			&i.TransactionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryIsSystem,
			&i.SubcategoryName,
			&i.AccountName,
			&i.TransferAccountName,
			&i.TransferIsOut,
			&i.CreditPaymentLinked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByTransferGroup = `-- name: ListTransactionsByTransferGroup :many
SELECT
    t.id,
    t.user_id,
    t.account_id,
    t.type,
    t.kind,
    t.amount,
    t.description,
    t.category_id,
    t.subcategory_id,
    t.transfer_group_id,
    t.transfer_account_id,
    t.transaction_date,
    t.created_at,
    t.updated_at,
    c.name AS category_name,
    c.icon AS category_icon,
    c.is_system AS category_is_system,
    s.name AS subcategory_name,
    a.name AS account_name,
    ta.name AS transfer_account_name,
    CASE
        WHEN t.transfer_group_id IS NULL THEN 0
        WHEN t.id = (
            SELECT x.id FROM transactions x
            WHERE x.transfer_group_id = t.transfer_group_id
            ORDER BY x.created_at ASC, x.id ASC
            LIMIT 1
        ) THEN 1
        ELSE 0
    END AS transfer_is_out
FROM transactions t
LEFT JOIN categories c ON c.id = t.category_id
LEFT JOIN subcategories s ON s.id = t.subcategory_id
LEFT JOIN accounts a ON a.id = t.account_id
LEFT JOIN accounts ta ON ta.id = t.transfer_account_id
WHERE t.transfer_group_id = ? AND t.user_id = ?
ORDER BY t.created_at ASC, t.id ASC
`

type ListTransactionsByTransferGroupParams struct {
	TransferGroupID *string `json:"transfer_group_id"`
	UserID          string  `json:"user_id"`
}

type ListTransactionsByTransferGroupRow struct {
	ID                  string  `json:"id"`
	UserID              string  `json:"user_id"`
	AccountID           string  `json:"account_id"`
	Type                string  `json:"type"`
	Kind                string  `json:"kind"`
	Amount              int64   `json:"amount"`
	Description         *string `json:"description"`
	CategoryID          *string `json:"category_id"`
	SubcategoryID       *string `json:"subcategory_id"`
	TransferGroupID     *string `json:"transfer_group_id"`
	TransferAccountID   *string `json:"transfer_account_id"`
	TransactionDate     string  `json:"transaction_date"`
	CreatedAt           string  `json:"created_at"`
	UpdatedAt           string  `json:"updated_at"`
	CategoryName        *string `json:"category_name"`
	CategoryIcon        *string `json:"category_icon"`
	CategoryIsSystem    *int64  `json:"category_is_system"`
	SubcategoryName     *string `json:"subcategory_name"`
	AccountName         *string `json:"account_name"`
	TransferAccountName *string `json:"transfer_account_name"`
	TransferIsOut       int64   `json:"transfer_is_out"`
}

func (q *Queries) ListTransactionsByTransferGroup(ctx context.Context, arg ListTransactionsByTransferGroupParams) ([]ListTransactionsByTransferGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByTransferGroup, arg.TransferGroupID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByTransferGroupRow{}
	for rows.Next() {
		var i ListTransactionsByTransferGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Type,
			&i.Kind,
			&i.Amount,
			&i.Description,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.TransferGroupID,
			&i.TransferAccountID,
			&i.TransactionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryIsSystem,
			&i.SubcategoryName,
			&i.AccountName,
			&i.TransferAccountName,
			&i.TransferIsOut,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsFilteredDateAsc = `-- name: ListTransactionsFilteredDateAsc :many
SELECT
    t.id,
    t.user_id,
    t.account_id,
    t.type,
    t.kind,
    t.amount,
    t.description,
    t.category_id,
    t.subcategory_id,
    t.transfer_group_id,
    t.transfer_account_id,
    t.transaction_date,
    t.created_at,
    t.updated_at,
    c.name AS category_name,
    c.icon AS category_icon,
    c.is_system AS category_is_system,
    s.name AS subcategory_name,
    a.name AS account_name,
    ta.name AS transfer_account_name,
    CASE
        WHEN t.transfer_group_id IS NULL THEN 0
        WHEN t.id = (
            SELECT x.id FROM transactions x
            WHERE x.transfer_group_id = t.transfer_group_id
            ORDER BY x.created_at ASC, x.id ASC
            LIMIT 1
        ) THEN 1
        ELSE 0
    END AS transfer_is_out,
    CASE WHEN cp.id IS NOT NULL THEN 1 ELSE 0 END AS credit_payment_linked
FROM transactions t
LEFT JOIN categories c ON c.id = t.category_id
LEFT JOIN subcategories s ON s.id = t.subcategory_id
LEFT JOIN accounts a ON a.id = t.account_id
LEFT JOIN accounts ta ON ta.id = t.transfer_account_id
LEFT JOIN credit_payments cp ON cp.transaction_id = t.id
WHERE t.user_id = ?
  AND (? = '' OR t.account_id = ?)
  AND (? = '' OR t.type = ?)
  AND (? = '' OR t.category_id = ?)
  AND (? = '' OR t.kind = ?)
  AND (? = '' OR t.transaction_date >= ?)
  AND (? = '' OR t.transaction_date <= ?)
  AND (? = '' OR t.description LIKE '%' || ? || '%')
ORDER BY t.transaction_date ASC, t.created_at ASC
LIMIT ? OFFSET ?
`

type ListTransactionsFilteredDateAscParams struct {
	UserID            string      `json:"user_id"`
	Column2           interface{} `json:"column_2"`
	AccountID         string      `json:"account_id"`
	Column4           interface{} `json:"column_4"`
	Type              string      `json:"type"`
	Column6           interface{} `json:"column_6"`
	CategoryID        *string     `json:"category_id"`
	Column8           interface{} `json:"column_8"`
	Kind              string      `json:"kind"`
	Column10          interface{} `json:"column_10"`
	TransactionDate   string      `json:"transaction_date"`
	Column12          interface{} `json:"column_12"`
	TransactionDate_2 string      `json:"transaction_date_2"`
	Column14          interface{} `json:"column_14"`
	Column15          *string     `json:"column_15"`
	Limit             int64       `json:"limit"`
	Offset            int64       `json:"offset"`
}

type ListTransactionsFilteredDateAscRow struct {
	ID                  string  `json:"id"`
	UserID              string  `json:"user_id"`
	AccountID           string  `json:"account_id"`
	Type                string  `json:"type"`
	Kind                string  `json:"kind"`
	Amount              int64   `json:"amount"`
	Description         *string `json:"description"`
	CategoryID          *string `json:"category_id"`
	SubcategoryID       *string `json:"subcategory_id"`
	TransferGroupID     *string `json:"transfer_group_id"`
	TransferAccountID   *string `json:"transfer_account_id"`
	TransactionDate     string  `json:"transaction_date"`
	CreatedAt           string  `json:"created_at"`
	UpdatedAt           string  `json:"updated_at"`
	CategoryName        *string `json:"category_name"`
	CategoryIcon        *string `json:"category_icon"`
	CategoryIsSystem    *int64  `json:"category_is_system"`
	SubcategoryName     *string `json:"subcategory_name"`
	AccountName         *string `json:"account_name"`
	TransferAccountName *string `json:"transfer_account_name"`
	TransferIsOut       int64   `json:"transfer_is_out"`
	CreditPaymentLinked int64   `json:"credit_payment_linked"`
}

func (q *Queries) ListTransactionsFilteredDateAsc(ctx context.Context, arg ListTransactionsFilteredDateAscParams) ([]ListTransactionsFilteredDateAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsFilteredDateAsc,
		arg.UserID,
		arg.Column2,
		arg.AccountID,
		arg.Column4,
		arg.Type,
		arg.Column6,
		arg.CategoryID,
		arg.Column8,
		arg.Kind,
		arg.Column10,
		arg.TransactionDate,
		arg.Column12,
		arg.TransactionDate_2,
		arg.Column14,
		arg.Column15,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsFilteredDateAscRow{}
	for rows.Next() {
		var i ListTransactionsFilteredDateAscRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Type,
			&i.Kind,
			&i.Amount,
			&i.Description,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.TransferGroupID,
			&i.TransferAccountID,
			&i.TransactionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryIsSystem,
			&i.SubcategoryName,
			&i.AccountName,
			&i.TransferAccountName,
			&i.TransferIsOut,
			&i.CreditPaymentLinked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsFilteredDateDesc = `-- name: ListTransactionsFilteredDateDesc :many
SELECT
    t.id,
    t.user_id,
    t.account_id,
    t.type,
    t.kind,
    t.amount,
    t.description,
    t.category_id,
    t.subcategory_id,
    t.transfer_group_id,
    t.transfer_account_id,
    t.transaction_date,
    t.created_at,
    t.updated_at,
    c.name AS category_name,
    c.icon AS category_icon,
    c.is_system AS category_is_system,
    s.name AS subcategory_name,
    a.name AS account_name,
    ta.name AS transfer_account_name,
    CASE
        WHEN t.transfer_group_id IS NULL THEN 0
        WHEN t.id = (
            SELECT x.id FROM transactions x
            WHERE x.transfer_group_id = t.transfer_group_id
            ORDER BY x.created_at ASC, x.id ASC
            LIMIT 1
        ) THEN 1
        ELSE 0
    END AS transfer_is_out,
    CASE WHEN cp.id IS NOT NULL THEN 1 ELSE 0 END AS credit_payment_linked
FROM transactions t
LEFT JOIN categories c ON c.id = t.category_id
LEFT JOIN subcategories s ON s.id = t.subcategory_id
LEFT JOIN accounts a ON a.id = t.account_id
LEFT JOIN accounts ta ON ta.id = t.transfer_account_id
LEFT JOIN credit_payments cp ON cp.transaction_id = t.id
WHERE t.user_id = ?
  AND (? = '' OR t.account_id = ?)
  AND (? = '' OR t.type = ?)
  AND (? = '' OR t.category_id = ?)
  AND (? = '' OR t.kind = ?)
  AND (? = '' OR t.transaction_date >= ?)
  AND (? = '' OR t.transaction_date <= ?)
  AND (? = '' OR t.description LIKE '%' || ? || '%')
ORDER BY t.transaction_date DESC, t.created_at DESC
LIMIT ? OFFSET ?
`

type ListTransactionsFilteredDateDescParams struct {
	UserID            string      `json:"user_id"`
	Column2           interface{} `json:"column_2"`
	AccountID         string      `json:"account_id"`
	Column4           interface{} `json:"column_4"`
	Type              string      `json:"type"`
	Column6           interface{} `json:"column_6"`
	CategoryID        *string     `json:"category_id"`
	Column8           interface{} `json:"column_8"`
	Kind              string      `json:"kind"`
	Column10          interface{} `json:"column_10"`
	TransactionDate   string      `json:"transaction_date"`
	Column12          interface{} `json:"column_12"`
	TransactionDate_2 string      `json:"transaction_date_2"`
	Column14          interface{} `json:"column_14"`
	Column15          *string     `json:"column_15"`
	Limit             int64       `json:"limit"`
	Offset            int64       `json:"offset"`
}

type ListTransactionsFilteredDateDescRow struct {
	ID                  string  `json:"id"`
	UserID              string  `json:"user_id"`
	AccountID           string  `json:"account_id"`
	Type                string  `json:"type"`
	Kind                string  `json:"kind"`
	Amount              int64   `json:"amount"`
	Description         *string `json:"description"`
	CategoryID          *string `json:"category_id"`
	SubcategoryID       *string `json:"subcategory_id"`
	TransferGroupID     *string `json:"transfer_group_id"`
	TransferAccountID   *string `json:"transfer_account_id"`
	TransactionDate     string  `json:"transaction_date"`
	CreatedAt           string  `json:"created_at"`
	UpdatedAt           string  `json:"updated_at"`
	CategoryName        *string `json:"category_name"`
	CategoryIcon        *string `json:"category_icon"`
	CategoryIsSystem    *int64  `json:"category_is_system"`
	SubcategoryName     *string `json:"subcategory_name"`
	AccountName         *string `json:"account_name"`
	TransferAccountName *string `json:"transfer_account_name"`
	TransferIsOut       int64   `json:"transfer_is_out"`
	CreditPaymentLinked int64   `json:"credit_payment_linked"`
}

func (q *Queries) ListTransactionsFilteredDateDesc(ctx context.Context, arg ListTransactionsFilteredDateDescParams) ([]ListTransactionsFilteredDateDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsFilteredDateDesc,
		arg.UserID,
		arg.Column2,
		arg.AccountID,
		arg.Column4,
		arg.Type,
		arg.Column6,
		arg.CategoryID,
		arg.Column8,
		arg.Kind,
		arg.Column10,
		arg.TransactionDate,
		arg.Column12,
		arg.TransactionDate_2,
		arg.Column14,
		arg.Column15,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsFilteredDateDescRow{}
	for rows.Next() {
		var i ListTransactionsFilteredDateDescRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Type,
			&i.Kind,
			&i.Amount,
			&i.Description,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.TransferGroupID,
			&i.TransferAccountID,
			&i.TransactionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryIsSystem,
			&i.SubcategoryName,
			&i.AccountName,
			&i.TransferAccountName,
			&i.TransferIsOut,
			&i.CreditPaymentLinked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumExpenseManual = `-- name: SumExpenseManual :one
SELECT COALESCE(SUM(amount), 0) AS total
FROM transactions
WHERE user_id = ? AND account_id = ? AND type = 'expense' AND kind = 'manual'
  AND affects_balance = 1 AND transaction_date <= ?
`

type SumExpenseManualParams struct {
	UserID          string `json:"user_id"`
	AccountID       string `json:"account_id"`
	TransactionDate string `json:"transaction_date"`
}

func (q *Queries) SumExpenseManual(ctx context.Context, arg SumExpenseManualParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumExpenseManual, arg.UserID, arg.AccountID, arg.TransactionDate)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const sumFutureExpenseInRange = `-- name: SumFutureExpenseInRange :one
SELECT COALESCE(SUM(amount), 0) AS total
FROM transactions
WHERE user_id = ? AND account_id = ? AND type = 'expense' AND kind = 'future'
  AND affects_balance = 1 AND transaction_date >= ? AND transaction_date <= ?
`

type SumFutureExpenseInRangeParams struct {
	UserID            string `json:"user_id"`
	AccountID         string `json:"account_id"`
	TransactionDate   string `json:"transaction_date"`
	TransactionDate_2 string `json:"transaction_date_2"`
}

func (q *Queries) SumFutureExpenseInRange(ctx context.Context, arg SumFutureExpenseInRangeParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumFutureExpenseInRange,
		arg.UserID,
		arg.AccountID,
		arg.TransactionDate,
		arg.TransactionDate_2,
	)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const sumFutureIncomeInRange = `-- name: SumFutureIncomeInRange :one
SELECT COALESCE(SUM(amount), 0) AS total
FROM transactions
WHERE user_id = ? AND account_id = ? AND type = 'income' AND kind = 'future'
  AND affects_balance = 1 AND transaction_date >= ? AND transaction_date <= ?
`

type SumFutureIncomeInRangeParams struct {
	UserID            string `json:"user_id"`
	AccountID         string `json:"account_id"`
	TransactionDate   string `json:"transaction_date"`
	TransactionDate_2 string `json:"transaction_date_2"`
}

func (q *Queries) SumFutureIncomeInRange(ctx context.Context, arg SumFutureIncomeInRangeParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumFutureIncomeInRange,
		arg.UserID,
		arg.AccountID,
		arg.TransactionDate,
		arg.TransactionDate_2,
	)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const sumFutureTransferInInRange = `-- name: SumFutureTransferInInRange :one
SELECT COALESCE(SUM(t.amount), 0) AS total
FROM transactions t
WHERE t.user_id = ? AND t.account_id = ? AND t.type = 'transfer' AND kind = 'future'
  AND t.affects_balance = 1 AND t.transaction_date >= ? AND t.transaction_date <= ?
  AND t.transfer_group_id IS NOT NULL
  AND t.id = (
    SELECT x.id FROM transactions x
    WHERE x.transfer_group_id = t.transfer_group_id
    ORDER BY x.created_at ASC, x.id ASC
    LIMIT 1 OFFSET 1
  )
`

type SumFutureTransferInInRangeParams struct {
	UserID            string `json:"user_id"`
	AccountID         string `json:"account_id"`
	TransactionDate   string `json:"transaction_date"`
	TransactionDate_2 string `json:"transaction_date_2"`
}

func (q *Queries) SumFutureTransferInInRange(ctx context.Context, arg SumFutureTransferInInRangeParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumFutureTransferInInRange,
		arg.UserID,
		arg.AccountID,
		arg.TransactionDate,
		arg.TransactionDate_2,
	)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const sumFutureTransferOutInRange = `-- name: SumFutureTransferOutInRange :one
SELECT COALESCE(SUM(t.amount), 0) AS total
FROM transactions t
WHERE t.user_id = ? AND t.account_id = ? AND t.type = 'transfer' AND kind = 'future'
  AND t.affects_balance = 1 AND t.transaction_date >= ? AND t.transaction_date <= ?
  AND t.transfer_group_id IS NOT NULL
  AND t.id = (
    SELECT x.id FROM transactions x
    WHERE x.transfer_group_id = t.transfer_group_id
    ORDER BY x.created_at ASC, x.id ASC
    LIMIT 1
  )
`

type SumFutureTransferOutInRangeParams struct {
	UserID            string `json:"user_id"`
	AccountID         string `json:"account_id"`
	TransactionDate   string `json:"transaction_date"`
	TransactionDate_2 string `json:"transaction_date_2"`
}

func (q *Queries) SumFutureTransferOutInRange(ctx context.Context, arg SumFutureTransferOutInRangeParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumFutureTransferOutInRange,
		arg.UserID,
		arg.AccountID,
		arg.TransactionDate,
		arg.TransactionDate_2,
	)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const sumIncomeManual = `-- name: SumIncomeManual :one
SELECT COALESCE(SUM(amount), 0) AS total
FROM transactions
WHERE user_id = ? AND account_id = ? AND type = 'income' AND kind = 'manual'
  AND affects_balance = 1 AND transaction_date <= ?
`

type SumIncomeManualParams struct {
	UserID          string `json:"user_id"`
	AccountID       string `json:"account_id"`
	TransactionDate string `json:"transaction_date"`
}

func (q *Queries) SumIncomeManual(ctx context.Context, arg SumIncomeManualParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumIncomeManual, arg.UserID, arg.AccountID, arg.TransactionDate)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const sumTransferInManual = `-- name: SumTransferInManual :one
SELECT COALESCE(SUM(t.amount), 0) AS total
FROM transactions t
WHERE t.user_id = ? AND t.account_id = ? AND t.type = 'transfer' AND t.kind = 'manual'
  AND t.affects_balance = 1 AND t.transaction_date <= ?
  AND t.transfer_group_id IS NOT NULL
  AND t.id = (
    SELECT x.id FROM transactions x
    WHERE x.transfer_group_id = t.transfer_group_id
    ORDER BY x.created_at ASC, x.id ASC
    LIMIT 1 OFFSET 1
  )
`

type SumTransferInManualParams struct {
	UserID          string `json:"user_id"`
	AccountID       string `json:"account_id"`
	TransactionDate string `json:"transaction_date"`
}

func (q *Queries) SumTransferInManual(ctx context.Context, arg SumTransferInManualParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumTransferInManual, arg.UserID, arg.AccountID, arg.TransactionDate)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const sumTransferOutManual = `-- name: SumTransferOutManual :one
SELECT COALESCE(SUM(t.amount), 0) AS total
FROM transactions t
WHERE t.user_id = ? AND t.account_id = ? AND t.type = 'transfer' AND t.kind = 'manual'
  AND t.affects_balance = 1 AND t.transaction_date <= ?
  AND t.transfer_group_id IS NOT NULL
  AND t.id = (
    SELECT x.id FROM transactions x
    WHERE x.transfer_group_id = t.transfer_group_id
    ORDER BY x.created_at ASC, x.id ASC
    LIMIT 1
  )
`

type SumTransferOutManualParams struct {
	UserID          string `json:"user_id"`
	AccountID       string `json:"account_id"`
	TransactionDate string `json:"transaction_date"`
}

func (q *Queries) SumTransferOutManual(ctx context.Context, arg SumTransferOutManualParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumTransferOutManual, arg.UserID, arg.AccountID, arg.TransactionDate)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE transactions
SET account_id = ?, type = ?, kind = ?, amount = ?, description = ?,
    category_id = ?, subcategory_id = ?, transaction_date = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateTransactionParams struct {
	AccountID       string  `json:"account_id"`
	Type            string  `json:"type"`
	Kind            string  `json:"kind"`
	Amount          int64   `json:"amount"`
	Description     *string `json:"description"`
	CategoryID      *string `json:"category_id"`
	SubcategoryID   *string `json:"subcategory_id"`
	TransactionDate string  `json:"transaction_date"`
	UpdatedAt       string  `json:"updated_at"`
	ID              string  `json:"id"`
	UserID          string  `json:"user_id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, updateTransaction,
		arg.AccountID,
		arg.Type,
		arg.Kind,
		arg.Amount,
		arg.Description,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.TransactionDate,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateTransferAccountID = `-- name: UpdateTransferAccountID :exec
UPDATE transactions SET transfer_account_id = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type UpdateTransferAccountIDParams struct {
	TransferAccountID *string `json:"transfer_account_id"`
	UpdatedAt         string  `json:"updated_at"`
	ID                string  `json:"id"`
	UserID            string  `json:"user_id"`
}

func (q *Queries) UpdateTransferAccountID(ctx context.Context, arg UpdateTransferAccountIDParams) error {
	_, err := q.db.ExecContext(ctx, updateTransferAccountID,
		arg.TransferAccountID,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateTransferCreatedAt = `-- name: UpdateTransferCreatedAt :exec
UPDATE transactions SET created_at = ? WHERE id = ? AND user_id = ?
`

type UpdateTransferCreatedAtParams struct {
	CreatedAt string `json:"created_at"`
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) UpdateTransferCreatedAt(ctx context.Context, arg UpdateTransferCreatedAtParams) error {
	_, err := q.db.ExecContext(ctx, updateTransferCreatedAt, arg.CreatedAt, arg.ID, arg.UserID)
	return err
}

const updateTransferLeg = `-- name: UpdateTransferLeg :exec
UPDATE transactions
SET account_id = ?, amount = ?, description = ?, transaction_date = ?,
    kind = ?, updated_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateTransferLegParams struct {
	AccountID       string  `json:"account_id"`
	Amount          int64   `json:"amount"`
	Description     *string `json:"description"`
	TransactionDate string  `json:"transaction_date"`
	Kind            string  `json:"kind"`
	UpdatedAt       string  `json:"updated_at"`
	ID              string  `json:"id"`
	UserID          string  `json:"user_id"`
}

func (q *Queries) UpdateTransferLeg(ctx context.Context, arg UpdateTransferLegParams) error {
	_, err := q.db.ExecContext(ctx, updateTransferLeg,
		arg.AccountID,
		arg.Amount,
		arg.Description,
		arg.TransactionDate,
		arg.Kind,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}
