// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_change_events.sql

package sqlc

import (
	"context"
)

const listUserChangeEventsAfter = `-- name: ListUserChangeEventsAfter :many
SELECT id, user_id, entity_type, entity_id, action, occurred_at
FROM user_change_events
WHERE user_id = ?1
  AND id > ?2
  AND (?3 = '' OR occurred_at >= ?3)
ORDER BY id ASC
LIMIT ?4
`

type ListUserChangeEventsAfterParams struct {
	UserID  string      `json:"user_id"`
	AfterID int64       `json:"after_id"`
	Since   interface{} `json:"since"`
	Limit   int64       `json:"limit"`
}

func (q *Queries) ListUserChangeEventsAfter(ctx context.Context, arg ListUserChangeEventsAfterParams) ([]UserChangeEvent, error) {
	rows, err := q.db.QueryContext(ctx, listUserChangeEventsAfter,
		arg.UserID,
		arg.AfterID,
		arg.Since,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserChangeEvent{}
	for rows.Next() {
		var i UserChangeEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
