// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*) FROM users WHERE is_admin = 1
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserAdminItem = `-- name: GetUserAdminItem :one
SELECT id, login, COALESCE(display_name, '') AS display_name, is_admin, status, created_at
FROM users WHERE id = ?
`

type GetUserAdminItemRow struct {
	ID          string `json:"id"`
	Login       string `json:"login"`
	DisplayName string `json:"display_name"`
	IsAdmin     int64  `json:"is_admin"`
	Status      string `json:"status"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) GetUserAdminItem(ctx context.Context, id string) (GetUserAdminItemRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAdminItem, id)
	var i GetUserAdminItemRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.DisplayName,
		&i.IsAdmin,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, login, COALESCE(display_name, '') AS display_name, is_admin, status, language, currency, timezone, theme
FROM users WHERE id = ?
`

type GetUserByIDRow struct {
	ID          string `json:"id"`
	Login       string `json:"login"`
	DisplayName string `json:"display_name"`
	IsAdmin     int64  `json:"is_admin"`
	Status      string `json:"status"`
	Language    string `json:"language"`
	Currency    string `json:"currency"`
	Timezone    string `json:"timezone"`
	Theme       string `json:"theme"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.DisplayName,
		&i.IsAdmin,
		&i.Status,
		&i.Language,
		&i.Currency,
		&i.Timezone,
		&i.Theme,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, COALESCE(display_name, '') AS display_name, is_admin, status, language, currency, timezone, theme, password_hash
FROM users WHERE login = ?
`

type GetUserByLoginRow struct {
	ID           string `json:"id"`
	Login        string `json:"login"`
	DisplayName  string `json:"display_name"`
	IsAdmin      int64  `json:"is_admin"`
	Status       string `json:"status"`
	Language     string `json:"language"`
	Currency     string `json:"currency"`
	Timezone     string `json:"timezone"`
	Theme        string `json:"theme"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (GetUserByLoginRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByLogin, login)
	var i GetUserByLoginRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.DisplayName,
		&i.IsAdmin,
		&i.Status,
		&i.Language,
		&i.Currency,
		&i.Timezone,
		&i.Theme,
		&i.PasswordHash,
	)
	return i, err
}

const getUserCreatedAtAndStatus = `-- name: GetUserCreatedAtAndStatus :one
SELECT created_at, status FROM users WHERE id = ?
`

type GetUserCreatedAtAndStatusRow struct {
	CreatedAt string `json:"created_at"`
	Status    string `json:"status"`
}

func (q *Queries) GetUserCreatedAtAndStatus(ctx context.Context, id string) (GetUserCreatedAtAndStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getUserCreatedAtAndStatus, id)
	var i GetUserCreatedAtAndStatusRow
	err := row.Scan(&i.CreatedAt, &i.Status)
	return i, err
}

const getUserFormatting = `-- name: GetUserFormatting :one
SELECT language, timezone, currency FROM users WHERE id = ?
`

type GetUserFormattingRow struct {
	Language string `json:"language"`
	Timezone string `json:"timezone"`
	Currency string `json:"currency"`
}

func (q *Queries) GetUserFormatting(ctx context.Context, id string) (GetUserFormattingRow, error) {
	row := q.db.QueryRowContext(ctx, getUserFormatting, id)
	var i GetUserFormattingRow
	err := row.Scan(&i.Language, &i.Timezone, &i.Currency)
	return i, err
}

const getUserIsAdmin = `-- name: GetUserIsAdmin :one
SELECT is_admin FROM users WHERE id = ?
`

func (q *Queries) GetUserIsAdmin(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserIsAdmin, id)
	var is_admin int64
	err := row.Scan(&is_admin)
	return is_admin, err
}

const getUserLanguage = `-- name: GetUserLanguage :one
SELECT language FROM users WHERE id = ?
`

func (q *Queries) GetUserLanguage(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserLanguage, id)
	var language string
	err := row.Scan(&language)
	return language, err
}

const getUserLogin = `-- name: GetUserLogin :one
SELECT login FROM users WHERE id = ?
`

func (q *Queries) GetUserLogin(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserLogin, id)
	var login string
	err := row.Scan(&login)
	return login, err
}

const getUserLoginAndStatus = `-- name: GetUserLoginAndStatus :one
SELECT login, status FROM users WHERE id = ?
`

type GetUserLoginAndStatusRow struct {
	Login  string `json:"login"`
	Status string `json:"status"`
}

func (q *Queries) GetUserLoginAndStatus(ctx context.Context, id string) (GetUserLoginAndStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getUserLoginAndStatus, id)
	var i GetUserLoginAndStatusRow
	err := row.Scan(&i.Login, &i.Status)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, login, password_hash, display_name, is_admin, status, theme)
VALUES (?, ?, ?, ?, ?, ?, 'system')
`

type InsertUserParams struct {
	ID           string  `json:"id"`
	Login        string  `json:"login"`
	PasswordHash string  `json:"password_hash"`
	DisplayName  *string `json:"display_name"`
	IsAdmin      int64   `json:"is_admin"`
	Status       string  `json:"status"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.ID,
		arg.Login,
		arg.PasswordHash,
		arg.DisplayName,
		arg.IsAdmin,
		arg.Status,
	)
	return err
}

const listAdminUserIDs = `-- name: ListAdminUserIDs :many
SELECT id FROM users WHERE is_admin = 1
`

func (q *Queries) ListAdminUserIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAdminUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIDs = `-- name: ListUserIDs :many
SELECT id FROM users
`

func (q *Queries) ListUserIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, login, COALESCE(display_name, '') AS display_name, is_admin, status, created_at
FROM users ORDER BY created_at ASC
`

type ListUsersRow struct {
	ID          string `json:"id"`
	Login       string `json:"login"`
	DisplayName string `json:"display_name"`
	IsAdmin     int64  `json:"is_admin"`
	Status      string `json:"status"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Login,
			&i.DisplayName,
			&i.IsAdmin,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithTimezone = `-- name: ListUsersWithTimezone :many
SELECT id, timezone FROM users
`

type ListUsersWithTimezoneRow struct {
	ID       string `json:"id"`
	Timezone string `json:"timezone"`
}

func (q *Queries) ListUsersWithTimezone(ctx context.Context) ([]ListUsersWithTimezoneRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersWithTimezone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersWithTimezoneRow{}
	for rows.Next() {
		var i ListUsersWithTimezoneRow
		if err := rows.Scan(&i.ID, &i.Timezone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users SET password_hash = ?, updated_at = ? WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	UpdatedAt    string `json:"updated_at"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET display_name = ?, language = ?, currency = ?, timezone = ?, theme = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateUserProfileParams struct {
	DisplayName *string `json:"display_name"`
	Language    string  `json:"language"`
	Currency    string  `json:"currency"`
	Timezone    string  `json:"timezone"`
	Theme       string  `json:"theme"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Language,
		arg.Currency,
		arg.Timezone,
		arg.Theme,
		arg.ID,
	)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET status = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateUserStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.Status, arg.ID)
	return err
}
