// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_data.sql

package sqlc

import (
	"context"
)

const clearUserAccountSelfRefs = `-- name: ClearUserAccountSelfRefs :exec
UPDATE accounts
SET payment_account_id = NULL,
    auto_topup_source_account_id = NULL
WHERE user_id = ?
`

func (q *Queries) ClearUserAccountSelfRefs(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, clearUserAccountSelfRefs, userID)
	return err
}

const deleteUserAccounts = `-- name: DeleteUserAccounts :exec
DELETE FROM accounts WHERE user_id = ?
`

func (q *Queries) DeleteUserAccounts(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserAccounts, userID)
	return err
}

const deleteUserBudgets = `-- name: DeleteUserBudgets :exec
DELETE FROM budgets WHERE user_id = ?
`

func (q *Queries) DeleteUserBudgets(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserBudgets, userID)
	return err
}

const deleteUserCategories = `-- name: DeleteUserCategories :exec
DELETE FROM categories WHERE user_id = ?
`

func (q *Queries) DeleteUserCategories(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserCategories, userID)
	return err
}

const deleteUserChangeEvents = `-- name: DeleteUserChangeEvents :exec
DELETE FROM user_change_events WHERE user_id = ?
`

func (q *Queries) DeleteUserChangeEvents(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserChangeEvents, userID)
	return err
}

const deleteUserCreditPayments = `-- name: DeleteUserCreditPayments :exec

DELETE FROM credit_payments
WHERE credit_id IN (SELECT id FROM credits WHERE user_id = ?)
`

// Wipe financial data for one user (keep profile, sessions, API tokens, notification settings).
func (q *Queries) DeleteUserCreditPayments(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserCreditPayments, userID)
	return err
}

const deleteUserCredits = `-- name: DeleteUserCredits :exec
DELETE FROM credits WHERE user_id = ?
`

func (q *Queries) DeleteUserCredits(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserCredits, userID)
	return err
}

const deleteUserDebtTransactions = `-- name: DeleteUserDebtTransactions :exec
DELETE FROM debt_transactions
WHERE debt_id IN (SELECT id FROM debts WHERE user_id = ?)
`

func (q *Queries) DeleteUserDebtTransactions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserDebtTransactions, userID)
	return err
}

const deleteUserDebtors = `-- name: DeleteUserDebtors :exec
DELETE FROM debtors WHERE user_id = ?
`

func (q *Queries) DeleteUserDebtors(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserDebtors, userID)
	return err
}

const deleteUserDebts = `-- name: DeleteUserDebts :exec
DELETE FROM debts WHERE user_id = ?
`

func (q *Queries) DeleteUserDebts(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserDebts, userID)
	return err
}

const deleteUserImportIdempotency = `-- name: DeleteUserImportIdempotency :exec
DELETE FROM import_idempotency WHERE user_id = ?
`

func (q *Queries) DeleteUserImportIdempotency(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserImportIdempotency, userID)
	return err
}

const deleteUserImportJobs = `-- name: DeleteUserImportJobs :exec
DELETE FROM import_jobs WHERE user_id = ?
`

func (q *Queries) DeleteUserImportJobs(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserImportJobs, userID)
	return err
}

const deleteUserMerchants = `-- name: DeleteUserMerchants :exec
DELETE FROM merchants WHERE user_id = ?
`

func (q *Queries) DeleteUserMerchants(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserMerchants, userID)
	return err
}

const deleteUserNotificationLog = `-- name: DeleteUserNotificationLog :exec
DELETE FROM notification_log WHERE user_id = ?
`

func (q *Queries) DeleteUserNotificationLog(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserNotificationLog, userID)
	return err
}

const deleteUserRecurringOperations = `-- name: DeleteUserRecurringOperations :exec
DELETE FROM recurring_operations WHERE user_id = ?
`

func (q *Queries) DeleteUserRecurringOperations(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserRecurringOperations, userID)
	return err
}

const deleteUserSubscriptions = `-- name: DeleteUserSubscriptions :exec
DELETE FROM subscriptions WHERE user_id = ?
`

func (q *Queries) DeleteUserSubscriptions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSubscriptions, userID)
	return err
}

const deleteUserTags = `-- name: DeleteUserTags :exec
DELETE FROM tags WHERE user_id = ?
`

func (q *Queries) DeleteUserTags(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserTags, userID)
	return err
}

const deleteUserTransactionTemplates = `-- name: DeleteUserTransactionTemplates :exec
DELETE FROM transaction_templates WHERE user_id = ?
`

func (q *Queries) DeleteUserTransactionTemplates(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserTransactionTemplates, userID)
	return err
}

const deleteUserTransactions = `-- name: DeleteUserTransactions :exec
DELETE FROM transactions WHERE user_id = ?
`

func (q *Queries) DeleteUserTransactions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserTransactions, userID)
	return err
}
